### ISSUE TITLE
figures on readthedocs not related to notebook

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#100]
Some of the figures (in the first example) are from another notebook (the CCF and ACF notebook I recently made). No idea how this is happening, but they figures are not related to the code above.

**Comment by raoulcollenteur** [comment]
Hmmm, I think we had this issue before. I would like to show the notebooks differently anyway on the documentation website (e.g., https://sphinx-nbexamples.readthedocs.io/en/latest/examples/index.html). The automatic conversion is also not working right now. Maybe we can solve all problems at once and automate all this.. :)

That said, I think the CCF / ACF notebook should actually not be there at all but I forgot to remove it during PR. Questions is, where should we store these kind of notebooks?

**Comment by rubencalje** [comment]
> That said, I think the CCF / ACF notebook should actually not be there at all but I forgot to remove it during PR. Questions is, where should we store these kind of notebooks?

https://github.com/pastas/pastas_research?

I can look into this (wrong figures), but not if we are going to change everything. I think it is fine now,  except for the wrong figures. So are you going to change it Raoul?

**Comment by rubencalje** [comment]
I fixed this in the developer branch, by giving each notebook its own folder in the documentation. Now the figures cannot be overwitten by the next notebook anymore.  See the commit: https://github.com/pastas/pastas/commit/524738f634adae9e8a187d13fcff52bce38a0706

**Comment by raoulcollenteur** [comment]
Cool! looks good. Closing the issue then :)
