### ISSUE TITLE
WellModel randomly results in different fit results

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#102]
I've been trying to implement the WellModel in a project I'm working on. The idea is to put all the wells in the same aquifer in one WellModel which then calculates one response function for all the wells which is only scaled by the distance from each well to the observation point. 

The way I've done this is by passing an extra parameter to `pastas.Hantush` containing the distance to the well _r_. The parameter _rho_ passed to leastsquares is now equal to 1 / _lambda_, and is multiplied by the distance _r_ when `pastas.Hantush.step()` is called. 

I've made an [example notebook](https://github.com/pastas/pastas/blob/wellmodel/examples/notebooks/wellmodel_consistency_problem.ipynb) that highlights the problem. I've created simple models with one Well with and without recharge I've tried adding the well with StressModel and with the WellModel. The model with a WellModel and recharge randomly yields different fit results (see figure at the end of the notebook). I haven't been able to establish why this happens. It would be great if we could get this to work somehow... So any ideas are welcome!

**Comment by raoulcollenteur** [comment]
Nice, looking forward to getting this to work too! 

Which Python/Pandas/Numpy version are you using? I have seen this behaviour in older python versions (<3.5??) where dictionaries were not ordered automatically. That is, the order of which the stress models are either added (but this looks the same) or the order the stress models are simulated. That is:

for s in ml.stressmodels.items():
     print(s)

would return different orders of s..

Is this happening?

**Comment by raoulcollenteur** [comment]
Cannot reproduce the problem with Python 3.7, Pandas 0.23.4 and numpy 1.15. So it looks like we need to upgrade a dependency to Pastas.

**Comment by dbrakenhoff** [comment]
I'm on Python 3.7.2, Pandas 0.23.4 and Numpy 1.15.4.

![image](https://user-images.githubusercontent.com/6552225/55642885-ff07e680-57d1-11e9-9eb5-d3e5cbbbe988.png)

Just ran again, and as the image shows the problem still occurs on my side. The stresses are always ordered in the order I added them, so that doesn't seem to be the issue. I did see that the WellModel was converted to a StressModel object in `ml.stressmodels`. Shouldn't it remain a WellModel? Not sure if that is relevant somehow.

**Comment by raoulcollenteur** [comment]
I ran it again and here is what I get. Maybe it is Scipy (Although I cannot imagine)? I am on 1.1.0.

![image](https://user-images.githubusercontent.com/12051167/55680548-39c96600-591b-11e9-8d40-06e07ae829e2.png)

**Comment by mbakker7** [comment]
For what it is worth, I get Raoul's result for numpy 1.15.1, pandas 0.23.4,
scipy 1.1.0.

On a Mac

**Comment by dbrakenhoff** [comment]
I'm on Scipy 1.1.0 as well. I will test it on colleagues computers today, see what we get then...

**Comment by rubencalje** [comment]
Hmm, the first time I ran it I got flat-lines, but the second time I got Davíd's result, strange...

**Comment by dbrakenhoff** [comment]
Onno did two runs on his PC (so he solved 40 models) and obtained the expected result (all EVPs similar to the "Normal Model"). I installed a copy of his environment on my PC and ran again, but for me this still resulted in random runs yielding an EVP of about 30%. 
- python 3.7.3, pandas 0.24.2, numpy 1.15.4, scipy 1.1.0

I also tried running with another environment I already had on my PC:
- Python 3.7.2, Pandas version: 0.24.2, Numpy version: 1.15.4, Scipy version: 1.2.0, Pastas version: 0.10.0b. 

This has so far led to all runs yielding the 30% EVP (N=40), so seemingly consistent, but not the expected result.

I also tried upgrading Pandas and Scipy in my base environment to Pandas 0.23.4 -> 0.24.2 and Scipy 1.1.0 -> 1.2.1 and ran again. Still same problem.

**Comment by mbakker7** [comment]
Can you make the problem a bit simpler? Give us 1 model that goes wrong?
Maybe reduce the length of the series? The shorter the example that is
reproducible (at least on your machine) the better.

**Comment by dbrakenhoff** [comment]
I've uploaded a [simple version of the notebook](https://github.com/pastas/pastas/blob/wellmodel/examples/notebooks/wellmodel_consistency_problem_simple.ipynb) which contains only the relevant model. I also added a tmin and tmax for slicing the timeseries (prior to them being passed to Pastas) to reduce the length of the series.

When I add the tmin and tmax slice step prior to building the model, the model now seems to consistently give the expected result. I haven't exhaustively tried different combinations of tmin and tmax values but passing the values pastas derives from the original (non-sliced) series has produced consistent results after 200 model runs. 

So... any ideas why that would matter? And why that would only matter on 2/5 computers we've tested it on so far...? It seems more PC related than Python related (using my environment on Onno's PC gave Onno good results, using Onno's environment (which was working for him) on my PC still gave me the same problem).

**Comment by raoulcollenteur** [comment]
Couple of things have changed in Scipy 1.2 i saw, but nothing that affects this I think.

Let's start ruling things out in the for loop:
- replace the EVP by something else, e.g., ml.simulate().sum()
- remove freq=14D

Then, does the problem still exist?

**Comment by mbakker7** [comment]
Zou het afrondingsfouten kunnen zijn bij het schatten van een afgeleide?
Als je dan grote reeksen hebt, en dus veel fouten moet opsommen, zouden er
onnauwkeurig afgeleiden uit kunnen komen.

Is LMFIT nog operationeel? Kun je het daarmee oplossen?

En fmin? Werkt fmin? Dat zou ook handig zijn. Misschien moeten we dat
inbouwen.

Ik ga morgen met Pastas aan de gang. Misschien probeer ik dat er in te
krijgen.

Groet,

Mark

**Comment by dbrakenhoff** [comment]
A summary of some of the findings so far:
- The problem has been observed on two PCs so far
- The problem is so far not reproducible on 2 Macs and one Windows PC

On my PC:
- The Python environment I use leads to either random results (one of two possible outcomes for EVP) or yields consistently bad fit results. But it does not seem to be determined by Python, Scipy, Numpy or Pandas versions, at least so far as I can tell.
- Using my Python environment on the Windows PC that did not show the problem initially, did not cause the problem to occur on that PC, suggesting it is also somehow related to specific computers. 
- @raoulcollenteur, changing the frequency to  `freq="D"` does not solve the problem
- Slicing the timeseries prior to creating the Pastas model seems to lead to more consistently good fit results being obtained. Though I did observe two possible outcomes in EVP that were .3 % apart, so maybe same problem, but somehow the two possible outcomes are both close together in that case.
- Changing the method to `method="dogbox"` seems to lead to consistently good results. Added benefit is that this method is 2-3 times faster than `method="trf"` when solving the model. Is there a reason we're using "trf" as default? A colleague (Frans) suggested dogbox may be more appropriate for our problem most of the time.

I'm not sure about the status of LmFit as a Solver. @raoulcollenteur, do you know if this still works well? @mbakker7, if you do implement fmin, let me know and I will try it!

**Comment by raoulcollenteur** [comment]
- I have not used LmFit and it is not maintained so I would be surprised if it would still work. However, it should be really easy to fix again if broken (which in itself would be helpful too).
- we use the default method that Scipy uses. So no specific choice has been made. If "dogbox" is better then "trf" we would need some study proving that I think, in the spirit of the Pastas project. Scipy docs mention: "particularly suitable for large sparse problems with bounds. Generally robust method.".
- @dbrakenhoff What about using another measure instead of EVP?

**Comment by dbrakenhoff** [comment]
- If I have some time this week, I'll take a look at LmFit.
- I think 'trf' is probably the most robust method, but it could well be that our Pastas optimizations run fine with 'dogbox'. I agree it would be necessary to study that some more before changing anything though.
- If I do ml.simulate().sum(), I find the same pattern to the EVP per run (randomly showing one of two possible outcomes), though the differences between the two outcomes is relatively small.

**Comment by raoulcollenteur** [comment]
Update: I just checked and LmfitSolve is still working as it should :)

@dbrakenhoff can you check if the problem also exists with this solver?

**Comment by raoulcollenteur** [comment]
@dbrakenhoff, Any progress on this?

**Comment by dbrakenhoff** [comment]
Unfortunately not much, but to add some more vagueness to the issue, I can't seem to reproduce the problem anymore. (I did have to reinstall my Python at some point, so I'm sure my environment isn't the same as before).

So ... though it's all been a bit weird, until i can find an example of this issue again, I will assume everything is working just fine now and this was an issue related to my Python environment in combination with my PC.

I do think it is smart to store the notebooks with which i previously showed this behavior somewhere. What would be a good location for that? Our pastas_research repo? I'll also run those notebooks on the PCs we did the tests on before just to be sure the issue has "disappeared".

Also LmFit consistently yields an EVP of 0 when trying to solve models with a WellModel. Haven't looked into that yet, but just fyi.

**Comment by dbrakenhoff** [comment]
Ah, I think i may have cheered to soon, just managed to reproduce the issue ... More on that in a bit

**Comment by mbakker7** [comment]
You want to elaborate?

**Comment by dbrakenhoff** [comment]
I do, but the issue is so frustratingly difficult to examine. I've written down what happened as I was posting my messages yesterday. This is sort of a log now to recall the steps I took.

1. I ran the notebooks that showed the problems before and did not get any odd behaviour.
2. I realized I was maybe on the wrong pastas branch, so i checked out my wellmodel branch
3. I reran the notebooks and suddenly the issue from before appeared again (one of two different fit results when using method="trf"). 
4. Then I figured I'd update wellmodel from the dev branch, because by now the branch was running behind quite a bit the current state of pastas.
5. I reran the notebooks again, and this time there weren't any issues (fits remained constant in subsequent runs). Oddly, LmFitSolve suddenly started giving results where earlier it would always result in an evp of 0.0 in models with a WellModel.
6. Then I found one model still being weird (in this case different fit results after every run with "trf"). This seems to be a different problem to the earlier one (not 2 possible results, but different after every solve).
7. I then found out I hadn't yet implemented the change I proposed in #108 in my branch. 
8. I made the change and re-ran all the notebooks.
9. The models, including the one from 6 are now yielding consistent results with all methods, including "trf".

My conclusion therefore:
- The problem with obtaining one of two possible fit results with `method="trf"` does not occur on my PC anymore with the current version of pastas in the wellmodel branch.
- The problem of a different model yielding different fit results after each run with `method="trf"` was solved by #108.

I will close the issue once wellmodel is implemented in the dev branch, and I've performed the tests on a few other PCs.

**Comment by raoulcollenteur** [comment]
@dbrakenhoff , I just merged PR #129 . Can we close this now or you want to keep it open for a bit longer?

**Comment by dbrakenhoff** [comment]
We can close it.
