### ISSUE TITLE
Change default parameter bounds of step response function

### ISSUE THREAD

**Issue by OnnoEbbens** [pastas/pastas#103]
I create a pastas model from an oseries with a sudden increase (step trend) using the rfunc 'one'. The parameter bounds (pmin, pmax) of this response function are set to (0,100) by default in the `set_parameter` method of the `One` class (since `up=True` by default). I would rather have a parameter bound of (-100, 100) by default, so both positive and negative responses are fitted. Is there a reason only a positive step response will be fit when using the default settings?

**Comment by raoulcollenteur** [comment]
I never really tested the StepModel after programming it, so interesting to see it put to use, an example notebook would be welcome ;)

That said, the `One` rfunc is used as the constant in the `Model`, and the positive or negative sign is determined by the `up` keyword. We like(d) the idea of knowing whether a stress has a positive or negative impact up front I think. To use it now, you can manually change the bounds with ml.set_pmin and set_pmax. 

Would actually maybe be better to have different boundaries here. For example, I am not sure what happens with negative oseries now.

**Comment by raoulcollenteur** [comment]
I check and the One response is used by FactorModel, LinearTrend, StepTrend and Constant.

The latter is used the most, but internally changes the boundaries to np.nan. This means no boundaries.

We could unbound One by default and remove that code from Constant. I would not be in favour of using (-100, 100) as this value would depend on the units used and the time series studied.

@OnnoEbbens, Can you do a PR with a proposal for the change?

**Comment by raoulcollenteur** [comment]
Related to Issue #131 and fixed by PR #130. Closing this issue.
