### ISSUE TITLE
Automate example notebook on readthedocs further

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#106]
If a notebook is removed or added, it does not yet turn up in the example list on readthedocs. Let's automate this process further so we don't have to look at it every time we add or remove a NB.

**Comment by rubencalje** [comment]
We could automate this, but I think this is the way sphinx is intended. When you add new stuff, you manually add this to the repository (using 'make html' in a command prompt), and you can maybe change the way you want things to look (the order maybe?). The same can be said about the api-docs. That's also why the links to the notebooks and the api-docs are in the repository.

**Comment by rubencalje** [comment]
The **contents** of the notebooks and the api-docs are automatically updated

**Comment by raoulcollenteur** [comment]
Close this issue?
