### ISSUE TITLE
remove keyword "original" from get_stress method in stress models

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#107]
This keyword is inconsistently implemented and I think quite pointless as the original series is what the user provides anyway. Would suggest to remove this from the few get_stress method where it still remains to keep things easy. Anyone against this?

**Comment by mbakker7** [comment]
Do we never want to do something to the original stress after adding it to
a stressmodel? Then I have no objections.

**Comment by raoulcollenteur** [comment]
This option was only there to obtain the original time series and not to edit them. But it is only implemented in StressModel, not even StressModel2 or any of the others. So I don't think it was ever used. Commit coming up to remove this.
