### ISSUE TITLE
Change paths in examples and notebooks to use os.path.join

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#110]
Is has been suggested to change all paths defined in Pastas to use os.path.join to make Pastas examples portable across OS's. Anybody has time to go through all the notebooks and example python scripts to change this? @dbrakenhoff, @rubencalje, @OnnoEbbens ?

**Comment by raoulcollenteur** [comment]
@rubencalje I see you have been working on this? Could we already close the issue or does this need some more work?

**Comment by rubencalje** [comment]
No, I have changed the paths to os.path.join in some examples that I changed anyway, but did not check everything. I think we should leave it open. It is not high on my priority-list however (as I have not seen the light yet, and am still on Windows)...

**Comment by raoulcollenteur** [comment]
The thing here is that Windows uses backslashes and all other (UNIX) systems use forward slashes. We have implemented everything with forward slashes and since python has a hack that makes this work for Windows as well we don't run into this problem.

Let's stick to using forward slashes in the examples and close this issue.

**Comment by mbakker7** [comment]
So why was it suggested in the first place? It was a suggestion from
Jeremy, so I presume there is an advantage. I will ask him.
