### ISSUE TITLE
Add Notebooks to Travis CI testing scheme

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#111]
We should add the jupyter notebooks to Travis CI to make sure they are working.

**Comment by rubencalje** [comment]
I agree!

**Comment by rubencalje** [comment]
The notebooks are testes, as of commit https://github.com/pastas/pastas/commit/c3c9cb69bd02f02c5946399aa435a84a99eb8d1d to https://github.com/pastas/pastas/commit/6a9d462f138b42fd32e9e15fd77d5e2451393b19

Only notebook 10 is not tested yet, as there still is a problem with importing data from a parent path.

**Comment by raoulcollenteur** [comment]
Cool thanks ! 

Closing the issue :)
