### ISSUE TITLE
RechargeModel doesn't store stress in stress attribute

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#113]
All stress model objects store the stress as a list, except for the new RechargeModel object, which doesn't store them in the stress attribute:

ml = ps.Model(obs, name='test')
rm = ps.StressModel2([rain, evap], name='recharge', rfunc=ps.Gamma)
ml.add_stressmodel(rm)
ml.solve()
print(rm.stress)  # prints a list of the stress TimeSeries objects

ml = ps.Model(obs, name='Kingstown')
rm = ps.RechargeModel(rain, evap, name='recharge', rfunc=ps.Gamma)
ml.add_stressmodel(rm)
ml.solve()
print(rm.stress) # prints an empty list

**Comment by raoulcollenteur** [comment]
They are stored in rm.prec, rm.evap and rm.temp (for temperature. We could actually easily add them to the stress list attribute. Either way, you can use the get_stress method from either rm or ml here.

**Comment by raoulcollenteur** [comment]
Solved this with the last commit d6c342. The above example works now again. Internally it is just a reference.

**Comment by mbakker7** [comment]
Great.
Are the series used for calibration somewhere? Or is that not stored?
