### ISSUE TITLE
ml.plot doesn't recognize keyword figsize anymore

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#114]
The following don't work anymore on master or dev (they used to work 6 months ago):

ml.plot(figsize=(16, 4));

ml.plots.plot(figsize=(16, 4));

Both result in a `AttributeError: Unknown property figsize` error.

**Comment by raoulcollenteur** [comment]
This should indeed work! Solved this issue and standardised all other methods in the plots module as per commit #f840c23. Closing the issue.
