### ISSUE TITLE
Update version to 0.11.0 on Friday 2019-06-21

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#117]
Planning to update the master branch to v0.11.0 so please commit all changes that you want to be in this release before Friday 12:00 CET.

**Comment by mbakker7** [comment]
Can we add an option to turn INFO: BLA BLA BLA off?

**Comment by raoulcollenteur** [comment]
This was previously implemented in the Model class (log_level="ERROR") but is now available on the Pastas package level thanks to @rubencalje.

`ps.set_log_level("ERROR")`

Would be nice to include this in a few of the examples.

**Comment by rubencalje** [comment]
I did create an example, so this functionality is tested: example_logger.py

**Comment by raoulcollenteur** [comment]
Interestingly `ps.set_log_level("ERROR")` works for me on Jupiter Notebooks but not in my Python console. I'll put that on the list for the next release. I think the Jupyter notebooks are more important anyway for now.

Updating to 0.11.0!
