### ISSUE TITLE
RechargeModel does not support istress in the simulate method

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#120]
Therefore ml.plots.decomposition(split=True) does not work. It does for all other stressmodels.

**Comment by raoulcollenteur** [comment]
True. That is why I put an error message in the decomposition plot now when this method is called with the istress argument. Split is not and will not be supported in RechargeModel as it calculates the contribution from recharge and not precipitation and evaporation. As more complicated recharge models will be added the split argument would be rather difficult to implement I think. Also we would need to think about if it is even fundamentally possible to split the contribution from precipitation and evaporation when using a non-linear method for the recharge calculation. My intuition says it is not.

The only stressmodel that actually supports split is StressModel2. The other stress models silently suppress the argument as it will become an unused kwarg when the simulate method is called with the istress argument. Therefore, StressModelBase does not include this argument in the default input arguments either.

**Comment by raoulcollenteur** [comment]
Related to #119

**Comment by rubencalje** [comment]
The main drawback of the RechargeModel-class, compared to StressModel2, is that the contribution of precipitation and evaporation cannot be splitted. For a Linear recharge model (the default) this is possible however. Therefore I made commit 8a6da4cfb738322059f46ec1926476fd71b91777.
