### ISSUE TITLE
giving an unknown setting produces a confusing error

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#121]
When specifying an unknown setting when creating a stressmodel, for example 
settings='precip' (i.o. 'prec'), or settings='rain' produces a strange error:

TypeError: update_settings() argument after ** must be a mapping, not str

Pastas should check if the string exists and give a sensible error message (like what strings are allowed!).

**Comment by raoulcollenteur** [comment]
The error was logged and not raised. Fixed with my latest commit, closing the issue.

**Comment by mbakker7** [comment]
It is still very difficult to find the 'settings' in the documentation.
Where can I find this right now?
