### ISSUE TITLE
add_stressmodel doesn't take a list as input for multiple stress models

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#122]
I thought you can add multiple stress models in one command. It looks like this can be done with multiple arguments, but that is confusing as there are also arguments (keyword arguments) after that. Shouldn't the correct syntax be a list (or tuple or any iterable) of stressmodels?

**Comment by raoulcollenteur** [comment]
it now works like that, providing each stress models as an argument:

`ml.add_stressmodel(sm1, sm2)`

We can remove the **kwargs actually, as they  are not used.

Should we change the behaviour to?

`ml.add_stressmodel([sm1, sm2])`

**Comment by raoulcollenteur** [comment]
Sticking to the current syntax to add stress models:

`ml.add_stressmodel(sm1, sm2)`

Closing the issue

**Comment by mbakker7** [comment]
I think [sm1, sm2, ...] is a much better syntax. So let's discuss.

**Comment by rubencalje** [comment]
Can't we support both?

Besides this, I see now that the replace-argument is not used when adding multiple stress-models in one go.

**Comment by raoulcollenteur** [comment]
Let's not support both, it should be clear hat to do. I have no preference for either of them.

as list: 1
as args: 0

ps. yes we should fix the replace-argument.

**Comment by dbrakenhoff** [comment]
I'm for the as list approach!

as list: 2
as args: 0

**Comment by raoulcollenteur** [comment]
I will change this to the following behaviour for the next release:

`ml.add_stressmodel([sm1, sm2])`
