### ISSUE TITLE
Add pr.add_oseries() and pr.add_stress()

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#125]
We've (Onno and I) had feedback from users that it would be nice to have explicit methods to add to oseries and stresses to projects.

Shouldn't take a whole lot of code and I agree it would be nice to have.

Maybe we should also think about the delete methods, whether it is worthwile to ensure we have one for each of these as well?

**Comment by raoulcollenteur** [comment]
I think this would be a good idea. I think this is how it was one day but I changed it for some reason. Can you prepare a PR?

**Comment by raoulcollenteur** [comment]
Closing issue with commit https://github.com/pastas/pastas/commit/5e40d348b817d0bc399cf98c364339e987985c57
