### ISSUE TITLE
Lower limit of Beta in Edelman response function

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#132]
I tried to use the new Edelman response function and ran into some troubles optimising the model. As Beta decreases, particularly below a value of 1, the step response becomes very long. At beta=1 it is already more than 12000 days. 

```
import matplotlib.pyplot as plt
import pastas as ps
r = ps.rfunc.Edelman() 
plt.plot(r.step([1]))
```

EDIT: when beta is very small this actually causes trouble in the optimisation and potentially strange `fftconvolve` error messages.

Is it an idea to have a lower limit of 1 for the Beta parameter?

**Comment by mbakker7** [comment]
Problem with Edelman is that it takes VERY long (theoretically infinitely
long I think) to get to the steady state value. Hence the use of a Polder
function, I think, where the top boundary is semi-confined. Or we can try a
no-flow at an unknown distance (extra parameter).

**Comment by raoulcollenteur** [comment]
Closing with wontfix tag.
