### ISSUE TITLE
[DEVELOPMENT] add tests for freq != "D"

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#136]
I talked with @rubencalje and we think it would be a good idea to add some tests for frequencies other than daily to our test suite. Also the relationship between the obtained parameters when solving on different frequencies might be interesting to explore in a notebook.

(We discussed this because I was working on models with freq="14D" but I was not entirely sure this always worked as well as I'd hoped. I've now decided to solve on a daily basis and getting a sample every 14 days from my oseries.)

**Comment by dbrakenhoff** [comment]
Pushing to release after next. I'll be working on models with different frequencies soon, but not before next release.

**Comment by raoulcollenteur** [comment]
Perhaps also add some tests  and close this issue as well?

**Comment by dbrakenhoff** [comment]
Add notebook
