### ISSUE TITLE
visualize solver iterations

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#137]
I wrote a small class that creates an interactive figure that shows the progression of the fit, the RMSE and the parameter values, similar, I believe, to what Menyanthes shows as it's solving. Implementing it looks like this:

```python
# after creating a model 
track = TrackSolve(ml)
fig = track.initialize_figure()
ml.solve(callback=track.update_figure)
```
It does make your solve really slow, but you can see the progression of the solver which is kinda cool.

![image](https://user-images.githubusercontent.com/6552225/62611251-8347b300-b905-11e9-8f3c-6e81aa2ce80b.png)

Should I add this class to pastas somewhere? And if so, what would be a logical place, utils.py or plots.py?

**Comment by raoulcollenteur** [comment]
plots.py seems ok for now. also add the class to the __init__.py.

**Comment by dbrakenhoff** [comment]
Added by abf7289f8763a94a0cb5f18c48810722596ec736. 

Provides a warning when used that the feature is under development. 
Still some TODOs in the Notes for further improvement.

**Comment by raoulcollenteur** [comment]
I think we can close this issue?

**Comment by dbrakenhoff** [comment]
Yep
