### ISSUE TITLE
limit pmin from gamma_n to 1

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#151]
Should we set the lower limit of the parameter gamma_n to 1.0 ?

```
rfunc = ps.Gamma()
plt.plot(rfunc.block([1,1,10]))
```

As n < 1.0 I think the impulse response goes to infinity for t=0.

Thoughts?

**Comment by rubencalje** [comment]
Just looked at an old study I did, and in about half of the locations n was below 1.0. When a noisemodel is used, n tends to be higher.

An n lower than 1.0 makes the response higher in the first days of the response. I think we should allow this for the Gamma-function.

Changing the lower bounds of n to 1.0 would change the optimal values for most of these models, and reduce the fit of the model. Therefore I am against this change.

**Comment by raoulcollenteur** [comment]
Agreed. Closing issue.

**Comment by mbakker7** [comment]
To clarify: The impulse response goes to infinity for t=0, but the block response (which Pastas uses) is finite.
