### ISSUE TITLE
improve error message when solving empty oseries

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#153]
When calling `ml.solve()` with a tmin beyond the last measurement or a tmax before the first measurement, the error that is returned is pretty vague:
- with noisemodel: `ZeroDivisionError: float division by zero` because it attempts to divide by the length of the oseries between tmin and tmax
- without noisemodel: `ValueError: Internal work array size computation failed: -5` this happens somewhere in numpy/lapack.

This happens for example when you set one tmin and tmax for each model you want to solve in your project even though some oseries do not have data between tmin and tmax. Obviously the user should try to properly select timeseries beforehand, but I think it would be nice to provide better messages in case this hasn't gone according to plan.

**Comment by raoulcollenteur** [comment]
I agree. Can you do a PR with a proposal for a solution?

Davíd Brakenhoff <notifications@github.com> schrieb am Di., 1. Okt. 2019,
14:47:

**Comment by raoulcollenteur** [comment]
Thanks the PR! Approved!
