### ISSUE TITLE
Enhance the use of deprecated messages

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#154]
Right now, the user receives the message that some methods will be deprecated in version 0.13.0:

> WARNING: Deprecation warning: method will be deprecated in version 0.13.0.

What we mean by this is that the method will be removed in version 0.13.0. So really the method is deprecated right now, as the definition of deprecated according to google is:

> Deprecated means, generally, that something is acknowledged but discouraged. In IT, deprecation means that although something is available or allowed, it is not recommended

So I think we should change the meassage. Also, it would be helpful to the user if we name the method that is deprecated, and that we give him an alternative. So I think the message should be

> WARNING: add_series() is deprecated since version 0.12.0. Please use add_oseries() or add_stress() instead.

Finally, I think we should keep the deprecated methods for longer, so people have time to transfer their scripts to the new methods. I think a good period would be 1 year, so around 4 version-updates.

**Comment by rubencalje** [comment]
I see my example is not the best, as add_series is not deprecated anymore in the dev-branch (which I agree with).

**Comment by Hugovdberg** [comment]
This is an interesting blog post addressing exactly this issue: https://emptysqua.re/blog/api-evolution-the-right-way/, there are video recordings of it as well.

**Comment by raoulcollenteur** [comment]
Maybe we can add the "right" way to the docs for future reference. E.g., here: https://pastas.readthedocs.io/en/latest/developers/code_style.html
