### ISSUE TITLE
ml.plots.stacked_results() gives an error

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#157]
The error is:

> TypeError: simulate() got an unexpected keyword argument 'istress'

Maybe we should remove this method?

**Comment by rubencalje** [comment]
David is on holiday. I fixed stacked_results. I see the use case now.

Can you implement nstress and istress for the linear case in the Recharge class Raoul?

**Comment by raoulcollenteur** [comment]
Uhm, I can't reproduce this error. Which example does it happen?

**Comment by rubencalje** [comment]
It is fixed. I assigned you, because I think we should implement the nstress-attribute of the Recharge-class for linear models (and the istress-attribute in the simulate-method of the Recharge-class). In that way, we can split the contribution between precipitation and evaporation, in ml.plots.decomposition() and ml.plots.results(), like we can with StressModel2. This may be better in a separate issue though, so I will close this issue.
