### ISSUE TITLE
disable noise method if noise=False or give Error

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#162]
I found out the following is now possible but highly unwanted:

```
ml.solve(noise=False)
n = ml.noise()
```

where n is "some kind of" noise series, while the alpha parameter has not been estimated. 

I think we have to give either a warning, or, this is my preference, disable the noise method when ml.setting["noise"] = False or some other criteria (no optimal noise_alpha?).

Anyone against this? I will think about an implementation, suggestions welcome.

**Comment by mbakker7** [comment]
Howbout implement an Assert when doing ml.noise() if ml.solve(noise=False).

Just to be clear: ml.noise() is never needed anymore, is it? Isn't it
simply turned on by doing ml.solve(noise=True) or ml.solve(noise=False)?

**Comment by raoulcollenteur** [comment]
Fixed with commit #f123a5e 

ml.noise() Will now return None and an Error message if called when no noise model is used for calibration. Closing the issue.
