### ISSUE TITLE
stderr is 0.00% when parameter cannot be determined

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#166]
For some reason, stderr in a fit-report is 0.00 % when the parameter cannot be determined. I think we should replace this by inf % or NaN %.

**Comment by raoulcollenteur** [comment]
Just fixed this in the uncertainty-branch. Closing issue.

**Comment by rubencalje** [comment]
Great, also that the model fit is now available after loading a pas-file. Good job!
