### ISSUE TITLE
functie models.stats.ops geeft rmsi

### ISSUE THREAD

**Issue by tdmeij** [pastas/pastas#167]
De functie **models.stats.ops** geeft als resultaat een dictionary met statistische parameters van models.stats. Die dictionary bevat een key 'rmsi', maar er bestaat geen attribuut **models.stats.rmsi** (wel 'rmse' en 'rmsn').

Code om het probleem te reproduceren (pr is een pastas project):
        modelname = next(iter(pr.models))
        statslist = list(pr.models[modelname].stats.ops.keys())
        dfstat = pr.get_statistics(statslist)

Geeft als foutmelding:
AttributeError: 'Statistics' object has no attribute 'rmsi'

Ik gebruik Pastas 0.12.0

Het zou praktisch zijn als de functie def get_statistics(self, statistics, models=None, **kwargs) uit project.py ook een waarde 'all' zou accepteren. Dan selecteer ik achteraf wel de kolommen die op dat moment van belang zijn.

**Comment by raoulcollenteur** [comment]
Hi Thomas, thanks, fixed with the latest commit in the dev-branch!

I can see the use to accept the keyword "all". If you want you can make this change and do a Pull Request.
