### ISSUE TITLE
Add package version explicitly to example notebooks

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#175]
I would like to add a print statement of the packages used at the start of each notebook, similar to the notebook for the groundwater paper. This should make it easier to track changes in Pastas that result from changes between versions in third party packages.

**Comment by mbakker7** [comment]
I have nog problem with this, but wonder if it is necessary.
Are we running into problems without it?

**Comment by raoulcollenteur** [comment]
I just think it is an easy way to check on GitHub when the results of notebooks change. Also, if people can't reproduce the notebook results shown here on GitHub, it's impossible to check the packages that were used to obtain these results now.

**Comment by raoulcollenteur** [comment]
Done, closing issue.
