### ISSUE TITLE
deprecate keyword metadata in TimeSeries?

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#176]
The `metadata` argument will be deprecated in v0.14.0 and removed in v0.15.0 from pastas Models, TimeSeries and Stressmodels. The feature will continued to be supported in Pastas projects.

EDIT: this was a proposal and is not yet decided upon.

**Comment by mbakker7** [comment]
Will the attribute be deprecated entirely?
So how can we store, e.g., the x,y location of a series?

**Comment by raoulcollenteur** [comment]
read_dino, meny, knmi and waterbase are affected. These methods return TimeSeries, using the metadata . 

This is not a problem for Pastas Models, only for projects. Working on this now.

**Comment by raoulcollenteur** [comment]
> Will the attribute be deprecated entirely? So how can we store, e.g., the x,y location of a series?

This is something the user needs to keep track off separately then , expect when using Pastas projects.

**Comment by mbakker7** [comment]
Then I don't see any reason to remove the metadata.

Storing the coordinates seems like a good thing to do and something we may
use in the future, so I don't see a good reason to remove the metadata.

**Comment by dbrakenhoff** [comment]
Did we agree to not deprecate this? I think it's nice to have that information at your disposal in Models, even if pastas doesn't really do anything with it.

**Comment by raoulcollenteur** [comment]
No. Let's keep it in. Changes were complicated and leaving it in is not ;-)
