### ISSUE TITLE
least_squares problem for parameters that are much smaller than 1

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#177]
The default method for parameter estimation in Pastas, `scipy.optimize.least_squares` has a bug when the absolute value of a parameter is much smaller than 1. See here: https://github.com/scipy/scipy/issues/11258
We should do something about that, at least until it is resolved.

**Comment by raoulcollenteur** [comment]
We need to find a working example to test this somewhere.. anyone?

**Comment by dbrakenhoff** [comment]
Check if implementation is correct in Pastas for small parameters

**Comment by mbakker7** [comment]
Scipy > 1.8 doesn't install yet with conda. Gotta wait for that. Bumped the milestone.

**Comment by raoulcollenteur** [comment]
I checked and scipy 1.8 is now available from Conda and Pypi. Bumped Scipy version in last commit so we can close this issue. :)

**Comment by dbrakenhoff** [comment]
I think it's fine closing this, but to double check:

@mbakker7 you had a ttim script where you discovered this issue, can you confirm it is now no longer a problem?

**Comment by raoulcollenteur** [comment]
@mbakker7 and @dbrakenhoff can you please check if we can close this issue and merge PR #496 ?

**Comment by mbakker7** [comment]
This is fixed in scipy 1.8, so as long as we require that, this can be closed.
