### ISSUE TITLE
Improve docs for Pastas v1.0

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#180]
This is just an issue to keep track of some other changes that could be made to the docs:

- [x] Create an example notebook gallery https://sphinx-nbexamples.readthedocs.io/en/latest/examples/index.html
- [x] Improve "benchmarks" section
- [x] Better example Notebooks
    - [X] River levels
    - [x] StepModel
    - [x] LinearTrend
    - [x] Model verification / Diagnostics
    - [x] Solve Strategies
    - [x] Uncertainty Quantification
- [x] Add "recommended reading" section in user guide / or references list using sphinx
- [x] Automate adding Notebooks (seems to fail now) on RTD
- [ ] Give the notebooks from Groundwater paper a place on the Docs.
- [x] Add "Publications" section for peer-reviewed accepted articles using Pastas
- [ ] Make list of terminology used in Pastas
- [x] Name examples
- [ ] Check if sphinx-gallery >0.11. can be used (https://github.com/spatialaudio/nbsphinx/issues/655) or drop sphinx-gallery if this PR gets through for sphinxnb (https://github.com/spatialaudio/nbsphinx/pull/706/files)
- [ ] Start using sphinx >6.0 if pydata-sphinx-theme 0.13 is released (https://github.com/pydata/pydata-sphinx-theme)
- [ ] add example of setting solver settings

**Comment by raoulcollenteur** [comment]
Let's add "better examples" to the list. Going through them made me realise they are not always that good, and we lack proper examples for most stress models. More specifically we need:

- new groundwater level data that is more clearly impacted by a rivers
- data showing a clear step trend
- data showing a linear trend (would be nice to test al well..)
- groundwater data where a gamma function is needed (no its often exponential)
- .. more?

Someone has these data that we can add?

**Comment by dbrakenhoff** [comment]
I can find you a timeseries that is heavily influenced by a river.
For step and linear trend I would just create fictitious examples by adding manually.

**Comment by dbrakenhoff** [comment]
[oseries_stresses_w_riv.zip](https://github.com/pastas/pastas/files/4360924/oseries_stresses_w_riv.zip)

This is a zipfile with:
- oseries 
- prec
- evap
- river (interpolated between stations to point nearest on river to observation point)

This oseries should have significant influence from the river.

**Comment by raoulcollenteur** [comment]
Cool, I'll make a new example with river levels with that! Thanks!

**Comment by martinvonk** [comment]
To add to the todo list:

- [ ] Readthedocs update Release Notes section
- [ ] Readthedocs update Development section

**Comment by raoulcollenteur** [comment]
Add a Project to track this issue and maintain a to-do list: https://github.com/orgs/pastas/projects/2

Add all todo's there!
