### ISSUE TITLE
bump dependency versions for pastas v0.14

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#183]
I think it is time to bump some of the dependency versions:

- python 3.5 => 3.6
- pandas 0.23 => 0.25 at least, preferably 1.0 (#92)
- scipy, no idea ???

All major packages (Numpy, Scipy, Matplotlib, Pandas) have dropped support for Python 3.5 by now and it's causing more and more problems on Travis. We could add 3.8 support.

Anyone has a problem with this? suggestions?

**Comment by dbrakenhoff** [comment]
- I agree with dropping support for 3.5 and adding 3.8.
- Pandas 0.25 seems reasonable but requiring 1.0 might be a bit early?
- I have no opinion on scipy... would be nice if they fixed that least_squares thing.

**Comment by rubencalje** [comment]
I agree with dropping 3.5, no preference for the other packages.

**Comment by mbakker7** [comment]
Is anybody running 3.8 at the moment?
Any new issues with 3.8?

**Comment by raoulcollenteur** [comment]
Bumped pandas to 0.25. That actually makes sense, as this version should equal 1.0, but give warnings when methods are deprecated :) 

Just dropped 3.5 from Travis and added 3.8. Let's see what happens. Python just made 3.9 their master-branch and only accepts new features there, so 3.8 should be stable by now.
