### ISSUE TITLE
Make name of parameter argument consistent throughout Pastas

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#185]
I think we can slowly move towards a stable 1.0 version of Pastas (#92), so I have been checking consistency throughout the code a little more. I found an interesting inconsistency in Pastas today in the naming of the parameters argument. 

- model.py: `parameters`
- noisemodels.py: `parameters`
- solvers.py: `parameters`
- stressmodels.py: `p`
- rfunc.py: `p`
- recharge_func.py: `p`

I think this should be made consistent throughout Pastas. I think `parameters` is more explicit and should should be changed to this. The change would be primarily internal, as the classes/method in the three affected files should generally not be called directly. However, for future use when calling these method directly at least it will be clear what the parameter-argument is named.

**Comment by rubencalje** [comment]
Doesn't parameters stand for the parameters-dataframe, and p for the numpy array with current parameters? I think this is a good distinction.

**Comment by mbakker7** [comment]
I agree with Ruben.
This is at least the intention.

**Comment by raoulcollenteur** [comment]
This would be nice, but it is not the case (now). Virtually all `parameter` arguments require array-like input, except for those in solver.py which take a DataFrame. Can't find any other methods that take a parameter-DataFrame input.

**Comment by rubencalje** [comment]
Ah, yes, I see what you mean, for example the simulate, residuals, noise or get_contribution methods  of Model. I did not know you could supply parameters to these methods as well, and I think not a lot of people have done so (right?).

You are right that the name 'parameters' is more explicit, and sounds better for an input-argument. However, to distinguish it from the parameters-dataframe, to keep the code compact and because normally it is an internal argument, I am in favor of renaming all array-like input-'parameters' to 'p'.

**Comment by raoulcollenteur** [comment]
I don't think many users call functions and provide `p` or `parameters` explicitly. And if so, they probably know very well what they are doing. Trying to improve some parts of the code today I actually became more convinced this needs to be changed soon: it is hard to reuse a function that call methods with either `p` or `parameters` so I had to write the same code twice.

I have a small preference for `parameters` as this is the argument name that most of the now-public methods have and I like the explicit name. But as we think there are not many people using them that is maybe not the best argument. `p` would be fine as well for me. Let's vote.

- `parameter`: 1
- `p`: 1

**Comment by raoulcollenteur** [comment]
I had a look at this, it really doesn't matter what we choose. I say we change all "parameter" arguments to "p" where it is a array or a list, and parameter if it's a DataFrame (virtually never). I we agree I'll make the change today before the next version.

**Comment by raoulcollenteur** [comment]
Started refactoring, commit coming up this morning.
