### ISSUE TITLE
Merge example notebook 4 and 11

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#187]
Right now there are two notebooks that rely on data from the Menyathes-file '../data/MenyanthesTest.men'. In notebook 4 we read and visualize the data and make a model. In notebook 11 we apply a WellModel to this data. I propose to combine these two notebooks, by adding relevant code from notebook 4 to notebook 11, and removing notebook 4.

Anyone against this change?

**Comment by mbakker7** [comment]
+1

**Comment by raoulcollenteur** [comment]
+1

**Comment by raoulcollenteur** [comment]
Hi Ruben,

Do you think you have time to this this somewhere over the next week? Would be nice to have this one finished before the next release

Cheers, Raoul

**Comment by rubencalje** [comment]
I have just committed the new notebook. I also compare the WellModel with a model of individual StressModels now, and deleted notebook 4.

**Comment by raoulcollenteur** [comment]
Nice work! Closing the Issue :)
