### ISSUE TITLE
rewrite ml.set_parameter and make method public

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#190]
I will rewrite the `ml.set_parameter` method and make it public. New usage will be:

`ml.set_parameter(name=name, vary=True, initial=0.0, pmin=None, pmax=None)`

Because I want to set and change these properties in one-line and not 4. E.g.:

```
ml.set_initial(name="constant_d", 10)
ml.set_vary(name="constant_d", True)
ml.set_pmin(name="constant_d", -10)
ml.set_pmax(name="constant_d", 20)
```

Will be:

`ml.set_parameter(name="constant_d", initial=10, vary=True, pmin=-10, pmax=20)
`

The old method will continue to work, but we can also deprecate them. They will internally continue to call set_parameter anyway.

**Comment by raoulcollenteur** [comment]
Done. I think this new method makes much more sense.

The option `move_bounds` of the set_initial is also supported properly now, solving a Bug when this option was set to True but the parameter was not present. This would not have given the correct Error message.

 Shall we deprecate the old methods ? At least for a version 1.0 I would say so we can start throwing DeprecationWarnings now.

**Comment by mbakker7** [comment]
I like the new method.
Can you make the new method such that all defaults of the keywords are
None? None then means: use the current value.
Then it is a full replacement of all the other methods.

**Comment by raoulcollenteur** [comment]
This is exactly how it is implemented right now 😄 !

**Comment by raoulcollenteur** [comment]
Anyone against deprecating the old set_methods? They will then continue to work until 1.0 (whenever that is).
