### ISSUE TITLE
Notebook 13_non_linear_recharge_models

### ISSUE THREAD

**Issue by tdmeij** [pastas/pastas#194]
The notebook ''13_non_linear_recharge_models.ipynb'' shows how to use three types of non-linear models implemented in Pastas: Linear, FlexModel, and Berendrecht. The notebook works fine and shows basic usage very clearly. Just one remark: A very brief description in the introduction of the general model concepts and differences in the three available non-linear models would help users in selecting the right model for the job at hand. Maybe references to reports describing practical application of these models for further study?

**Comment by raoulcollenteur** [comment]
Hi! Thanks for the interest in the non-linear models! A better description will be added in a future version of Pastas. These models have just been added in the last version of Pastas two weeks ago, so there are no practical applications of these models yet. I am currently working on a report that will introduce these models and will add a reference to that once this is public :)

**Comment by raoulcollenteur** [comment]
Just added the reports describing the models to the notebook and Python code. Closing this issue.
