### ISSUE TITLE
Questions on StackOverflow

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#195]
The readme points users to ask questions about Pastas on StackOverflow. However, when you try to post a question with the tag pastas, it tells you that tag does not currently exist and you need at least 1500 reputation to create it.

I've added an example Q&A using the tags `python`, `timeseries` and `forecasting` based on an email I received: https://stackoverflow.com/questions/61387335/making-a-prediction-with-a-pastas-timeseries-model

It would be nice to have the pastas tag though! Or help users identify their questions somehow so that we can find and answer them.

**Comment by raoulcollenteur** [comment]
GitHub will soon release GH Discussions, a separate section next to Issues that could serve well for this purpose. Let's wait until that is rolled out and remove stackoverflow?

**Comment by mbakker7** [comment]
Sounds like a plan

**Comment by raoulcollenteur** [comment]
I requested to join the Beta for Github Discussion and it just got approved. I think this will work very well to separate discussion topics from the issues and keep everything in one place here on Github. 👍
