### ISSUE TITLE
Passing array of parameters to residuals function

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#20]
I want to pass an array of parameters to the residuals function. Right now it checks first if the method is 'lmfit', then whether the parameters are an array. I think that should be the other way around. Also, in the checking whether parameters is an array, it now also check whether it is None. I think that is impossible, as it won't get beyond the if statement.

**Comment by raoulcollenteur** [comment]
I think this issue was fixed when we introduced the solver class, so the issue is closed.
