### ISSUE TITLE
tmax of response function

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#201]
In a previous version of Pastas, the rfunc of a StressModel used to have a tmax. This attribute is removed and there is now a get_tmax function, but that function requires the parameters as input. That is inconvenient. Maybe allow parameters to be None and then return the tmax for the current optimal parameters? Is tmax really not stored anywhere?

**Comment by raoulcollenteur** [comment]
tmax is not stored somewhere anymore and is calculated using the parameters and cutoff. I'll add a convenience method to the Model class to obtain the tmax:

`ml.get_tmax(sm="recharge", cutoff=0.999)`

**Comment by raoulcollenteur** [comment]
Fixes. Users may now use:

`ml.get_response_tmax("recharge", cutoff=0.99)`

Also added to the documentation. Closing Issue.
