### ISSUE TITLE
autocorrelation function over estimates for small time lags

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#203]
The built-in autocorrelation function that can deal with irregular time steps tends to overestimate the autocorrelation for smaller time lags. I think this is because the bin size is chosen based on the mean time steps, which is too big for smaller time lags. I think this should be easy to fix by comparing the lag and the bin_width. Quick option for now:

`ml.plots.diagnostics(acf_options={"bin_width": 0.5});`

**Comment by EitvanderMeulen** [comment]
Normally the autocorrelation increases for smaller time lags. So with the mean of time lags an underestimation of the autocorelation for the smaller time lags can be expected.

**Comment by raoulcollenteur** [comment]
Hi Eit,
Yes that is true if one would take the mean acf of multiple time lags, but that is not what I proposed above. The problem here is in the size of the bin_width that is used to calculate the acf that is too big for small time lags. So right now Pastas actually overestimates the ACF for small time lags.

**Comment by raoulcollenteur** [comment]
Changed the default bin_width to 0.5 days as per the last commit and we now compute the autocorrelation for all time lags up to 365 days. Nan-values are removed after. This way you get a better view of the autocorrelation with the default settings.
