### ISSUE TITLE
reading Dinoloket Peilschalen (level gauges)

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#204]
Pastas can only read groundwater levels from the Dutch data portal Dinoloket. Support for reading level gauges (peilschalen) is useful for timeseries analysis in the Netherlands. The CSV format for level gauges is slightly off, therefore a variation of the ps.read.DinoGrondwaterstand class is needed.

**Comment by mbakker7** [comment]
I didn't know DinoLoket had surface water levels. That would be nice.
Can you submit a PR including an example Notebook where you use both groundwater levels and surface water levels?

**Comment by rubencalje** [comment]
That would be nice. A PR would be welcome. If you do not have a scripts for reading Dinoloket level gauges yet, we do have something, but it will take some work to make it ready for Pastas. I can commit the raw script though.

**Comment by tomvansteijn** [comment]
I added DinoPeilschaal in my pastas fork [here](https://github.com/tomvansteijn/pastas/blob/dev/pastas/read/dinoloket.py). However it is bit of an overhaul as I tried to make use of some generalisations for reading this type of files. Needs more testing as well.

**Comment by tomvansteijn** [comment]
Ofcourse it is also possible to refactor and do a PR for the complementary code only, leaving the groundwater level reader class untouched.

**Comment by mbakker7** [comment]
I think that would be the best option: a PR for the complimentary code only
and leaving the groundwater level reader class untouched.

**Comment by tomvansteijn** [comment]
Second try, a new DinoPeilschaal class for reading level gauges. A minimum of changes compared to the groundwater level reader class.

https://github.com/tomvansteijn/pastas/blob/dev/pastas/read/dinoloket.py

Example notebook to be added.
