### ISSUE TITLE
Improve response function in docs and examples: Merge Notebooks 3 and 9

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#205]
Both Notebooks show the response function, would be nice to merge and extend this and have one notebook about the response function.

Anyone against this?

**Comment by rubencalje** [comment]
Would be great, although it would take some time to do it right. You could also rename notebook 9 to 'Four Parameter response function'. And maybe also add the Edelman-response function to notebook 3?

**Comment by raoulcollenteur** [comment]
The following response functions will soon be stable and should well-documented:

- [ ] FourParam
- [ ] Gamma
- [ ] Hantush
- [ ] Exponential
- [ ] Polder
- [ ] DoubleExponential
- [ ] HantushWellModel
- [ ] Edelman, not sure about this one?

This list could be added to rfunc.py to ensure documentation. I think the docstring of each response function should have the impulse and/or step response function in the docstring.

**Comment by raoulcollenteur** [comment]
Merged Notebook 3, 9, and 16 (which was not in the docs) to a new notebook 3. Probably this Notebook could be extended in the future with more information (maybe the formulas for the step responses) but should be ok for now.

All docstrings now include the formula for the impulse response function (except Edelman).

Closing Issue.
