### ISSUE TITLE
separate calculation of weights and noise in the noise models

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#206]
Currently the `simulate` methods of the noisemodels return the weighted noise. This makes it difficult to compute the unweighted noise values. @mbakker7 and I propose to untangle this and have `simulate` return the unweighted noise.

This change will affect:
- solver.misfit method
- ml.noise method
- all methods that depend op ml.noise

To reduce the impact (for now) I propose to add a keyword `'weighted'` to ml.noise, with a default value True. This way all the changes are only internal, but the code allows testing of the impact of the weights better.

**Comment by mbakker7** [comment]
I propose to make the keyword `weights` in `ml.noise`. 
Please right away add a deprecation warning that in an upcoming release the default value will be `weigths=False`.

**Comment by raoulcollenteur** [comment]
Should we also add a ml.weights method? Otherwise we still need to call 

`ml.noisemodel.weights(alpha, odelt)`

This would require the user to figure out the alpha and odelt...

**Comment by mbakker7** [comment]
Can you give an example when the user would use the ml.weights function?
My preference is to keep it as ml.noisemodel.weights. I think in the
(near?) future, we want to be able to add user-specified weights to
measurements, so it may be wise to keep associating these weights with the
noisemodel.

**Comment by raoulcollenteur** [comment]
An new method was added to address this Issue in commit #0d8ea2e:

`ml.noise_weights()`

This method calls the weights method from the noisemodel.

Should we close this issue?

**Comment by mbakker7** [comment]
I think the default  should be `weights=False` in `ml.noise`.
The next release will include a lot of enhancements (leading to better but different results), so there is no reason to postpone implementing this as the default.

**Comment by OnnoEbbens** [comment]
Now when I solve a model I get the warning:
`WARNING: The default argument for weights will be changed to weights=False in a future version of Pastas.`

I think I don't have to do anything with this so I don't think I should see this warning?

**Comment by mbakker7** [comment]
It is a deprecation warning, but an annoying one. And maybe too obscure for
most users.
You don't need to do anything. My suggestion is to remove the warning and
set the weights to False by default.

**Comment by raoulcollenteur** [comment]
After `ml.del_noisemodel()` running `ml.solve()` will now error. this should be fixed I think.

**Comment by EitvanderMeulen** [comment]
If you want to weight noise/innovations isn't it better to introduce weights in the optimization criterion of noise/innovations for an optimal calibration of the parameters of your Pastas model (included the parameters of the noise model)? You can introduce different criteria and with a proper optimization method the model will always be optimal for a chosen criterion.

**Comment by raoulcollenteur** [comment]
@EitvanderMeulen not sure if i understand this well but I think what you suggest is how it will now work. weights are applied in the solver and not directly applied to the noise anymore.

**Comment by raoulcollenteur** [comment]
I think after all the changes we can actually remove the weights argument from ml.noise() again, including the warning. We can add to the release notes that ml.noise() returns the unweighted noise and not the weighted noise anymore?

**Comment by mbakker7** [comment]
Agree

**Comment by raoulcollenteur** [comment]
Done as per the last commit. I also solved the issue with solving after running ml.del_noisemodel(). I added these changes to the release_notes file but I'll commit that later. Closing Issue.
