### ISSUE TITLE
`ValueError: array of sample points is empty`

### ISSUE THREAD

**Issue by RDWimmers** [pastas/pastas#207]
When downloading KNMI data the timestamp of the data is YYYYMMDDHHMMSS, with HHMMSS as 01:00:00.
The DINO timestamp has HHMMSS as 00:00:00.

When trying to solve the model `ml.solve()` the following error will accrue:

`ValueError: array of sample points is empty`

This error is given in `np.interp()` and relate to the different timestamp. There is no overlapping timestamp between DINO data and KNMI data. So there are no values to interpolate. See attachment.

By removing the HHMMSS the model does compute. `evap.index = pd.to_datetime(evap.index).date`
Maybe it is possible to check the data? Or find the closest value based on the `sim.timestamp`?

Thanks, and keep up the good work.

[dev.zip](https://github.com/pastas/pastas/files/4868808/dev.zip)

I guess this error is somehow similar in the mechanics as issue #55. However, this accusers for every model. Not only the `stressmodel2`.

**Comment by raoulcollenteur** [comment]
Hi RDWimmers,

Thanks for the Bug report. I have quickly looked into it and it's appears to be a bit more complicated. The problem does not occur in `ml.residuals()` but already in `ml.simulate()`. ml.get_stress("recharge") still gives a result.

This is because the sim_index returned by ml.get_sim_index() does not take the offset of 1 hour into account. I'll keep this issue open, but it might take some time before it is addressed. The solution you proposed above is the fix  for now :-)

Cheers,
Raoul

**Comment by raoulcollenteur** [comment]
Short script to test for future reference:

```
import pastas as ps
from pastas.read.knmi import KnmiStation
import pandas as pd


head = pd.read_csv("data/head_nb1.csv", index_col=0, parse_dates=True,
                  squeeze=True)

# fetch data from KNMI station
knmi = KnmiStation.download(stns=260, start="1985", end="2008")
evap = knmi.data["EV24"]
rain = knmi.data["RH"]

ml = ps.Model(head, name="Model", constant=False)
sm = ps.RechargeModel(rain, evap, rfunc=ps.Exponential, name="recharge")
ml.add_stressmodel(sm)

ml.solve(tmin="1982")
```

**Comment by rubencalje** [comment]
The time_offset needs work indeed. You can set the time_offset manually, just before ml.solve(), by

`ml.settings['time_offset'] = pd.to_timedelta(1,'H')`

or let the model set it, by:

`ml._set_time_offset()`

These are all undocumented and unreliable (they can change in future Pastas-releases), so it is best to just remove the hours (as is done in the read_knmi-method).

Problems will also arise when there are different time_offsets in your input-series.

**Comment by raoulcollenteur** [comment]
New script for future reference. Model is working now after PR #237, closing this Issue.

```
import pastas as ps
from pastas.read.knmi import KnmiStation

import pandas as pd

head = pd.read_csv("data/head_nb1.csv", index_col=0, parse_dates=True,
                   squeeze=True)
 
# fetch data from KNMI station
knmi = KnmiStation.download(stns=260, start="1985", end="2008")
evap = knmi.data["EV24"]
rain = knmi.data["RH"]
ml = ps.Model(head, name="Model", constant=True)
sm = ps.RechargeModel(rain, evap, rfunc=ps.Exponential, name="recharge")
ml.add_stressmodel(sm)
ml.solve(tmin="1982", tmax="2007")
```
