### ISSUE TITLE
changing parameters of Hantush and Polder functions

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#210]
All response functions can be written in the same form:

h(t) = A * t^(n-1) * exp(-t/a -b/t)

The Hantush and Polder functions have different parameters that can be re-grouped to form this same shape. The documentation will clearly state how these parameters are related to physical parameters in the two functions. Right now, the Polder function is inconsistent with the Hantush function anyway, as Hantush has the parameter cS while Polder has the parameter sqrt(1/(cS)). In both functions, it will be replaced by a=cS.

An additional benefit is that all parameters will have the same name and meaning. Any thoughts?

**Comment by raoulcollenteur** [comment]
Yes sounds good, as long as we clearly document the changes and meaning of the parameters. I think we also stated something about Hantush in the Pastas article so we should note somewhere that the implementation is slightly different then.

Sidenote: Does it make sense to make the initial parameter values similar for all ? Or maybe the opposite actually, maybe for Hantush we can be "a" larger, as pumping gives generally a slower response. I have some examples where the initial value for "a" matters for pumping.

**Comment by mbakker7** [comment]
Synchronizing all parameters will likely make it easier to set good initial
values.

**Comment by rubencalje** [comment]
I did not know the Polder function could be written in that form. Would we then also change the way we calculate the step-response (no erfc for example), or do we just change the parameters?

I think it is good to standardise the parameters. We do need to clearly announce the changes in the changelog, as older models will give different results without solving again.

**Comment by raoulcollenteur** [comment]
also related to #156

**Comment by mbakker7** [comment]
Fixed with https://github.com/pastas/pastas/commit/607820ad7d9addb313cb771d602a48fb97bb9c76
