### ISSUE TITLE
incorrect doc string for Polder function

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#211]
The Polder function now states that it has only 2 parameters, while it has three parameters. Only when A=1 is fixed, the function is the Polder function and the other two parameters represent the combination of aquifer parameters.

**Comment by raoulcollenteur** [comment]
Solve together with #210

**Comment by mbakker7** [comment]
Fixed with https://github.com/pastas/pastas/commit/607820ad7d9addb313cb771d602a48fb97bb9c76
