### ISSUE TITLE
Make it possible to change the response function

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#215]
In the future I would like it to be possible to change the response function of an existing stressmodel. Something like this:

`ml.change_response_function("recharge", ps.Gamma)`

and/or directly on the stressmodel:

`sm.change_response_function(ps.Gamma)`

Both need to be implemented, starting with the latter. Internally the method should update the parameter dataframe and nparam attribute in the stressmodel, and the parameter dataframe in the Model class.

- [ ] implement sm.change_response_function
- [ ] implement ml.change_response_function

**Comment by dbrakenhoff** [comment]
Closed. Won't be implemented.
