### ISSUE TITLE
check for solver in `ml.solve`

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#219]
The `ml.solve` method takes an optional input argument `solver`. It is checked whether `solver` is a valid object with the following code

```
if solver is None:
        if self.fit is None:
            self.fit = LeastSquares(ml=self)
        elif not issubclass(solver, self.fit.__class__):
            self.fit = solver(ml=self)
```

I don't understand the `elif not issubclass(solver, self.fit.__class__)`. I think this means that if a current solver is defined, it can not be overwritten. Why not? Besides, should it not be checked that `solver` is indeed a subclass of `BaseSolver`?

**Comment by mbakker7** [comment]
In addition, I don't think any of the solvers use the `**kwargs` in the initialization method. Those should probably be removed and only remain in the `solve` method inside the class.

**Comment by raoulcollenteur** [comment]
- The elif prevents the solver from being initialised when the same solver is already used in a previous solve. Why would we want to create a new instance of the solver object every time?

- Checking if it is a subclass of the Basesolver might be a good idea, for all objects actually (rfunc, stressmodel etc.)

- **kwargs are only used in the solve method of the Solver class already? And then passed on the the actual minimisation method. Or do you mean the **kwargs of the __init__ ? Those could be removed I think..

**Comment by mbakker7** [comment]
- So it  only checks whether the solver is already defined. Wat if the solver is added with different arguments? I think it should simply be replaced if user explicitly adds it. What I thought this check was for, is whether the solver was indeed a solver object.

- Yeah, we could, but I am not sure that is needed here. Besides, users don't have to use the BaseSolver class if they don't want to, so why restrict them?

- I mean in the `init`. It is not used there and can be removed.

**Comment by raoulcollenteur** [comment]
- Yes, if the solver is added with different arguments this is not possible. However, that would also require supplying an instance and not a class. I would be in favour of starting to supply instances. Would fit the next release as well. 
- Agree, lets not check this.
- Let's try this, I'll make a commit removing the **kwargs.

**Comment by raoulcollenteur** [comment]
Removing **kwargs causes issues when storing a creating models from pas-files (try ml.copy()), as obj_func may be provided but is not an keyword argument in all solvers. Not removing ** kwargs from the solver for the next version.

**Comment by mbakker7** [comment]
This prevents creating a new solver object every solve. **kwargs doesn't hurt. Issue closed.
