### ISSUE TITLE
[BUG] example_900.py errors

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#231]
**Describe the bug**
 example_900.py errors on Travis, but not on my local computer. Should figure out what happens there.

**Comment by raoulcollenteur** [comment]
example_900.py errors after updating to Pandas 1.1.x. No idea why. Anyone wants to fix this?

**Comment by rubencalje** [comment]
It has to do with the _sample_weighted , which does not handle the time-offset correctly. I can fix this, but my fix will probably break other examples (without a time-offset, but with more irregular data). It will take some time to really fix this issue. For now, I will fix the example, by adding the freq_original to the evaporation-timeseries.

**Comment by rubencalje** [comment]
Why this only happens after updating to Pandas 1.1.x I have no idea.

**Comment by raoulcollenteur** [comment]
Fixed as per PR #237
