### ISSUE TITLE
[BUG] Metrics error when observations and simulation have different time offsets 

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#232]
**Describe the bug**
Metrics error when observations and simulation have different time offsets. some metrics used to use the ml.residuals(), but now subtract the ml.simulate() from ml.observations(). ml.residuals() has internally some interpolation. 

**To Reproduce**
https://pastas.readthedocs.io/en/latest/examples/011_WellModel.ipynb.html

**Expected behavior**
Good question. 

Related to other issues with time off sets. This really is a bit of a mess now, with users possibly unaware of interpolation to compute the residuals when the time stamps from the observations and simulation differ.

**Comment by raoulcollenteur** [comment]
After some work / improvements on the metrics I found that the problem is in more examples. There are a few examples where the time indices of the the simulation and observation don't match. ml.residuals() (silently) interpolates, but the methods in metrics.py do not do this. Since we now mostly use `sim` and `obs` for all metrics this issue shows up. For now I added a warning and return a None. A more sustainable solution would be to add "interpolation" option to the metrics methods in metric.py. 

Not sure how I feel about this "silent" interpolation that apparently happens more often. I think very few users are aware that this might happen when the indices don't match right now.

**Comment by rubencalje** [comment]
Every time the user solves a model where interpolation of the simulation to the observation times happens, the user gets the following information:
`INFO: There are observations between the simulation timesteps. Linear interpolation between simulated values is used.`

I think this is what you want. When a model simulates the head at midnight and the head is measured at 12:00 in the afternoon, I think you want to compare the measured head to the average of the simulated head at the beginning and end of the day. So we use linear interpolation. See also issue number #56 for more details. I can imagine this causes problems with the metrics though.

**Comment by rubencalje** [comment]
Shouldn't we add a residuals parameter (res) to all metric-methods, just like mae(), rmse() and sse(), and let a Pastas Model use this ml.residuals() as input for this parameter?

In this way, we make sure the residuals of the model and the metrics are the same again.

**Comment by raoulcollenteur** [comment]
Yes that is a good idea for some of the methods! This should fix the problem for the EVP, but not for the correlation (Pearson r). I'll have a look at this today.

**Comment by raoulcollenteur** [comment]
Fixed as per #f5cc04a
