### ISSUE TITLE
groundwater paper examples are broken

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#234]
I just checked the groundwater paper examples and these won't work with the new version anymore. The code is relatively easy to fix, but figuring out what to do with the gain for the Hantush will take some more work, as well_A parameter is not the gain anymore. 

- [x] Fix code in Example1
- [x] Fix code in Example2

**Comment by dbrakenhoff** [comment]
The Hantush rfunc has a `gain()` method. Is that what you need?

**Comment by raoulcollenteur** [comment]
No that won't help unfortunately, because I need to know the parameters such that the gain is -100 for Hantush. This used to be well_A but not anymore.. Maybe it would be nice to scale Hantush (and Polder) again such that the parameter A is the gain again?

**Comment by mbakker7** [comment]
Doesn't every response function have a 'gain' method?

**Comment by raoulcollenteur** [comment]
Is it an idea to scale the Polder and Hantush function differently, such that A is the gain?

https://pastas.readthedocs.io/en/dev/examples/003_response_functions.ipynb.html

**Comment by dbrakenhoff** [comment]
Still working on this issue, I think the rescaling is possible for Hantush. I think I've managed to make parameter `A` the gain again, but I'm still getting a difference between classic Hantush and Pastas Hantush in the response function notebook which I have to figure out. 

Also this rescaling is not possible for `HantushWellModel`, but you do want to be able to determine the gain (which can be done with the `rfunc.gain()` method) and the uncertainty of the gain. The uncertainty of the gain is a [combination of the uncertainty](https://en.wikipedia.org/wiki/Propagation_of_uncertainty#Example) for parameters `A`and `b`, which then needs to be calculated according to the formula in the link (I think). It would be nice to have method to help users do that.

**Comment by dbrakenhoff** [comment]
@mbakker7, in 227a6a3dcaa654321d6d83e2ba120bea11c0b0dd, the scaling of the Hantush response function was deliberately changed so that the step function goes to `k0(r / lambda)`. There was probably a good reason for this?

FYI, the relationship between the current parameter `A` and the gain is:
`A = gain / k0 (sqrt(4 * b))`

So it's fairly simple to set the Hantush parameters such that the step function reaches 100.

**Comment by dbrakenhoff** [comment]
Another issue I just ran into. The results of the notebook about adding multiple wells (and the WellModel) are different compared to the previous release.
 
See the notebook in the documentation from the [last release](https://pastas.readthedocs.io/en/latest/examples/011_WellModel.ipynb.html#Compare-individual-StressModels-and-WellModel) and compare it to the [current dev version](https://pastas.readthedocs.io/en/dev/examples/010_multiple_wells.ipynb.html#Compare-individual-StressModels-and-WellModel).

I think parameter estimation might be a reason to scale Hantush differently. This is the results table for the estimate of the gain from the multiple wells notebook, run with the pastas master branch. Hantush_scaled is the current implementation of hantush, hantush_gain is the implementation where A = gain.

![image](https://user-images.githubusercontent.com/6552225/98539742-21ef5c00-228d-11eb-9607-f6ac3e922fb5.png)

I'm getting this difference only on the master branch at the moment, on the current dev branch, the results from both Hantush implementations are the same and equal to the Hantush_gain results in the table. There is something in the current dev branch affecting the results... I'll have to look into that, and then figure out the Hantush implementations...

Here is my test notebook:
[test_hantush.zip](https://github.com/pastas/pastas/files/5510338/test_hantush.zip)

**Comment by raoulcollenteur** [comment]
Yes good point! Looking at the plot_decomposition above it is a problem in stack_plot. ml.get_contribution("Wells") shows that there are nan-values. This happens because the timestamps for both contributions are the same. Another point is that "tilmestep_weighted_resample" is triggered on the oseries, this became visible after I improved the logger info for time series validation this morning. I think settings="series" should be applied to the series provided to ps.Model.

About the Hantush, rescaling would be preferred I think. But this is up to you. The uncertainty of the gain seems complicated or has to be approximated using Monte Carlo. The latter is technically possible now but less efficient off corse :-)

**Comment by raoulcollenteur** [comment]
Changed Hantush to Gamma for the well. This does not really change the results and the current implementation of Hantush makes it too difficult to compute the confidence interval of the gain for this notebook.

Also removed the dependency of example_2 on the Pastas Project, anticipating the removal of this sub-module in the next Pastas version.

Closing Issue :)
