### ISSUE TITLE
[BUG] syntax warning in stressmodels

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#236]
I think this SyntaxWarning should be fixed

pastas/stressmodels.py:1146: SyntaxWarning: "is" with a literal. Did you mean "=="? 
` if istress is 1 and self.nsplit > 1:`

**Comment by ArtesiaWater** [comment]
I fixed three similar warnings earlier this week. Will fix this as well.

**Comment by rubencalje** [comment]
Just fixed it. Earlier this week I found three similar warnings, which are also gone now.
