### ISSUE TITLE
[BUG] TimeSeries not the same after loading from file

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#238]
**Describe the bug**
I think Onno and I have discovered a bug with TimeSeries for which the frequency cannot be inferred. The following steps show the problem. 
1. Create a model with a stress timeseries for which the frequency cannot be inferred with `pd.infer_freq()`. In my case I have a (slightly weird) TimeSeries with values at the start and end of each month. 
2. Solve the model. Calculate the EVP.
3. Save the model and load from file.
4. Calculate the EVP. This will be different from the EVP calculated in step 2.

I've looked into this, and I know why this is happening but I'm not sure yet what the proper solution should be. 

When creating the stressmodel and adding it to the model, the frequency (timestep) of the stress TimeSeries is set to e.g. 'D' (because that is the model freq). In this process the TimeSeries is converted to daily values in `_change_frequency()` using `_sample_weighted()`. 

Now when the model is loaded from a file the `_validate_series()` method sets the freq_original to the 'D' value stored in the TimeSeries.settings dictionary. It does this in the following code. The reason is the freq_original is None, and it cannot infer the frequency using `pd.infer_freq()`, so it then sets `freq_original` to `self.settings['freq']` which is 'D' (line 370). 

https://github.com/pastas/pastas/blob/ff1a1b50ee5eee975bdb1f472fab85666ab1e270/pastas/timeseries.py#L361-L370

Now both `freq_original` and `freq` have the value 'D'. Which means that when it wants to update the series with `_change_frequency()` it eventually reaches `_fill_nan()`, resulting in a different series and therefore eventually a different EVP.

**To Reproduce**
See zip. [pastas_reload_model_bug.zip](https://github.com/pastas/pastas/files/5317769/pastas_reload_model_bug.zip)

**Expected behavior**
The expected behavior is that when you load a TimeSeries from file, that it is able to exactly reproduce the TimeSeries it created the first time when solving the model. Removing line 370 solves the issue for this particular case, but I'm not sure if that works in general...

**Screenshots**
Screen shot of the script that reproduces this problem:
![image](https://user-images.githubusercontent.com/6552225/94920911-844b8480-04b7-11eb-8576-41714e3ddf70.png)

**Python package version**                                                                                                                                 
Python version: 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
Numpy version: 1.18.1
Scipy version: 1.4.1
Pandas version: 1.0.3
Pastas version: 0.16.0b
Matplotlib version: 3.1.3

**Additional considerations**
Maybe a good idea to add a test that tests equivalence of models before and after load. Onno added a test that does this based on this example to the pastastore, but it is also appropriate for pastas.

**Comment by dbrakenhoff** [comment]
After updating to pastas with PR #237 my timeseries are not the same length before and after load...

**Comment by dbrakenhoff** [comment]
I now see #68 discusses similar problems, I think...

**Comment by raoulcollenteur** [comment]
Does this happen with any other resample method than weighted_resample?

**Comment by rubencalje** [comment]
> After updating to pastas with PR #237 my timeseries are not the same length before and after load...
> 
> EDIT: line 370 has become line 376 ;)


And does this still happen when you remove line 376?

When freq_original is changed to 'D' different resampling- techniques are used (the one in settings instead of timestep_weighted). Therefore I think we should remove line 376, so the same resample-technique is used before and after saving to file.

**Comment by dbrakenhoff** [comment]
> Does this happen with any other resample method than weighted_resample?
I'm not sure what you mean with this question? 

> And does this still happen when you remove line 376?
Yes, removing this line solves the problem for this case.

**Comment by rubencalje** [comment]
So, I will remove line 376 (and adjust some of the lines following that one), to make sure the same resampling technique is used before and after loading of a model.

**Comment by raoulcollenteur** [comment]
@dbrakenhoff can you check this again after pulling the latest changes to Dev? 

I get the following which is much closer but still the time series are not equal.

![Screenshot 2020-11-11 at 17 07 07](https://user-images.githubusercontent.com/12051167/98835230-72f38180-2440-11eb-9358-5111c62e9133.png)

**Comment by dbrakenhoff** [comment]
The timeseries comparison is because of floating point differences I think: `np.allclose(ts1, ts2)`  yields True.

The difference in EVP from the 10th decimal place isn't a problem I don't think. So looking good now!

**Comment by raoulcollenteur** [comment]
Sweet! Can you close the Issue if you are sure? 👍
