### ISSUE TITLE
unexpected behavior resampling Monthly time series

### ISSUE THREAD

**Issue by OnnoEbbens** [pastas/pastas#239]
**Describe the bug**
I have a stress time series with monthly values and a model with a daily frequency. When adding the stressmodel to the model the stress time series is resampled to daily values. This resampling is done according to the settings dictionary. 

The stress time series has a value on the first day of the month which represents the extraction for the whole month. Therefore I use the settings `'sample_up': 'ffill'` and `'to_daily_unit': 'divide'`. Now my resampled stress time series has some unexpected values (see code example below):
1. the daily values in the first month are the monthly values while they should have been divided by the number of days in that month.
2. the other daily values are divided by the number of days in the previous month. e.g. the monthly value of April is 0.860028. The daily values in the resampled series are 0.027743 which is equal to 0.860028/**31**. The daily values should be 0.860028/**30** = 0.0286676. Since April only has **30** days.
3. the resampled time series stops at the first of May while I wished it would stop at 31th of may 1896.

The work arounds are quite easy. To solve 1 and 3 you can add a value of 0 to the start and the end of the monthly time series. For 2 you can create a monthly time series that contains values at the end of each month and use the default well settings (`'sample_up': 'bfill'`). Although the work arounds are easy I think we should fix this because a user does not expect this behavior and it will influence model results.

**To Reproduce**

```
import numpy as np
import pandas as pd
import pastas as ps

np.random.seed(1)

index_gw = pd.date_range('1986-1-1', '1986-5-1', freq='D')
gwdata = pd.DataFrame(index=index_gw,
                      data =np.random.random_sample(len(index_gw)))



well_df = pd.DataFrame(index=pd.date_range('1986-1-1', '1986-5-1', freq='MS'),
                       data=np.random.random_sample(5))

# Create a model object
ml = ps.Model(gwdata, name="GWL")

settings =  {'sample_up': 'ffill',
                  'sample_down': 'mean',
                  'fill_nan': 0.0,
                  'fill_before': 0.0,
                  'fill_after': 0.0,
                  "to_daily_unit": "divide"}
    

w1 = ps.StressModel(well_df, name='tst',
                    rfunc=ps.Hantush, 
                    settings=settings, up=False)

ml.add_stressmodel(w1, True)
s = ml.stressmodels['tst'].stress[0].series
print(well_df)
print(s)
```
This yields
```
                   0
1986-01-01  0.026211
1986-02-01  0.028306
1986-03-01  0.246211
1986-04-01  0.860028
1986-05-01  0.538831

1986-01-01    0.026211
1986-01-02    0.026211
1986-01-03    0.026211
1986-01-04    0.026211
1986-01-05    0.026211
                ...   
1986-04-27    0.027743
1986-04-28    0.027743
1986-04-29    0.027743
1986-04-30    0.027743
1986-05-01    0.017961
Freq: D, Length: 121, dtype: float64
```

Work arounds

```
# use a time series with monthly values at the end of each month
well_df = pd.DataFrame(index=pd.date_range('1986-1-31', '1986-5-31', freq='M'),
                       data=np.random.random_sample(5))

# add a value of zero at the start and the end of the time series
well_df.loc[pd.Timestamp('1985-12-31')] = 0
well_df.loc[pd.Timestamp('1986-6-30')] = 0
well_df.sort_index(inplace=True)

# use default well settings
w1 = ps.StressModel(well_df, name='tst',
                    rfunc=ps.Hantush, 
                    settings='well', up=False)
```

**Expected behavior**
When resampling a monthly time series to a daily time series with the settings `"to_daily_unit": "divide"`, daily values should be the monthly values divided by the number of days in that month. 

This might be solved by improving the `TimeSeries._to_daily_unit` method. If so, I can try to make a pull request for this myself. However I am not sure if adjusting this method will break other things.

**Python package version**
Python version: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.18.5
Scipy version: 1.5.0
Pandas version: 1.0.5
Pastas version: 0.15.0

**Additional context**
I had a look in the example notebooks to see if this issue occurs there. In "7_ well_example.ipynb" daily values are used so there is no issue. In "11_WellModel.ipynb" data from menyanthes is used. A comment in the code (`# the time unit is already days, so we need te set to_daily_unit to None`) suggests these are daily values. When I load the data I get a monthly time series. Because the `daily_unit` is set to `None` the monthly values are used as daily values in the model. Although model results will not change a lot I think this should be fixed as well.

**Comment by raoulcollenteur** [comment]
Related to the open Issue #216. Should be solved at the same time.

**Comment by ArtesiaWater** [comment]
to_daily_unit assumes the values are at the end of each period, which is the default setting in sample_up ('bfill'). As you mention Onno, this gives problems when other settings for sample_up are used. I will try to fix 1 and 2 for now, but a more robust solution is to remove to_daily_unit fully. The user is then responsible for the unit of the stresses.

Number 3 needs to be solved in _sample_up, so I think this is a separate issue.

About the comment `# the time unit is already days, so we need te set to_daily_unit to None`. What is meant is that, if I remember correctly,  the unit of the series is already m3/d (and not m3/month). The frequency of the series is monthly indeed, as you mention. I will try to make this more clear.

**Comment by rubencalje** [comment]
to_daily_unit assumes the values are at the end of each period, which is the default setting in sample_up ('bfill'). As you mention Onno, this gives problems when other settings for sample_up are used. I will try to fix 1 and 2 for now, but a more robust solution is to remove to_daily_unit fully. The user is then responsible for the unit of the stresses.

Number 3 needs to be solved in _sample_up, so I think this is a separate issue.

About the comment `# the time unit is already days, so we need te set to_daily_unit to None`. What is meant is that, if I remember correctly, the unit of the series is already m3/d (and not m3/month). The frequency of the series is monthly indeed, as you mention. I will try to make this more clear.

**Comment by raoulcollenteur** [comment]
> but a more robust solution is to remove to_daily_unit fully

I would  very much vote for this option. We could instead provide a function in util to do this if desired.

**Comment by rubencalje** [comment]
> I would very much vote for this option. We could instead provide a function in util to do this if desired.

Yes, that would be better. The difficulty is in how to deal with existing models that use to_daily_unit...

**Comment by raoulcollenteur** [comment]
Given that this is a completely undocumented feature (#216) I suspect very few users would have used this. And otherwise, they were using an undocumented feature so they knew what they were doing already and should be able to fix there time series before providing them to Pastas. I think we can simply remove this for the next version and provide a separate function.

**Comment by raoulcollenteur** [comment]
I have removed to_daily_unit method from the TimeSeries object and created a separate (experimental) method in utils.py (`ps.utils.to_daily_unit)`. Since it was an experimental feature there is should be no concern with backward incompatibility.

Couple of notes there:

- No documentation was provided with the function when it was added, nor in the TimeSeries.update_series (#216). Yet it was used when settings "well" were used. This leads to completely unknown behaviour for users and they have no way of finding out what happens. Since the TimeSeries object is extremely important for simulation I really think we should not let this happen again.
- Since it is a stress, it has to have a constant time steps. The freq="M" violates this assumption and should not work when convoluting with a response function. This is also stated in the docs from update_series. The example provided by @OnnoEbbens is therefor invalid.

**Summarising**: for a stress you must have a time series with a regular grid. Pastas can deal with missing data for the stresses, but NOT with irregular grids for the time indices. We need to document this much better somewhere.

For future work I can imagine that we add a function that transforms a time series from an irregular grid (e.g. Month) to a regular grid (e.g., "Days") to utils.py.

**Comment by dbrakenhoff** [comment]
I'm all good with moving this feature to utils as a separate pre-processing function. 

Not sure if this is already the case at this point, but I'd appreciate being able to load models from older versions of pastas where `_to_daily_unit` was still used. Not that the feature was necessarily used in those models, but the key is stored in the settings dictionaries and I'm hoping that `ps.io.load` will be able to deal with that.

**Comment by raoulcollenteur** [comment]
Dealing with that right now

**Comment by rubencalje** [comment]
> I have removed to_daily_unit method from the TimeSeries object and created a separate (experimental) method in utils.py (`ps.utils.to_daily_unit)`. Since it was an experimental feature there is should be no concern with backward incompatibility.
> 
> Couple of notes there:
> 
> * No documentation was provided with the function when it was added, nor in the TimeSeries.update_series (#216). Yet it was used when settings "well" were used. This leads to completely unknown behaviour for users and they have no way of finding out what happens. Since the TimeSeries object is extremely important for simulation I really think we should not let this happen again.
> * Since it is a stress, it has to have a constant time steps. The freq="M" violates this assumption and should not work when convoluting with a response function. This is also stated in the docs from update_series. The example provided by @OnnoEbbens is therefor invalid.
> 
> **Summarising**: for a stress you must have a time series with a regular grid. Pastas can deal with missing data for the stresses, but NOT with irregular grids for the time indices. We need to document this much better somewhere.
> 
> For future work I can imagine that we add a function that transforms a time series from an irregular grid (e.g. Month) to a regular grid (e.g., "Days") to utils.py.

All resample methods function properly for monthly data. It is one of the frequencies that are supported as input for a Timeseries-object.

**Comment by OnnoEbbens** [comment]
This issue was solved (long time ago) by moving `to_daily_unit` from the settings to `util`
