### ISSUE TITLE
[BUG] ml.get_stress does not work for WellModel

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#244]
**Describe the bug**
ml.get_stress does not work for WellModel.

**To Reproduce**
```
ml = ps.io.load("example.pas")
ml.get_stress("wells")
```

returns

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-beaa3ca231c1> in <module>
----> 1 ml.get_stress("wells")

~/Projects/pastas/pastas/pastas/decorators.py in _get_stressmodel(self, name, **kwargs)
     25                          "following list: {}".format(self.stressmodels.keys()))
     26         else:
---> 27             return function(self, name, **kwargs)
     28 
     29     return _get_stressmodel

~/Projects/pastas/pastas/pastas/model.py in get_stress(self, name, tmin, tmax, freq, warmup, istress, return_warmup, parameters)
   1606         stress = self.stressmodels[name].get_stress(p=parameters, **kwargs)
   1607         if not return_warmup:
-> 1608             stress = stress.loc[tmin:tmax]
   1609 
   1610         return stress

AttributeError: 'list' object has no attribute 'loc'

```
**Expected behavior**
Work.

**Python package version**
Python version: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09) 
[Clang 10.0.1 ]
Numpy version: 1.18.5
Scipy version: 1.4.0
Pandas version: 1.1.2
Pastas version: 0.16.0b
Matplotlib version: 3.1.3
numba version: 0.49.1

[example.zip](https://github.com/pastas/pastas/files/5461239/example.zip)

**Comment by dbrakenhoff** [comment]
I submitted a fix via #245 , but now I'm not so sure what `ml.get_stress` is supposed to do.

I assume you're expecting the original stress timeseries? What do you expect if there are multiple? In the case of the WellModel it's not really logical to add them together and return one timeseries like it is for `StressModel2`.

Maybe we should return a list of pandas.Series if there are multiple stresses in a StressModel? In that case we just need to fix the return_warmup to also work with a list of stresses.

Thoughts?

**Comment by raoulcollenteur** [comment]
The ml.get_stress should return the stress that is used, or stresses. #245 changes the method such that the contribution is returned. This is already covered by ml.get_contribution().

I think it would be logical to return a DataFrame or a list with the time series of the stresses used for convolution, not the original series.

**Comment by dbrakenhoff** [comment]
My bad, I meant the stress used in convolution. And I got a bit confused by the usage of simulate in another StressModel. Anyway, I submitted a new PR #246 that takes care of this issue. 

This is probably a separate issue, but I ran into the following with your example model:

```python
import pastas as ps
ml = ps.io.load("example.pas"
wm = ml.stressmodels["wells"]

wm.simulate(ml.get_parameters("wells"))  # --> doesn't work
```
Returns a vague error because `freq=None` (see below).  Would you expect this statement to work without providing a `freq`? If any case, the error message isn't very helpful, and could probably be improved. 

```python
~/Github/pastas/pastas/utils.py in _get_time_offset(t, freq)
    145 
    146     """
--> 147     return t - t.floor(freq)
    148 
    149 

pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.floor()

pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp._round()

pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.round_nsint64()

AttributeError: 'NoneType' object has no attribute 'nanos'
```

**Comment by raoulcollenteur** [comment]
Thanks for the PR, just merged it. Should we make an Issue for your comment above? Not sure if people really call the simulate method directly on the WellModel object and if that works for other stress models anyway..

**Comment by dbrakenhoff** [comment]
Yea, I agree it's probably not really a big issue. But it would be nice to return a TypeError instead of this AttributError. I'll make a new issue.
