### ISSUE TITLE
Improve error message when updating timeseries with freq=None?

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#249]
This is not a major issue, and I'm not sure if users ever really run into this, but I did while testing some things. 
When updating a timeseries when freq is None this results in a slightly vague error. 

Example:
```python
import pandas as pd
import pastas as ps

s = pd.Series(index=pd.date_range("2020-01-01", "2020-06-30", freq="D"),
              data=1.)
ts = ps.TimeSeries(s)
ts.settings["fill_before"] = 0.0

ts.update_series(tmin=ts.series.index[0] - pd.Timedelta(days=10), freq=None)  # this results in error below
```

```python
AttributeError: 'NoneType' object has no attribute 'nanos'
```
I guess it's pretty obvious this is about the frequency being None, but the `_update_frequency()` method is fine with `freq=None` and just returns the original series. So either the `_fill_before()` method should also be able to deal with that or we add a slightly clearer error message?

I would propose the latter and add the following to `_get_time_offset()` in utils.py:

```python
if freq is None:
  raise TypeError("frequency is None")
```

**Comment by raoulcollenteur** [comment]
Implemented as suggested. Closing Issue.
