### ISSUE TITLE
[BUG] Unexpected behaviour ml._get_time_offset

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#252]
**Describe the bug**
I refactored the ml.set_time_offset method into a get method, to make it easier to debug and be in line with the other methods. The method now returns the offset instead of directly changing the settings dict.

**To Reproduce**
ml._get_time_offset("D")

returns 

Timedelta('0 days 00:00:00')

but anything else (2D, 4D, 40D, 365D) returns

Timedelta('1 days 00:00:00')

**Expected behavior**
I am actually not sure what behaviour is expected. I would say all of these should return 0?

**Python package version**
Python version: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09) 
[Clang 10.0.1 ]
Numpy version: 1.18.5
Scipy version: 1.4.0
Pandas version: 1.1.2
Pastas version: 0.16.0b
Matplotlib version: 3.1.3

**Additional context**
Possibly related to #250 but not sure.

**Comment by raoulcollenteur** [comment]
@rubencalje, what do you think about adding the following to ps.utils._to_time_offset?  

```
freq = to_offset(freq).name  # Maybe something like this first??
return t - t.floor(freq)
```

I think this would solve it?

**Comment by rubencalje** [comment]
I do not really understand what your solution means.  I do not think we should look in ps.utils._to_time_offset.

I think the problem is in ps.Model._get_time_offset, where there should be a '>=' sign instead of a '>' sign. I will commit this change. I do not get an offset of 1 day now anymore, for the frequencies you mentioned.

**Comment by rubencalje** [comment]
The way the offset is called now (_get_time_offset instead of _set_time_offset) is much better by the way. It is more useful now.

**Comment by raoulcollenteur** [comment]
Cool thanks! Seems to work well now, closing the Issue :)
