### ISSUE TITLE
Remove FactorModel from stressmodels (redundant)

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#253]
I would like to deprecate and finally remove the FactorModel from Pastas, because StressModels can already do exactly the some using the rfunc ps.One as follows: 

`w = ps.StressModel(waterlevel, rfunc=ps.One,  name="waterlevel", settings="waterlevel")`

will yield the exact same result as:

`w = ps.FactorModel(waterlevel, name="waterlevel", settings="waterlevel")`

Thus I think the stress model is redundant and we can remove FactorModel and keep maintenance down. I added the model three years ago and I don't think it is used that much. We can start giving deprecation warnings with the above code.

Anyone against this?

EDIT: FactorModel actually does not work with well with some methods like ml.plots.results(). As an example of maintenance.

**Comment by rubencalje** [comment]
Fine by me, although we have some projects that will fail then. What do you think, @dbrakenhoff?

**Comment by dbrakenhoff** [comment]
I think it should be okay to add a deprecation warning this version. We can keep those projects on the version of pastas they are currently using. If we do need to update, the fix is relatively simple.
