### ISSUE TITLE
LinAlgError when trying to solve a model for the first time

### ISSUE THREAD

**Issue by OnnoEbbens** [pastas/pastas#258]
When I try to solve a model I get a `LinAlgError` with the message: `SVD did not converge`. Then when I run `ml.solve()`  again I don't get this error. The model results are good when solving the second time. I don't understand why I get the error and I don't understand why I don't get an error the second time. I guess it has to do something with the number of iterations or other solver settings. Any ideas how to fix this?

**To Reproduce**
Data is in the attached zip file.
[data.zip](https://github.com/pastas/pastas/files/5715272/data.zip)
```
import pastas as ps
import pandas as pd
# read timeseries
oseries = pd.read_csv("data/grondwaterstand.csv",
                       parse_dates=True,  squeeze=True, index_col=0)
neerslag = pd.read_csv("data/neerslag.csv", parse_dates=True,
                    squeeze=True, index_col=0)
verdamping = pd.read_csv("data/verdamping.csv", parse_dates=True,
                    squeeze=True, index_col=0)

# create model
ml = ps.Model(oseries)
sm = ps.StressModel(neerslag-verdamping, rfunc=ps.Gamma, name="recharge")
ml.add_stressmodel(sm)
ml.solve()
```
yields

```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-23-40197eda27e4> in <module>
----> 1 ml.solve(report=False)

C:\Anaconda3\lib\site-packages\pastas\model.py in solve(self, tmin, tmax, freq, warmup, noise, solver, report, initial, weights, fit_constant, **kwargs)
    736         # Solve model
    737         success, optimal, stderr = self.fit.solve(noise=self.settings["noise"],
--> 738                                                   weights=weights, **kwargs)
    739         if not success:
    740             self.logger.warning("Model parameters could not be estimated "

C:\Anaconda3\lib\site-packages\pastas\solver.py in solve(self, noise, weights, callback, **kwargs)
    334         self.result = least_squares(self.objfunction, bounds=bounds,
    335                                     x0=parameters.initial.values,
--> 336                                     args=(noise, weights, callback), **kwargs)
    337 
    338         self.pcov = DataFrame(self._get_covariances(self.result.jac,

C:\Anaconda3\lib\site-packages\scipy\optimize\_lsq\least_squares.py in least_squares(fun, x0, jac, bounds, method, ftol, xtol, gtol, x_scale, loss, f_scale, diff_step, tr_solver, tr_options, jac_sparsity, max_nfev, verbose, args, kwargs)
    915         result = trf(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol, xtol,
    916                      gtol, max_nfev, x_scale, loss_function, tr_solver,
--> 917                      tr_options.copy(), verbose)
    918 
    919     elif method == 'dogbox':

C:\Anaconda3\lib\site-packages\scipy\optimize\_lsq\trf.py in trf(fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale, loss_function, tr_solver, tr_options, verbose)
    123         return trf_bounds(
    124             fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale,
--> 125             loss_function, tr_solver, tr_options, verbose)
    126 
    127 

C:\Anaconda3\lib\site-packages\scipy\optimize\_lsq\trf.py in trf_bounds(fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale, loss_function, tr_solver, tr_options, verbose)
    299             J_h = J_augmented[:m]  # Memory view.
    300             J_augmented[m:] = np.diag(diag_h**0.5)
--> 301             U, s, V = svd(J_augmented, full_matrices=False)
    302             V = V.T
    303             uf = U.T.dot(f_augmented)

C:\Anaconda3\lib\site-packages\scipy\linalg\decomp_svd.py in svd(a, full_matrices, compute_uv, overwrite_a, check_finite, lapack_driver)
    127 
    128     if info > 0:
--> 129         raise LinAlgError("SVD did not converge")
    130     if info < 0:
    131         raise ValueError('illegal value in %dth argument of internal gesdd'

LinAlgError: SVD did not converge
```

**Python package version**
Python version: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.19.2
Scipy version: 1.5.2
Pandas version: 1.1.3
Pastas version: 0.16.0
Matplotlib version: 3.3.2

**Comment by dbrakenhoff** [comment]
I cannot reproduce this issue with latest version of pastas.

Does updating and `pastas` and or `pandas` resolve the issue?

**Python package version**
Python version: 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
Numpy version: 1.19.2
Scipy version: 1.5.2
Pandas version: 1.1.4
Pastas version: 0.17.0b
Matplotlib version: 3.3.2

**Comment by OnnoEbbens** [comment]
I do get the error when using the dev version of pastas (0.17.0b) and the newest version of pandas (1.2.0). Weird thing is that I don't get the error when I use the same package versions with a different Python version. 

**Python package versions with errors**
Python version: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.19.2
Scipy version: 1.5.2
Pandas version: 1.2.0
Pastas version: 0.17.0b
Matplotlib version: 3.3.2

**Python package versions without errors**
Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.19.2
Scipy version: 1.5.2
Pandas version: 1.2.0
Pastas version: 0.17.0b
Matplotlib version: 3.3.2

**Comment by dbrakenhoff** [comment]
I just tried with pandas 1.2.0 and still no errors here...

Python version: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
Numpy version: 1.19.2
Scipy version: 1.5.2
Pandas version: 1.2.0
Pastas version: 0.17.0b
Matplotlib version: 3.3.2

**Comment by raoulcollenteur** [comment]
What about the Numba dependency? You can run ps.show_versions(numba=True).. Lmfit is not used right?

**Comment by dbrakenhoff** [comment]
For me: 
numba version: 0.52.0

**Comment by OnnoEbbens** [comment]
Both times, with and without the error, I used Numba version 0.51.2

Upgrading to 0.52.0 did not solve the error.

So mysterious..

**Comment by dbrakenhoff** [comment]
I guess we could compare the input to `svd`, to see if that is somehow different...?

**Comment by OnnoEbbens** [comment]
It seems there is something strange happening deep inside scipy. It probably has to do with some inconsistency in my environment. When I run the script with the same packages in a clean environment everything runs as it should. I will close this issue
