### ISSUE TITLE
implement _set_optimal method 

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#259]
I suggest we implement a `_set_optimal` method in addition to `_set_initial`, `_set_pmin`, `_set_pmax`, `_set_vary`
This will allow the user to select the value that is used in calculations. Right now this can only be done by modifying the `parameters` attribute. That works, but is not desired.

**Comment by raoulcollenteur** [comment]
Good idea. We should then also add this keyword to the set_parameter method (e.g., `ml.set_parameter(optimal=10)`)

**Comment by raoulcollenteur** [comment]
Just added this feature. Only works for the model class, as the stressmodel and rfunc objects don't store "optimal" values in the dataframes. Usage is as follows:

`ml.set_parameter("recharge_A", optimal=600)`

Closing issue.
