### ISSUE TITLE
[BUG] R2 shown as percentage in the plots

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#260]
**Describe the bug**
R2 is somehow reported as a percentage in the plotting methods now, while is should be a float between 0 and 1.

**Comment by rubencalje** [comment]
Do you mean the percentage described in commit  8f992be97aa65f7552b1532f676f82a1ffd717b7?

I think a percentage is easy to understand, and I believe it is allowed to display a R2-value as a percentage. Therefore I am in favor of keeping it this way.

**Comment by dbrakenhoff** [comment]
Yea, i put it there as a percentage. I think we discussed putting R2 as it is a more well known metric, and I put it as a percentage because the EVP is/was given as a percentage.

**Comment by raoulcollenteur** [comment]
> I think a percentage is easy to understand, and I believe it is allowed to display a R2-value as a percentage. Therefore I am in favor of keeping it this way.

Sorry I got confused. I checked and this is indeed common I think and I also prefer it. 

Somehow internally we still used EVP so I changed that to rsq which is normally the same so not a real change (unless R2<0).

closed with commit #5f4261f
