### ISSUE TITLE
Move to Github actions?

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#264]
Is it an idea to move to GitHub actions instead of travis? I did it for the pastastore module and quite liked how it worked. It should be relatively simple to copy the configuration from pastastore and adapt it for pastas.

Thoughts?

**Comment by rubencalje** [comment]
Fine by me. But it may need some configuration, for example with codecov, or is that something else? @raoulcollenteur ?

**Comment by dbrakenhoff** [comment]
pastastore is also still integrated with codecov via codacy. So it all stays the same but minus travis.

**Comment by raoulcollenteur** [comment]
Sounds good to me. I also implemented a GitHub Action for publishing to Pypi and it seems to work well. Is it possible to create the GitHub action in parallel to Travis to start?

**Comment by dbrakenhoff** [comment]
Yep, that should be possible.

**Comment by raoulcollenteur** [comment]
Done. Closing Issue. Thanks @dbrakenhoff !
