### ISSUE TITLE
Reading menyanthes file in pastas (with read_meny)

### ISSUE THREAD

**Issue by TijmenHeetebrij** [pastas/pastas#271]
Hi,
I am exploring the possibilities to use pastas instead of menyanthes. The data I have is often already in a menyanthes file, I tried to read the menyanthes file in pastas with the read_meny method. I got an error though:

AttributeError: 'mat_struct' object has no attribute 'tnocode'

Should I do something differently or is there another way to import the data from a menyanthes file?

Thanks in advance!

**Comment by rubencalje** [comment]
Hi Tijmen,

The Menyanthes import functions for a certain Menyanthes-version (of about 2 years ago). It could be that the file from a newer Menyanthes version cannot be imported. The file format tends to change rather frequently. You could try changing the MenyData-class. We could make the import depend on the Menyanthes-version, but this would take some work.

**Comment by TijmenHeetebrij** [comment]
Hi Ruben,
That's clear. Thank you for the fast response!
