### ISSUE TITLE
Reduce tests duration?

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#288]
I saw that notebook 14_timestep_analysis is taking about 4-5 mins to run, which is almost half the total time it takes to run all the tests. So maybe an idea to remove this notebook from the tests to speed them up?

If not, just close this issue, but just thought I'd mention it.

**Comment by raoulcollenteur** [comment]
Yes definitely an Issue, I also noticed this. I think in general we may want to use CI computing power a bit more efficiently. E.g., notebooks actually don't have to be tested all the time, maybe only when we merge. This would in general be an improvement I think.

**Comment by dbrakenhoff** [comment]
I made a first attempt on dev branch to discern between the notebooks and the other tests:

- I added a marker to the notebook tests, 
- The github workflow has 2 steps for testing:
   - on push: run all tests (also notebooks)
   - on pull_request: do not run notebooks

I'm not quite sure what happens to the coverage reporting though if the notebooks are not run...

**Comment by raoulcollenteur** [comment]
I think that should be the opposite: 

on pull: run all tests (also notebooks)
on push: do not run notebooks

We push a lot more than we pull :)

**Comment by dbrakenhoff** [comment]
That does make more sense I think, I think I was reasoning from my Hantush PR, which I kept adding commits to. I'll switch the behavior.

**Comment by raoulcollenteur** [comment]
Cool, your last commit seems to have fixed this! 

It only decreased coverage a bit I think, but not for the master branch, because this is determined by a pull-request. So perfect as it is now I think 👍🏻

**Comment by dbrakenhoff** [comment]
I read somewhere that a PR merge results in a push, so I think maybe this change will also reduce coverage on master eventually...?

For a discussion on this subject see e.g. https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359
or https://brennerm.github.io/posts/trigger-github-actions-on-pr-close.html

I think flopy uses an extra job to calculate coverage, which could also be a solution if this doesn't work out as well as we hoped.

But let's leave it like this for now and see how that works out!

**Comment by raoulcollenteur** [comment]
I think the time to run the CI is acceptable now, shall we close this issue @dbrakenhoff ?
