### ISSUE TITLE
Drop Python 3.6 support for Pastas 0.18 and bump dependencies

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#293]
I propose to drop Python 3.6 support for the next release of Pastas (0.18, planned the end of June). Numpy, Scipy and Pandas have all dropped their support for 3.6 now. Other dependencies could be bumped up as well?

Python: >= 3.7.1
Numpy => 1.17 ??
Scipy => 1.5 ??
Pandas >=1.1
Matplotlib => 3.1

Thoughts?

**Comment by mbakker7** [comment]
I think this is a good idea. What about numba?

**Comment by raoulcollenteur** [comment]
Numba would remain optional (but highly recommended, also Pandas uses it internally now).

**Comment by raoulcollenteur** [comment]
For future references.

NumPy, Scipy, Matplotlib, and Pandas all (plan to) follow NEP29: https://numpy.org/neps/nep-0029-deprecation_policy.html

This means the following:

> This project supports:
> 
> All minor versions of Python released 42 months prior to the project, and at minimum the two latest minor versions.
> All minor versions of NumPy, Scipy, Matplotlib, and Pandas released in the 24 months prior to the project, and at minimum the last three minor versions.
> 

I'll put that in the developers documentation and update the dependencies. Pretty sure everyone uses higher dependencies already.
