### ISSUE TITLE
Math not rendering in Hantush notebook in docs

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#294]
See link: https://pastas.readthedocs.io/en/latest/concepts/hantush_response.ipynb.html

Math is not rendering (and also the table is not showing properly).

**Comment by raoulcollenteur** [comment]
Do you know if this is a thing with Sphinx, Jupyter, or our formatting?

**Comment by dbrakenhoff** [comment]
Math seems ok now... But the pros/cons table is still funky. The table is a combination of html and markdown code, I think, so maybe that's not supported as well as I'd hoped. Leave open for now, and I'll try simplifying the table to something that renders nicely.

**Comment by dbrakenhoff** [comment]
Fix table c74adebc40e1218deab5c053d812efe7c1318fd9
