### ISSUE TITLE
[Enhancement] Check data types in load_model method

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#304]
**Describe the bug**
The data types are not well checked when reading a pastas model from a .pas file. See for example this issue in the Pastastore:

https://github.com/pastas/pastastore/issues/39

A name is a string, but load_model with return an integer of only numbers are provided.

**Expected behavior**
Data types should be the same, basically for everything..

**Comment by dbrakenhoff** [comment]
Enforce dtypes, e.g. for names (=str).
Check for illegal characters in strings.

**Comment by raoulcollenteur** [comment]
Closing after PR #415
