### ISSUE TITLE
Root Mean Square Error description

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#306]
The [description of the Root Mean Square Error is incorrect](https://github.com/pastas/pastas/blob/master/pastas/stats/metrics.py
).
Currently:
```
    Notes
    -----
    Computes the Root Mean Squared Error (RMSE) as follows:
    .. math:: \\text{RMSE} = \\sqrt{\\sum_{i=1}^{N} w_i(n_i- \\bar{n})^2}
    where :math:`N` is the number of residuals :math:`n`.
```
but  <img src="https://render.githubusercontent.com/render/math?math=RMSE \neq \sqrt{\sum_{i=1}^N w_i(n_i- \bar{n})^2}"> . This is actually the formula for the standard deviation (if w_i is the same for all residuals). 

The formula for the RMSE should be:
```
.. math:: \\text{RMSE} = \\sqrt{\\sum_{i=1}^{N} w_i (n_i)^2}
```
<img src="https://render.githubusercontent.com/render/math?math=RMSE = \sqrt{\sum_{i=1}^N w_i(n_i)^2}"> which is also what is calculated.

**Comment by raoulcollenteur** [comment]
Thanks for reporting and the PR, docstring was wrong indeed. Merging the PR and closing this issue!
