### ISSUE TITLE
add polder function

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#31]
Nice library! The polder function (Bruggeman) is not included in rfunc.py. It would be nice to have as well to be able model surface water stresses.

**Comment by mbakker7** [comment]
Tom,

That function is on the list to implement. But in the mean time, it turns
out that the Gamma function works remarkably well for surface water
stresses. (-:

Mark

**Comment by raoulcollenteur** [comment]
Thanks to @rubencalje the Bruggeman method is now included in the list of response functions (commit 3d025988e3b7e85a2a5e0c3170f0e99c3ba2c2b4), closing this issue :)
