### ISSUE TITLE
number of parameter samples not equal to passed n

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#311]
When getting parameter samples with `ml.fit.get_parameter_sample()` the truncated multivariate parameter sampling sometimes leads to a lower number of returned parameter samples than the `n` passed by the user.

The number of iterations in the while loop is hardcoded to 10. I propose making this a parameter (i.e. `max_iter`), and logging a warning when the number of returned parameter samples is lower than `n`. 

I updated pastas locally to test this, let me know if you think this is a good idea, and I will push it to dev.

**Comment by raoulcollenteur** [comment]
Ah yes that makes sense! Could you commit the code? `max_iter` sound good as well.

**Comment by dbrakenhoff** [comment]
Added in dd72369b625c5f17d269e2917c01ae62174141db
