### ISSUE TITLE
Interception Storage in FLEX Recharge model

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#314]
Remove the interception storage zone with one command `interception=False`. The same as the snow storage zone with `snow=False` in the FLEX model. To remove the interception storage Si,max can just be set to 0.

**Comment by raoulcollenteur** [comment]
I now added this feature to the FlexModel in the snow model branch. You can now do:

`ps.rch.FlexModel(interception=False)`

If False, the interception bucket is removed, saving one parameter (that is not calibrated by default, but still..) and some computation time.
