### ISSUE TITLE
[BUG] RuntimeWarning: invalid value encountered in log10 atol = np.min([1e-8, 10**(np.round(np.log10(pmin)) - 1)])

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#317]
**Describe the bug**
```
/opt/miniconda3/envs/iah/lib/python3.9/site-packages/pastas/model.py:1658: 
RuntimeWarning: invalid value encountered in log10
  atol = np.min([1e-8, 10**(np.round(np.log10(pmin)) - 1)])
```
The model still solves fine but the parameter `pmin` probably hits negative values.

**To Reproduce**
ml.solve() with the newest pastas (and python) version. The error does not occur when using Pastas version 0.17.0

**Python package version**
Python version: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
[GCC 9.3.0]
Numpy version: 1.20.3
Scipy version: 1.7.1
Pandas version: 1.3.2
Pastas version: 0.18.0
Matplotlib version: 3.4.3
lmfit version: 1.0.2
numba version: 0.54.0

**Additional context**
Occurred when running the NB1_simple_model.ipynb workshop notebook

**Comment by martinvonk** [comment]
Just noticed I also get a for a model. This means `pmin` also hits 0. 
```
/opt/miniconda3/envs/iah/lib/python3.9/site-packages/pastas/model.py:1658: 
RuntimeWarning: divide by zero encountered in log10
  atol = np.min([1e-8, 10**(np.round(np.log10(pmin)) - 1)])
```

**Comment by dbrakenhoff** [comment]
This should be all fixed now.
