### ISSUE TITLE
[Enhancement] calculate covariance if the solver doesn't 

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#319]
I've been working with LmfitSolve recently and in some cases, usually when a model isn't performing very well, the parameter uncertainties are not calculated and show up as NaN in the parameters, and results plot etc.

I know there were some issues related to this behavior (for dealing with the lack of a result) that have been fixed. But I remembered that [metran](https://github.com/pastas/metran) has code to calculate the uncertainties if this happens. See [the code here](https://github.com/pastas/metran/blob/ac3c74ceedb75447243e369b3ba771e48099f00e/metran/solver.py#L258-L262) for example.

Perhaps an idea to include something similar for Pastas?

**Comment by raoulcollenteur** [comment]
I also observed this quite frequently with LMFit. Do we know when this happens? Perhaps LMFit has some solutions there?

**Comment by dbrakenhoff** [comment]
LmFit lists this on their website: https://lmfit.github.io/lmfit-py/faq.html#why-are-uncertainties-in-parameters-sometimes-not-determined

**Comment by dbrakenhoff** [comment]
Needs more research. Check some models where this occurs to diagnose reason. Might also be reasonable not to return estimates if result is too uncertain/meaningless.

**Comment by dbrakenhoff** [comment]
@wlberendrecht might be able to help with this issue? You implemented this in metran, can that solution be adapted to pastas?

**Comment by wlberendrecht** [comment]
Yes, it might help to calculate the covariance matrix as implemented in metran. It uses finite differences to estimate the hessian. From this the covariance matrix is calculated. 

I suggest to include a check why the covariance matrix has not been calculated. If there is a plausible reason for it, I don't think it is wise to "overrule" this with a finite difference approach.
