### ISSUE TITLE
GXG functions grayed out

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#32]
Methods for calculating Dutch groundwater statistics GHG and GLG are included in the Statistics class. 
Why are these commented out? Can I add percentile based methods? I have forked the repo.

**Comment by rubencalje** [comment]
I think it was commented out because the GHG- and GLG-method now does not take the frequency of the data into account. We can solve this by sampling the series at the 14th and 28th of every month (which has my preference), or use a percentile-based method like you propose.

**Comment by tomvansteijn** [comment]
I have implemented a percentile-based method in my fork. Needs some testing. Can implement the classic method as well, if you like I can send a pull request  when its ready.

Tom van Steijn MSc
Hydrologist
T +31 88 348 23 34 | M +31 6 54 24 50 79 | E tom.van.steijn@rhdhv.com<mailto:tom.van.steijn@rhdhv.com> | W www.royalhaskoningdhv.com<http://www.royalhaskoningdhv.com/>

**Comment by raoulcollenteur** [comment]
Tom,

The GxG methods were indeed commented out because they need some further work on how these statistics are calculated.. It would be great if you could add percentile based methods and create a pull request for that. I think Pandas has some built-in functions that can be called? 

Cheers, Raoul

**Comment by raoulcollenteur** [comment]
Closed the issue as I think it is all solved for now.

**Comment by tomvansteijn** [comment]
Good. You can let me know if there is more work to be done on this issue or another.
