### ISSUE TITLE
[BUG] _get_response() function option add_0=True returns 1 as first value of index

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#320]
**Describe the bug**
The function [_get_response](https://github.com/pastas/pastas/blob/3785c14c54d293f611f3c84b43e163556491cddc/pastas/model.py#L1270) returns a pandas Series of the block or step response. The index of this series starts at 1 since it is the _time after the impulse_ (for the block response). 

When setting `add_0=True`, a value of zero is added to the first value of the Series. However, the index remains the same and starts at 1. It would be more logical if the index would remain _time after the impulse_ and would have an index starting value of 0 if `add_0=True`. Also, the description states: _adds a zero at t=0_ so this fix would be in line with the description.

```
def _get_response(self, block_or_step, name, p=None, dt=None, add_0=False, **kwargs):

add_0: bool, optional
            Add a zero at t=0.
```

**Expected behavior**
First value of the index of block and step response should become 0 if `add_0=True`

**Screenshots**
CURRENTLY
![image](https://user-images.githubusercontent.com/66305055/133109130-8d584c63-0a74-411f-86dc-15175c514496.png)
WHAT I BELIEVE IT SHOULD BE
![image](https://user-images.githubusercontent.com/66305055/133109063-82ff4825-7fe2-4c59-aa52-3a7c21027613.png)

**Python package version**
Python version: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
[GCC 9.3.0]
Numpy version: 1.20.3
Scipy version: 1.7.1
Pandas version: 1.3.2
Pastas version: 0.19.0b
Matplotlib version: 3.4.3
numba version: 0.54.0

**Comment by raoulcollenteur** [comment]
Yes I think you are right. Let's double-check with @rubencalje ? @martinvonk perhaps you can do a PR with a fix?

**Comment by rubencalje** [comment]
Yes, Martin already checked with me, I think he is right. We will try to fit it.

**Comment by raoulcollenteur** [comment]
Merged.
