### ISSUE TITLE
[BUG] Numba errors with v0.50.1

### ISSUE THREAD

**Issue by TimFranken** [pastas/pastas#329]
**Describe the bug**
Fitting a model with a non linear recharge function results in an error. This happens both with the Berendrecht and the Flex model. The final error is:
`SystemError: CPUDispatcher(<function Berendrecht.get_recharge at 0x0000029BE63F8048>) returned a result with an error set
`From the stack trace there seems to be a type mismatch that Numba does not like:
`TypeError: expected dtype object, got 'numpy.dtype[float64]'
`
Commenting the njit decorator from the `get_recharge `function solves the error but makes it rather slow.

**To Reproduce**
I tested the 07_non_linear_recharge notebook in the examples and got the same error.

**Python package version**
Python version: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.20.3
Scipy version: 1.5.0
Pandas version: 1.2.3
Pastas version: 0.18.0
Matplotlib version: 3.2.2
numba version: 0.50.1

**Comment by martinvonk** [comment]
> `pip install --upgrade --force-reinstall pastas`

I recreated the error but the above solution did not work for me. 

The solution that worked for me was upgrading Numba version to 0.53.1 or 0.54.1. Most easy is to use `pip install numba`. That'll install the latest version 0.54.1. Make sure you remove the old Numba version first or create a new environment.

**Comment by raoulcollenteur** [comment]
OK. So it seems the error is Numba related and updating to Numba > 0.51 fixes the problem.

**Comment by raoulcollenteur** [comment]
Updating Numbda should fix the problem. Closing Issue.
