### ISSUE TITLE
[ENHANCEMENT] add optional dependencies to setup.py

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#331]
We can have a look if we can define optional dependencies somewhere, such as Numba and Lmfit. That way we can also indicate a minimum version for those packages, to prevent issues such as #329 .

https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#declaring-dependencies

**Comment by martinvonk** [comment]
This can be solved by adding the following to setup.py:
```
setup(
...
extras_require={'numba': ['numba>=0.51'],
                'lmfit': ['lmfit>=1.0.0']
               },
)
```

To install with these dependencies one uses `pip install pastas[numba,lmfit]` or locally `pip install -e .[numba,lmfit]`

We can also make it a bit easier and parse `extras_require={'full': ['numba>=0.51', 'lmfit>=1.0.0']}` and install using `pastas[full]`
