### ISSUE TITLE
[ENHANCEMENT] improve reindexing to equidistant timeseries in stoffer_toloi

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#336]
In the `stoffer_toloi` diagnostic test, the series is reindexed to a equidistant time index using `series.asfreq(freq)`. The trouble with this method is that if the first timestamp from the original series (in this case the noise) is different from all other timestamps, an almost empty timeseries is returned which is then used in the tests, leading to vague errors in some cases. 

The following snippet shows the problem:
```python
freq = "D"
idx0 = pd.date_range("2000-01-01", freq=freq, periods=7).tolist()
idx0[0] = pd.Timestamp("2000-01-01 09:00:00")
series = pd.Series(index=idx0, data=np.arange(len(idx0), dtype=float))
series.asfreq(freq)
```
This results in the following timeseries:
```
2000-01-01 09:00:00    0.0
2000-01-02 09:00:00    NaN
2000-01-03 09:00:00    NaN
2000-01-04 09:00:00    NaN
2000-01-05 09:00:00    NaN
2000-01-06 09:00:00    NaN
Freq: D, dtype: float64
```
When I think we want something along these lines:
```
2000-01-01    0.0
2000-01-02    1.0
2000-01-03    2.0
2000-01-04    3.0
2000-01-05    4.0
2000-01-06    5.0
2000-01-07    6.0
Freq: D, dtype: float64
```

The following snippet is the fix I would propose:
```python
# build new equidistant index
idx = pd.date_range(series.index[0].floor(freq),
                    series.index[-1].ceil(freq),
                    freq=freq)
# get nearest index from original series
sample_idx = ps.utils.get_sample(series.index, idx)
# create a new equidistant series
s = pd.Series(index=idx, data=np.nan)
# fill new series with sampled data from original series
s.loc[idx[:sample_idx.size]] = series.loc[sample_idx].values
# trim any trailing nans
s = s.loc[s.first_valid_index():s.last_valid_index()]
```

**Comment by dbrakenhoff** [comment]
Another simpler option would be to just round the index, drop the resulting duplicates (if there are any) and then use `asfreq`.
```python
series.index = series.index.floor(freq)
series = series.drop_duplicates(keep="first", inplace=False).asfreq(freq)
```

The code is simpler, but you might end up losing a few datapoints.

**Comment by raoulcollenteur** [comment]
@dbrakenhoff can we close this issue now?

**Comment by dbrakenhoff** [comment]
Yes. It will automatically close with the next release I think, but I will close it manually now.
