### ISSUE TITLE
[ENHANCEMENT] both block and step response in plots.results

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#337]
Instead of choosing between the block and step response in plots.results, it would be nice if we could show both in the same graph, using a twinax.

`ml.plots.results(block_or_step="both)`

 Anyone keen to program that?

**Comment by rubencalje** [comment]
Ha, that would be nice, with two different y-axes. Right now we plot the block-response on a logarithmic x-axis and the step-response on a linear x-axis. We have to choose one if we plot both in the same graph (two x-axis will confuse people). If we choose linear, the block-response  is glued to the y-axis on the left. If we choose logatimic the step-reponse will look strange.  Which one do you prefer? I guess I prefer logaritmic...

**Comment by raoulcollenteur** [comment]
Ah yes I meant twin y-axes. Logarithmic would make sense as well I think for the y-axis.

**Comment by martinvonk** [comment]
I had a look at this but I think we should not want this. The implementation would always be either ugly or illogical.

The option `block_or_step` in `plots.results()` is used to call the function `get_response(block_or_step)` which is elegant. Using `block_or_step = "both"` would disturb this and require a lot of additional code. 

If we don't mind this the next problem arrises, namely the allignment of the two y-axis. The grid (and ticks) for both y-axis don't overlap. So to do fix this we would need to scale one y-axis such that it alligns with the other y-axis. However this gives ugly ticks with lots of decimals. 

If we then still want this... we have to think about how to attribute the correct y-axis to either the step or block response. This (probably) means we need to give the y-axis the same color as the line, which is also ugly.

**Comment by rubencalje** [comment]
I agree with Martin
