### ISSUE TITLE
scipy.signal.oaconvolve instead of fftconvolve?

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#340]
`oaconvolve` is reportedly 'much' faster than `fftconvolve` when one array is much larger than the other.

worth investigating.

**Comment by raoulcollenteur** [comment]
I did some simple %timeits on ml.simulate() for both example.py and example_well.py. No real differences, or fftconvolve is faster. But perhaps someone gets different results.

**Comment by mbakker7** [comment]
Thanks for trying. I suggested it, because I thought we meet the criteria
listed in the doc string of `oaconvolve`.
But if it doesn't give an improvement we can simply close this issue.
