### ISSUE TITLE
Feature Addition: EMD decomposition with IMF significance testing

### ISSUE THREAD

**Issue by oshin94** [pastas/pastas#342]
EMD decomposition is a very robust method for non-parametric time series analysis and is especially useful for hydrological data. Although libraries exist which can decompose time-series into their respective IMF components and residue, I could not find a single library anywhere on the internet, python or Matlab, where I could perform the test for determining statistical information content in the decomposed components. 

I want to contribute towards the project by adding the feature to test for the statistical information content in IMF components of Empirical Mode Decomposition.
The methodology was proposed by Zhaohua Wu, & Huang, N. E. (2004) in their paper, "A study of the characteristics of white noise using the empirical mode decomposition method" and has been established as an effective method to analyse trends especially for hydrological time series.
link: Original Paper
link: statistical test for trend identification

Additional context
Kindly let me know if this feature is in line with the aim of this project and if I may raise a PR for this.

**Comment by raoulcollenteur** [comment]
Hi @oshin94, thanks for your interest in contributing to Pastas! Do you have any studies where these methods are applied in a hydrological context? The links don't seem to work, could you add these? I'll have a look at the article as well and get back to you.

Cheers,
Raoul

**Comment by oshin94** [comment]
> Hi @oshin94, thanks for your interest in contributing to Pastas! Do you have any studies where these methods are applied in a hydrological context? The links don't seem to work, could you add these? I'll have a look at the article as well and get back to you.
> 
> Cheers, Raoul

Sorry for the error.. Please find the links below..
Original paper: https://www.jstor.org/stable/4143111
Statistical test for trend identification: https://doi.org/10.1016/j.jhydrol.2013.12.039

**Comment by oshin94** [comment]
@raoulcollenteur Any update?

**Comment by raoulcollenteur** [comment]
Dear @oshin94. I'm sorry for not getting back to you. I hope you found an alternative way to make your code for EMD decomposition publicly available. For now I think this method is outside of the scope of this package. Perhaps you could add this to stats models or similar work that has a bit broader scope.

Again, sorry for taking so much time to respond .

All the best,
Raoul
