### ISSUE TITLE
[BUG] simulation contains NaNs in period w missing data but residuals can be calculated for this period

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#348]
**Describe the bug**
This is a bit of an edge case that should generally not occur if you provide your timeseries settings. 

When you add a StressModel with a timeseries that starts after the start of your calibration period, and do not provide any settings (containing the filling logic for missing data), the model simulation will contain NaNs. This makes sense, because the model cannot calculate the contribution of this stress in the period with no data. Pastas also prints a warning that this is the case. The funky thing is that the results image shows that the there are residuals in that period...

See the example below. The simulation is plotted starting in 2005, but the residuals can apparently be calculated before that time.

![bug](https://user-images.githubusercontent.com/6552225/143888595-88a5bd57-acd3-419b-895b-b0f84d8d4a4d.png)

The reason this is possible is because of the interpolation of the simulation to the observation timestamps. The period before 2005 is missing from the simulation series so it uses the first simulation value to backfill the missing period. That allows it to calculate residuals for this period. 

This bit of code that does this is in `models.py -> residuals()` (line 430):

```python
sim_interpolated = np.interp(oseries_calib.index.asi8, 
                             sim.index.asi8, sim.values)
```
A maybe logical fix would be to set extrapolation to np.nan (see below), but this causes some trouble when calculating fit statistics. That issue can probably be fixed as well, but wanted to check what the desired solution would be before going down that route. 

```python
sim_interpolated = np.interp(oseries_calib.index.asi8, 
                             sim.index.asi8, sim.values,
                             left=np.nan, right=np.nan)
```

**Expected behavior**
If you can't calculate the simulation in a period with missing data (because there is no filling logic for missing data), then you shouldn't be able to calculate the residuals either. 

**Python package version**
```
Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
Numpy version: 1.21.2
Scipy version: 1.7.1
Pandas version: 1.3.3
Pastas version: 0.19.0b
Matplotlib version: 3.4.3
```

**Comment by raoulcollenteur** [comment]
~~@dbrakenhoff , is this Issue not related to the changes documented in #459 and solved in PR #459 ? If so, perhaps we can close this issue?~~

On second thought, However, as @rubencalje noted nans can come from many different errors, so throwing an Error when this happens seems appropriate. Then, I see that in [this commit](https://github.com/pastas/pastas/commit/e3e6c149ce4cdac24b249d4f93a601f65817a0e0) you did that ? So we could still close the issue?

**Comment by dbrakenhoff** [comment]
I think i reverted that commit later. I think this needs another quick look after #459 is merged.

**Comment by raoulcollenteur** [comment]
@dbrakenhoff did you have a quick look at this one by any chance? Do you have an example to test this? Would be nice to close or fix this issue before 1.0.

**Comment by dbrakenhoff** [comment]
Steps to reproduce:
- Create a model with heads from 1980 - 2020, and precipitation from 2000, and not passing any settings to the StressModel. 
- This results in residuals being calculated based on the extrapolation of the simulation, so residuals in the period 1980-2000 are based on the first simulation value. This is weird.

To solve, either we need the tmin to be set differently (since the stress cannot be extended to the oseries tmin), or we just need to throw an error that simulating heads when the stress is partly available and no extending settings are provided.

Example:

```python
import pastas as ps
import numpy as np
import pandas as pd

random_seed = np.random.RandomState(12345)

# function to generate some heads
def generate_synthetic_heads(
    input, rfunc, params, sigma_n=0.1, alpha=2.0, const=10.0, noise="none"
):
    # Generate the head
    step = rfunc.block(params, cutoff=0.9999)

    h = const * np.ones(len(input) + step.size)
    
    for i in range(len(input)):
        h[i : i + step.size] += input[i] * step
    
    head = pd.Series(
        index=input.index,
        data=h[: len(input)],
    )

    # add random (uncorrelated) noise
    if noise == "random":
        residuals = random_seed.normal(0, 1, len(head)) * sigma_n
        head = head + residuals
    
    # add correlated noise AR(1)
    elif noise == "correlated":
        delt = (head.index[1:] - head.index[:-1]).values / pd.Timedelta("1d")
        noise = sigma_n * np.random.randn(len(head))
        residuals = np.zeros_like(noise)
        residuals[0] = noise[0]
        for i in range(1, head.index.size):
            residuals[i] = np.exp(-delt[i - 1] / alpha) * residuals[i - 1] + noise[i]
        head = head + residuals

    return head

# Read in some data
prec = pd.read_csv("../../doc/examples/data/rain_260.csv", index_col=[0], parse_dates=True).squeeze() * 1e-3

# response function
rfunc = ps.Exponential()
params = [5.0, 10.0]
constant = 10.0

head = generate_synthetic_heads(prec, rfunc, params, const=constant, noise="none")

# select precipitation data from 2000
prec_2000 = prec.loc["2000":]

# create model
ml = ps.Model(head)
sm = ps.StressModel(prec_2000, rfunc=rfunc, name="prec")  # <- no settings provided
ml.add_stressmodel(sm)
ml.solve()
ml.plots.results()
```

**Comment by dbrakenhoff** [comment]
@raoulcollenteur I reverted that commit, but I'm for reintroducing that error without the other changes. I'll submit a PR.

**Comment by raoulcollenteur** [comment]
Closing issue after merging PR #526. Behaviour is now either prevented or a informative error is thrown.
