### ISSUE TITLE
Visualization of cross-correlation between timeseries

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#350]
use pastas CCF
test for timeseries with different time resolutions
test for non-equidistant timesteps

**Comment by dbrakenhoff** [comment]
Linked to https://github.com/pastas/pastas/issues/350, implement as plugin, see https://github.com/pastas/pastas/pull/657

**Comment by raoulcollenteur** [comment]
I would propose close this issue as won't fix or merge with #352. But if people want this I think the code is there (e.g., ccf) and this is simple to do anyway.

**Comment by dbrakenhoff** [comment]
Closing this issue. Further developments will be posted in #730.

**Comment by dbrakenhoff** [comment]
Closing in favor of #352.
