### ISSUE TITLE
Add methods for PACF calculation and plot

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#352]
Add methods to calculate and visualize partial autocorrelation function.
Use statsmodels implementation I think? Add as optional dependency.
Check for equidistant timeseries prior to calculation.

Test performance with get_equidistant_timeseries()...? Perhaps consider if binning applied in pastas ACF can be used to get something resembling an equidistant timeseries on which PACF can be calculated?

**Comment by dbrakenhoff** [comment]
optional dependency statsmodels, add ps.stats.pacf()

**Comment by raoulcollenteur** [comment]
I came across this post if you're interested in interpreting ACF/PACF. https://towardsdatascience.com/interpreting-acf-and-pacf-plots-for-time-series-forecasting-af0d6db4061c

But to add to this thread. I would propose to not implement something that is in statsmodels, also not as an optional dependency. The only reason I did this for the ACF is that the ACF implementation can deal with irregular time series. This would be hard to implement for the PACF. 

 I suspect only few users will use it, and users that will can simply import the pacf function. 

If you agree @dbrakenhoff, feel free to close this issue :)

**Comment by raoulcollenteur** [comment]
@dbrakenhoff checkin in on this issue. You still intend to work on this / use PACF or should we close it?

**Comment by dbrakenhoff** [comment]
This has become part looking into cross-correlation between time series related to #350. See let's keep it open for now, and we can discuss what we want to do with it as a part of that.

**Comment by dbrakenhoff** [comment]
Linked to #350, implement as plugin, see #657
