### ISSUE TITLE
ValueError when creating diagnostics plot

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#356]
Can be reproduced with many datasets. Example:

```
data = pd.read_csv('https://raw.githubusercontent.com/pastas/test-datasets/main/vanderspek_bakker_2017/B09B0124_DE-KOOG.csv', index_col=0, parse_dates=True, sep=";").loc["1980":]
head = data.iloc[:,0]
prec = data.iloc[:,1].dropna() # m/d
evap = data.iloc[:,2].dropna() # m/d
#
ml = ps.Model(head.dropna(), noisemodel=noise)
sm = ps.RechargeModel(prec, evap, rfunc=ps.rfunc.Gamma)
ml.add_stressmodel(sm)
ml.solve(noise=False, tmin="1990", tmax="2005")
```
`ml.plots.diagnostics()` now gives:
```ValueError: ACF result is empty. Check input arguments for calculating acf!```

Plot is created when decreasing number of points: `ml.plots.diagnostics(acf_options={'min_obs':20})`

Solution: maybe try a smarter approach to set `min_obs` and definitely give a better error message.

**Comment by raoulcollenteur** [comment]
Changed the default value of min_obs to 20, and changed the message to:

> The computed autocorrelation function has no values. Changing the input arguments ('acf_options') for calculating ACF may help.

**Comment by raoulcollenteur** [comment]
min_obs = 20 causes error and wrong ACF values in some cases

**Comment by raoulcollenteur** [comment]
Note to future self to report with an example. Have not had any problems for a while so I'll close this issue. It can be reopened if the issue comes up (again) and an example can be provided.
