### ISSUE TITLE
add classical GXG methods

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#36]
Sampling at 14 and 28th day of the month, using forward fill or linear interpolation.

I will try to implement these.

**Comment by rubencalje** [comment]
Nice! I wouldn't use any interpolation technique, as this smoothes out any peaks, but rather sample the series. In the model class there is the sample method, in which you can sample a series at a pre-defined index, while keeping the original data (so it only throws away excess timestamps).
