### ISSUE TITLE
Deprecate StressModel2 in v0.21.0, remove in v0.23.0

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#363]
As discussed StressModel2 can be deprecated in v0.20.0

**Comment by raoulcollenteur** [comment]
@rubencalje any progress on this? :)

**Comment by raoulcollenteur** [comment]
Add warning to the current version. Planning to deprecate in 0.21.0 and totally removed in v0.22.0.

**Comment by rubencalje** [comment]
> @rubencalje any progress on this? :)

Sorry for my late reply. Thanks for taking care of this. I just made a commit with some minor improvements (9e42405c6451769c304c7c1c1c536664cbd5aea2). Shall we close the issue when StressModel2 is removed?

**Comment by raoulcollenteur** [comment]
For future reference. pas-files which still contain a StressModel2 instead of the newer RechargeModel can be updated to the new code using Pastas 0.22.0, by loading and saving the file again.

ml = pt.io.load('old_file.pas'). # StressModel2
ml.to_file('new_file.pas'). # updated to RechargModel.

**Comment by mbakker7** [comment]
The error message is now `AttributeError: module 'pastas' has no attribute 'StressModel2'`
That is not helpful. In my opinion it needs to throw an error message to use RechargeModel (as the old deprecation warning was).

**Comment by raoulcollenteur** [comment]
What was the code you used to get this Error? Pastas should not be loading StressModel2 at all.

Or is this an old python script and you did:` ps.StresModel2`?

**Comment by mbakker7** [comment]
I did `ps.StressModel2`
That should throw an informative error message.

**Comment by raoulcollenteur** [comment]
I will add an empty StressModel2 class that raises an informative error message.
