### ISSUE TITLE
consider using pytest instead of nosetests

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#37]
My test file runs with pytest. Better and more up-to-date compared with nosetests, in my opinion. Up to you!

**Comment by raoulcollenteur** [comment]
Super late reply but I didn't see the need yet. However, I just tested with pytest and would say I also prefer it. Color coding and actually returning the values in assertions makes debugging the tests much easier! Thanks for the tip, will implement it in the next release!
