### ISSUE TITLE
[ENHANCEMENT] Add script to execute all notebooks at once for Pastas releases

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#384]
I now need to execute all the notebooks individually to ensure the docs are updated with each new release. This needs to be automated to save time.

**Comment by rubencalje** [comment]
I think I can solve this. Notebooks will be run automatically by nbsphinx when they contain no output. A problem will be that the notebooks will be run from the docs-directory, and therefore will not be able to find the data files that are used in the example-notebooks. I cannot find a solution for this with the current location of the notebooks.

Therefore I propose the following solution:
1 Remove all output from the notebooks. This will also make version control more clear
2 Move the notebooks from pastas\examples\notebooks to pastas\doc\examples
3 Remove the nblink-files in pastas\doc\examples as they are not needed anymore

As the notebooks will not contain any output anymore, moving the notebooks from the example-directory is reasonable I think. We can put a README.rst in the pastas\examples\ directory with a link to the readthedocs-page, where notebooks with output are shown.

Agree?

**Comment by martinvonk** [comment]
I came across this article yesterday on storing notebooks without the uneccesary metadata. This way notebooks can be stored normally on GitHub. Maybe it could be useful for this issue as well? It looks promising but I have not tested the method (nbdev2) myself yet.

Article: [The Jupyter+git problem is now solved! Written 25 Aug 2022 by Jeremy Howard](https://www.fast.ai/2022/08/25/jupyter-git)

**Comment by rubencalje** [comment]
Sounds interesting, have quickly read it, I think it may require everybody to change the way they commit changes to notebooks. Saving the notebooks without output is simpler though, and will already be a great improvement to the existing setup.

**Comment by rubencalje** [comment]
All notebooks are now run automatically for each pull request and commmit.
