### ISSUE TITLE
[BUG] ValueError in `ml.fit_report()` when running pytest

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#386]
**Describe the bug**
This odd error in `ml.fit_report()` came to light in the pastastore testing. When running the tests the following error arose for one specific test in which `ml.solve()` was called: `ValueError: Sign not allowed in string format specifier`. When you run the code normally the error does not occur, it only happens (so far) when running it via pytest. 

The error is caused by the calculated length of a piece of the error report turning negative. It happens in the following bit of code:
https://github.com/pastas/pastas/blob/63ddc6bb5eb906907247c514f07aca01fd0611b3/pastas/model.py#L1558-L1565

This length `wspace` turns negative because the calculated total width of the fit report is smaller than the constituent parts that are hard-coded. The total width is calculated here:
https://github.com/pastas/pastas/blob/63ddc6bb5eb906907247c514f07aca01fd0611b3/pastas/model.py#L1545

In this specific case, one of the calculated uncertainties in the parameters dataframe is a huge number. This causes the `parameters.__str__()` method to truncate the pandas output, showing only the first and last columns and an ellipsis `...` in between. The total width of the parameter table is calculated based on this truncated output, and a much smaller number than should be the case. This causes problems later on, as described above. This does not occur locally because the `parameter.__str__()` method uses the width of the current console to determine whether to truncate output or not, which apparently was not necessary locally. 

The solution is to either use a method to calculate the width that does not truncate output based on the width of the console. Perhaps `parameters.to_string()`? Or to set a minimum total width that is at least larger than the sum of the constituent parts. Or perhaps both.

The total width should be at least 40 + the length of the AIC/BIC with precision 2. So 50 should be fine usually. 

**To Reproduce**
I was able to eventually reproduce it locally by reproducing the Github CI environment locally, and running pytest. Or see [here](https://github.com/pastas/pastastore/runs/5745841197?check_suite_focus=true#step:8:400).

**Expected behavior**
No error.

**Python package version**
Numpy version: 1.21.2
Scipy version: 1.8.0
Pandas version: 1.3.3
Pastas version: 0.21.0b
Matplotlib version: 3.5.1

**Comment by raoulcollenteur** [comment]
@dbrakenhoff is this not fixes by your commit?

**Comment by dbrakenhoff** [comment]
Yeah, it should be fixed!
