### ISSUE TITLE
use Pandas methods in model

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#39]
Hi,

I have created a branch in which some methods of the model class are partly replaced by existing pandas fuctions, see dev-model in my fork. I think it makes the code a bit more compact and (just slightly) faster. 

If you see the changes and like them, I can make a pull request.

**Comment by raoulcollenteur** [comment]
Hi Tom,

Great. I have also been working on some performance issues last week so happy to see some more work there. I just created a new branch ("performance") to collaborate on this goal. Can you create a pull request from your branch to the new performance branch?

**Comment by tomvansteijn** [comment]
I will finish the doc strings and make a pull request.
