### ISSUE TITLE
[BUG] Stress model disregarding settings of passed TimeSeries objects

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#397]
**Describe the bug**
Also came up in #394.

If `ps.TimeSeries` objects with user-specified settings are passed to RechargeModel these are subsequently ignored and the defaults ("prec", "evap") are used. This can be solved by also providing the settings to RechargeModel, but it would be nice if this was taken care of automatically, since all the information is contained within the TimeSeries objects. 

**To Reproduce**
```
psettings = {'sample_up': 'divide',
 'sample_down': 'mean',
 'fill_nan': 0.0,
 'fill_before': 'mean',
 'fill_after': 'mean'}
pseries = ps.TimeSeries(prec, name='precip', settings=psettings)
rm = ps.RechargeModel(pseries, evap)
print(rm.prec.settings)  # note the difference with pseries.settings
```

**Expected behavior**
Use TimeSeries settings if TimeSeries objects are passed, else fall back to defaults. 

**Python package version**
```
Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
Numpy version: 1.21.2
Scipy version: 1.8.1
Pandas version: 1.4.2
Pastas version: 0.21.0b
Matplotlib version: 3.5.1
```

**Comment by dbrakenhoff** [comment]
Check other stressmodels for behavior and priority between StressModel settings and TimeSeries settings

**Comment by raoulcollenteur** [comment]
I checked this issue, and there are actually more stress models with this behaviour (e.g., StressModel2. WellModel, TarsoModel). Everywhere where the 'settings' argument of a stressmodel is not None. The settings provided by the stress model settings argument determines the settings. 

It actually seems hard to accommodate allowing both setting TimeSeries settings when creating a TimeSeries object, and when creating a Stress model. Moreover, it is not very transparant for users (see issue #408 by @mbakker7).

Given that TimeSeries are actually only used internally, the easiest solution would be to only accept Pandas Series as input for stress models, and internally transform these to TimeSeries objects, not exposing users to them at all. Then the place to provide settings for the stresses would then be the stress models and nowhere else.

Additionally, after removing the read methods (issue #407), I think this would make sense, and make a lot of things much easier to teach and understand to new users.

Thoughts?

**Comment by raoulcollenteur** [comment]
TimeSeries objects are very important to how we save the models and settings, so option 2 would probably be better for now.

**Comment by dbrakenhoff** [comment]
+1 for option 2

I agree that most users should use pandas to read timeseries (and potentially metadata), then provide those directly to the StressModels, optionally passing metadata and the "settings". When settings is None, perhaps a warning is a good idea to indicate that extending/resampling of the timeseries will not be possible?

In the internal discussion at Artesia we agreed the TimeSeries objects aren't used directly very often, and we rarely use the resampling functionality, but changing that part is quite rigorous so that's something to investigate at a later stage. So we're okay making the TimeSeries object more an internal thing. Having the metadata stored in the model is nice though, as it can give you some extra information about the timeseries in the model. Not a critical feature, but I'd personally vote for somehow keeping that functionality.

**Comment by mbakker7** [comment]
I read the discussion, but it is not entirety clear what "option 2" is. Can
you summarize?

**Comment by raoulcollenteur** [comment]
I think this issue can be closed with a "wontfix" label @dbrakenhoff. As the new code will not allow users to provide TimeSeries objects to stress models anymore, this issue can not arise anymore.
