### ISSUE TITLE
[ENHANCEMENT] Calculate all fit metrics with pastas.stats.metrics

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#402]
There are some places in the code (e.g. plots.py) where fit metrics are calculated without using the `pastas.stats.metrics` library. To make sure the metrics are consistent this should be enhanced by always calculating fit metrics using `pastas.stats.metrics`.

**Additional context**
This problem arose in PR #401.
@dbrakenhoff:  _This predates the changes to the metrics, they used to be calculated in the model methods, which could not be accessed with the callback in solve. But there is no reason not to change it now, so good idea to open a new issue._

**Comment by raoulcollenteur** [comment]
Closing after last PR. Thanks!
