### ISSUE TITLE
[Development] export all time series from Pastas model

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#404]
**Describe the proposed feature**
Add a method to export all the time series from a Pastas Model to a single pandas DataFrame. This could then be used to export the results to a csv or excel, using regular pandas methods. Helps to share modeling results with others (and applications).

**Code to show the expected the behavior**

`df = ml.get_all_series(tmin, tmax)   # df is a pandas DataFrame`

**Comment by dbrakenhoff** [comment]
I once added an export method to pastastore to export timeseries to csv files (for sharing with others). See code [here](https://github.com/pastas/pastastore/blob/d252b94ef3884d3b39f5f6a6932513166fec8fff/pastastore/store.py#L731-L781). Figured I'd mention it since this functionality sounds similar.
