### ISSUE TITLE
[ENHANCEMENT] Remove pastas.read module entirely

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#407]
**Describe the proposed enhancement**
Add deprecation warnings

**Additional context**
Link to hydropandas for read methods.

**Comment by raoulcollenteur** [comment]
Closing Issue as per last PR #417 from @OnnoEbbens . Thanks!!

**Comment by raoulcollenteur** [comment]
Re-opening this issue to document the removal of this module better.. 

- [ ] Read module gives warnings in pastas 0.22.
- [ ] Read module gives errors in pastas 0.23 (all code within the method can be removed, only raising errors code remains)
- [ ] Read module is removed in pastas 1.0 (entered folder is removed)

For future reference, @OnnoEbbens where can we find the new functions, can you post a link to Hydropandas here?

**Comment by raoulcollenteur** [comment]
After merging  #470 the only thing left to do is to remove the the module entirely for Pastas 1.0. Updated the milestone accordingly.

**Comment by raoulcollenteur** [comment]
Closing issue as completed after merging PR #494.
