### ISSUE TITLE
squeeze=True is deprecated in pandas

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#414]
The use of `squeeze=True` when reading a csv file in Pandas is deprecated (I am running Pandas 1.4.2). 
Should be replaced by `.squeeze()`. Pandas doc of `.squeeze()`: DataFrames with a single column or a single row are squeezed to a Series.

Should be fixed in all examples and all notebooks and the pandas requirement should be bumped. Not sure to what number, but 1.4.2 works.

**Comment by raoulcollenteur** [comment]
Fixed by PR #416
