### ISSUE TITLE
meanstress in StressModel contains confusion function

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#419]
In StressModel.init, the meanstress is computed as:

        if meanstress is None:
            meanstress = stress.series.std()

Why is that? The it should either be called stdstress rather than meanstress. Or the name remains `meanstress` and the `mean` function is called rather than the `std`.

**Comment by rubencalje** [comment]
This was changed by me a few years ago, after an offline discussion. A time series model is influenced by the changes of a stress, and less by the absolute value of a stress. For example, when the stress is the air pressure or a river level, the absolute value of the stress-series is not so important, but the variation is. Therefore I think the standard deviation of the series is a better quantification of the influence of the stress on the head than the mean.

I agree that the name meanstress can be confusing, but one could argue that the real stress is the change in values of the stress-series, and the mean of this stress can be represented by the standard deviation of this series.

We could change the name to stdstress, but we need to make sure this is backwards compatible, as meanstress is stored in pas-files I think.

**Comment by mbakker7** [comment]
I suggest to call it `scalefac` for scalefactor. Then when it is set for each stress clearly document what is used for the scalefactor (as is probably obvious from the computation of the scale factor).

**Comment by raoulcollenteur** [comment]
what about `gain_scale_factor` to be more explicit? It's a bit long but given how not often users will provide it, that won't hurt most users. 

To-do-list
- [ ] Change self.meanstress attribute in rfuncs
- [ ] Change keyword in stressmodels and rfunc. 
- [ ] Deal with pas- files

**Comment by mbakker7** [comment]
is fine. as long as the code is clear about the way it is scaled (mean, std, ...)

**Comment by raoulcollenteur** [comment]
Fixed this issue in PR #483. No problems with backward compatibility as the use is really limited, and pas-files did not even store it.

**Comment by raoulcollenteur** [comment]
`meanstress` was changed to `gain_scale_factor`. Providing `meanstress` produces a warning. This should be entirely removed for Pastas 1.0. Updating the milestone accordingly.

**Comment by raoulcollenteur** [comment]
Closing after merging https://github.com/pastas/pastas/pull/504
