### ISSUE TITLE
Solve with other frequency

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#42]
I was trying to solve a model with a different frequency, but found out this does not work yet/anymore. However, the simulate, residuals etc all support this already. Would be a nice feature to be able to solve with different frequencies.

**Comment by rubencalje** [comment]
What do you mean by: this does not work? And what do you mean by different frequency? Different than daily? In example_menyanthes.py a model is made with a weekly frequency, that still 'works'. Or do you mean that you want to be able to change the frequency of an existing model? Than we have to decide how we are going to downscale/upscale the stress-series. Maybe we can pass pandas methods to the tseries objects for that...

**Comment by raoulcollenteur** [comment]
This is possible from version 0.9.3 onwards. Issue closed
