### ISSUE TITLE
Features that will be changed/deprecated for version 1.0 [Development]

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#421]
1. All stressmodels will only accept equidistant Pandas time series only (either a series or dataframe with one column). 
2. Stressmodels will only accept instance of response function (#360)
3. solve method will only accept instance of solver class (#479)
4. (Dutch) weather data and head data can not be read from inside Pastas. Functionality is available in HydroPandas.
5. StressModel2 will be removed.
6. argument `meanstress` to `gain_scale_factor` (#419)

To assist with #3, there will be helper functions to validate series
StressModel will still have functionality to fill NaN values and to extend series backward (warmup) or forward depending on the settings. The settings will be clearly documented.
Current TimeSeries metadata will be stored elsewhere.

**Comment by raoulcollenteur** [comment]
Check-list for things to remove in Pastas 1.0 (please change if you find something)

- [ ] warn bounds in ml.fit_report
