### ISSUE TITLE
Remove Linear instance initialization of RechargeModel

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#423]
**Describe the proposed enhancement**
Right now we create an an instance of the Linear class in the definition of RechargeModel:

https://github.com/pastas/pastas/blob/ec900ecec8e53e919d7bff1352a672d06fafc0d4/pastas/stressmodels.py#L851

During import of pastas this creates an instance of the Linear class (see for yourself by putting buggy code in `__init__` of `Linear `and then importing pastas). We should avoid this, as this causes a slightly slower import of pastas.

**Expected behavior**
We should change this code to `recharge=None` and the add the following to RechargeModel's `__init__`:
```
if recharge is None:
    recharge = Linear()
```

**Comment by mbakker7** [comment]
His is a good idea. Don't forget to also change the doc string.

**Comment by raoulcollenteur** [comment]
Good idea, PR coming up!

**Comment by raoulcollenteur** [comment]
This was implemented in PR #445 and is now in Pastas 0.22. Closing issue :)
