### ISSUE TITLE
[Development] Automated References and publications

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#435]
**Describe the proposed feature**
I propose to add a new way for referencing in the code, using a public Zotero group library to maintain the references. We can use the Zotero API and sphinxcontrib.bibtex to automatically reference everything and create reference lists. I just did this for Pyet and it works great. Saving lots of work in the future. The following two pages are added to the Documentation page:

- A references page, listing all literature throughout Pastas
- A publications page, listing all peer-reviewed articles using Pastas.

**Additional context**

[See pyet reference list here](https://pyet.readthedocs.io/en/dev/references.html)
[See beautiful referencing here](https://pyet.readthedocs.io/en/dev/api/generated/pyet.temperature.html#module-pyet.temperature)

**Comment by martinvonk** [comment]
Looks pretty neat!

Is there also a way to do this locally with a .bibtex file on GitHub, instead of an online Zotero library? Just to keep things in one place?

**Comment by raoulcollenteur** [comment]
Well, you can always download the bibtex file of course ;-) We could do it locally as well, but that makes updating a #$#%. Now you just add a reference or format it in Zotero, much easier to maintain and for others to contribute I think. We can keep a local bibtex file of course, but not sure who would ever edit the bibtex file directly instead of using a reference manager?

Zotero library will also support a few other things in the future.

**Comment by raoulcollenteur** [comment]
Intermediate sneak preview: https://pastas--436.org.readthedocs.build/en/436/publications.html

**Comment by raoulcollenteur** [comment]
Closing as per last PR #436.
