### ISSUE TITLE
[ENHANCEMENT] Add Python 3.11 support

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#452]
**Describe the proposed enhancement**

It would be great if Pastas 1.0 would support Python 3.11. As noted by @martinvonk Numba is not ready yet, but should be soon.

**Comment by dbrakenhoff** [comment]
Perhaps set 3.11 to allow failure for now?
- continue on error: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

**Comment by raoulcollenteur** [comment]
I'll just check up on Numba every now and then, this Issue: https://github.com/numba/numba/issues/8304

**Comment by martinvonk** [comment]
We'll remove Numba from the optional dependencies and add it as a full on dependency, since we follow Numba's dependencies one on one.

**Comment by martinvonk** [comment]
Since we now use Numba with a global setting, we could maybe add Python 3.11 support by setting the global to `False`?

**Comment by martinvonk** [comment]
> Since we now use Numba with a global setting, we could maybe add Python 3.11 support by setting the global to `False`?

Nevermind this comment, it won't work.

**Comment by martinvonk** [comment]
Release candidate for numba with Python v3.11 support: https://github.com/numba/numba/issues/8841

**Comment by martinvonk** [comment]
New Numba version released : https://github.com/numba/numba/releases/tag/0.57.0

So we should be good to go now. I already created a branch py311 for testing purposes https://github.com/pastas/pastas/tree/py311
