### ISSUE TITLE
[Development] Add impulse method to rfunc classes and improve docs

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#453]
**Describe the proposed feature**

@mbakker7 proposed to implement an `impulse` method for all rfuncs classes, and started implementing this. I create this Issue to record this progress and new feature development.

Additionally, It would perhaps be an idea to add the latex formula to a __repr__ function, such that printing the class would show thee impulse response function and keep everything in one place.

**Expected usage**

`ps.Gamma().impulse()`

**Additional context**

The reason for this change is that it is now not always entirely clear what the impulse response functions exactly is and how it looks from the code and related articles. It should be clear what 

1. the impulse and step response functions are from the code, 
2. and somewhere in the documentation.

**Comment by martinvonk** [comment]
Maybe we could use [latexify](https://github.com/google/latexify_py)? 

This way we can check the formula's easily like this:
![image](https://user-images.githubusercontent.com/66305055/211527020-94ae0ecd-62a9-404a-9e98-1c6f308b5c64.png)

**Comment by mbakker7** [comment]
That is a nice feature that I didn't know about.
Not sure it will work well with our format (parameter passing, etc).

**Comment by raoulcollenteur** [comment]
This feature was aded in #472, closing issue.
