### ISSUE TITLE
[ENHANCEMENT] GitHub linguist language deduction from Pascal to Python

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#454]
GitHub uses the [linguist ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-languages )library to determine the language of the repository. However since we moved the documentation (_Jupyter Notebook_) to the doc folder, GitHub now thinks we use _Pascal_ instead of _Python_

We could override this using https://github.com/github/linguist/blob/master/docs/overrides.md

Now the homepage looks like this with in the bottom right 93.8% Pascal. This influences GitHub search options.
![image](https://user-images.githubusercontent.com/66305055/211525789-bce1bfcd-49bd-4b32-bbd6-92b606cf5268.png)

**Comment by dbrakenhoff** [comment]
https://www.droidcon.com/2022/03/10/removing-noise-from-your-github-language-stats/

for ignoring specific filetypes

**Comment by martinvonk** [comment]
Closing issue since #456 is merged.
