### ISSUE TITLE
[ENHANCEMENT] Question: move running of notebooks to Github Actions instead of ReadtheDocs?

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#458]
I know we recently moved the running of notebooks to RTD, but I came across this action that allows Github Actions to run the notebooks which are then uploaded and picked up by RTD to write the docs: https://github.com/dfm/rtds-action . 

Advantage is it is more efficient since we test the notebooks anyway. Disadvantage is that it feels a bit more complicated. Just figured I'd put it out there.

I think I'm pro leaving it as it is until RTD becomes unhappy about running all our notebooks (either because of memory usage/timeouts, or difficult dependencies).

**Comment by raoulcollenteur** [comment]
Let's wait with this until RTD starts complaining :)

**Comment by raoulcollenteur** [comment]
I'll close this issue as wont fix. We can reopen if RTD starts complaining.
