### ISSUE TITLE
Bugs in tests of GXG values with pandas 0.20

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#46]
Most of the tests are now failing in Travis with pandas 0.20. @tomvansteijn, can youfigure out how to fix this? E.g. https://travis-ci.org/pastas/pastas/jobs/233972587

**Comment by tomvansteijn** [comment]
That’s odd, I will take a look.

Tom van Steijn MSc
Hydrologist
T +31 88 348 23 34 | M +31 6 54 24 50 79 | E tom.van.steijn@rhdhv.com<mailto:tom.van.steijn@rhdhv.com> | W www.royalhaskoningdhv.com<http://www.royalhaskoningdhv.com/>

**Comment by raoulcollenteur** [comment]
Hi Tom!
Any progress here? I am preparing a new release for next week and I would like to include these methods.
Cheers, Raoul

**Comment by raoulcollenteur** [comment]
Fixed per Pull #47 and commit #48.
