### ISSUE TITLE
[BUG] No plots in documentation

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#476]
I do not see any of the plots for the dev-branch in the documentation. For example, see:
https://pastas.readthedocs.io/en/dev/examples/01_basic_model.html

Did we change anything lately?

**Comment by raoulcollenteur** [comment]
Hmm, I changed a couple of small things so I'll have a look. One figure is shown here though, when using %matplotlib inline.. 

https://pastas.readthedocs.io/en/dev/concepts/pastas_timeseries.html

**Comment by mbakker7** [comment]
Yes, but https://pastas.readthedocs.io/en/dev/concepts/pastas_timeseries.html also has a number of errors...

**Comment by raoulcollenteur** [comment]
Fixed it! Closing issue.

**Comment by martinvonk** [comment]
https://github.com/pastas/pastas/commit/e09217f5500cc48b7af8dda16b1d00a5411c6b0a
