### ISSUE TITLE
[ENHANCEMENT] Solvers as instances instead of classes

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#479]
**Describe the proposed enhancement**

With the latest changes in 0.23.0b, users have to provide instances of classes virtually everywhere, except for the solver (e.g., `ps.Gamma()`, `ps.StressModel()`, `ps.rch.FlexModel()`, `ps.ThresholdTransform()`, `ps.NoiseModel()`). 

For consistency and ease of use, I propose to also change the way to how solvers are provided, to be instances. This has two advantages I think:

1. Pastas becomes entirely consistent in its expected behaviour, users provide instance. 
2. Users can provide additional arguments to the solver, which might be useful in the future.

A disadvantage is that the solver instance needs the Model instance, so the solver should be provided as below. 

**Expected behavior**

`solver = ps.LeastSquares(model=ml)
ml.solve(solver=solver)`

Anyone has any thoughts on this?

Raoul

**Comment by martinvonk** [comment]
I'm in favor of making the the solver an instance to make Pastas consistent. I can imagine that in the future arguments such as _maximum number of function evaluations_ can be parsed to the solver.

**Comment by mbakker7** [comment]
I agree that we should pass an instance, but the question is how to do that. 
I don't really like your suggestion.
First creating a solver with a model as input and then passing the solver to the model seems like a confusing circular operation. 

A solution is that the solver does not take the model as an input on initiation anymore. Instead, every solver has a `set_model` function that sets the model. Then the `solve` method of a model can simply set the model for the provided solver. In the code something like:
```
def solve(self, tmin=None, tmax=None, freq=None, warmup=None, noise=True,
        solver=None, report=True, initial=True, weights=None,
        fit_constant=True, **kwargs):

                # Store the solve instance
                if solver is None:
                    if self.fit is None:
                        self.fit = LeastSquares() # modify this line
                elif not issubclass(solver, self.fit.__class__): # not sure what this checks. what happens if this is False?
                    self.fit = solver() # modify this line
                self.fit.set_model(self) # add this line
```
BTW, I think `self.fit` to store the solver is a pretty cryptic name. Why not `self.solver`?

**Comment by martinvonk** [comment]
Agree with @mbakker7. I didn't notice that you have to parse the Model to the solver class the original suggestion of @raoulcollenteur. I'd only like it if 
`ml.solve(solver=ps.LeastSquares)` becomes `ml.solve(solver=ps.LeastSquares())`.

**Comment by raoulcollenteur** [comment]
I will prepare a PR will the suggested change as implement proposed by @mbakker7. 

ml.solve() will throw an DeprecationWarning when a class is provided.

Should be an easy change.

**Comment by raoulcollenteur** [comment]
keeping self.fit for now, this could be another issue and PR :)

**Comment by mbakker7** [comment]
I will submit an issue.

**Comment by raoulcollenteur** [comment]
Change made as per PR #487. Closing issue.
