### ISSUE TITLE
[Development] Static type checking and PEP 561 compliance

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#480]
**Describe the proposed feature**
Since v0.23.0 Pastas has implemented type hints. It would be nice to implement static type checking using `mypy` and make Pastas PEP [561 ](https://peps.python.org/pep-0561/) compliant. This improves the code quality and robustness. 

The downside I think is that this will be a lot of work (2days at least) because a lot of errors and issues will be raised by `mypy`. Also, Matplotlib, SciPy, Numba don't fully support type hinting, as that they are PEP [561](https://peps.python.org/pep-0561/) compliant. NumPy and Pandas are though, via `numpy.typing` and `pandas-stubs` respectively.

**Comment by martinvonk** [comment]
We probably should remove the types in Pastas for packages that are not PEP 561 compliant. So for instance, NumPy and Pandas are PEP 561 compliant, but Matplotlib and SciPy aren't. Currently in Pastas we use we use `FigureBase` and `_AxesBase` from Matplotlib to define the `Figure` and `Axes` types in Pastas. However, these types were only implemented from Matplotlib>v3.3. 

So to:
```
Axes = TypeVar("Axes", bound=_AxesBase)  # Matplotlib Axes
Figure = TypeVar("Figure", bound=FigureBase)  # Matplotlib Figure

```
should be redefined in pastas.typing.types to: 
```
Axes = TypeVar("Axes", bound=Any)  # Matplotlib Axes
Figure = TypeVar("Figure", bound=Any)  # Matplotlib Figure
```

or we should require Matplotlib>v3.3

**Comment by raoulcollenteur** [comment]
Should we drop this issue @martinvonk ? I don't think it is worth our time now..

**Comment by martinvonk** [comment]
It depends, we can also leave it open on low priority. 

I think static type checking would improve our code quality. However, it is a lot of work... Running mypy on our current code yields: `Found 2051 errors in 56 files (checked 69 source files)`

**Comment by mbakker7** [comment]
Won't fix for now. This doesn't cause any problems at the moment.
