### ISSUE TITLE
[Development] Editable install without setup.cfg

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#481]
**Describe the proposed enhancement**
Since setuptools >= 64.0 supports the installation of editable installs of pyproject.toml based builds (PEP [660](https://peps.python.org/pep-0660/)), there is no longer the need for an empty setup.cfg file. This means we can delete the setup.cfg file after checking if things still work the way it should. See https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml for more context.

**Comment by raoulcollenteur** [comment]
Closing after merging #490
