### ISSUE TITLE
[Development] Move custom configuration files to pyproject.toml

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#482]
**Describe the proposed feature**
Since Pastas v0.23.0 is a pyproject.toml based build, we can start moving configuration files  (e.g. [pytest.ini](https://docs.pytest.org/en/7.1.x/reference/customize.html)) inside of the pyproject.toml file. This is not necessary per se, but looks cleaner imo.

**Comment by raoulcollenteur** [comment]
any other files you want to move to toml?

**Comment by martinvonk** [comment]
Nope, we can only store other configuration files there so this is it. Closing with #490.
