### ISSUE TITLE
[ENHANCEMENT] Change self.fit to self.solver in Model class

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#488]
The `solver` is stored as `self.fit` in the `Model` class. It would probably be better if it is called `self.solver`.

**Comment by raoulcollenteur** [comment]
Yes, I think this would make sense. The change should be easy, and ml.fit could simply be a reference to ml.solver for a couple of versions. I will pick this one up.

**Comment by raoulcollenteur** [comment]
Working on this now. Quite easy but lots of code where self.fit or ml.fit was used 🥇

**Comment by raoulcollenteur** [comment]
Fixed as per PR #628.
