### ISSUE TITLE
[ENHANCEMENT] Create html repr for Model class (for Notebooks)

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#519]
**Describe the proposed enhancement**
I work with xarray sometimes and they have a really nice html repr to show a Dataset/DataArray in a notebook environment (https://github.com/pydata/xarray/issues/1627). The same goes for Pandas which has a html repr for the DataFrame class. I want to create a similar html repr for the Model class that nicely shows you the observations and other info. I have been working on this a bit in the [html_repr branch](https://github.com/pastas/pastas/tree/html_repr) but got a bit stuck since I don't know any html/css. This is how far I've got for a ml with 2 stressmodels:

**Expected behavior**
![image](https://user-images.githubusercontent.com/66305055/216326936-e8e3dfd4-5a12-426a-bec8-820908f286c1.png)
The menu's can be expanded and collapsed:
![image](https://user-images.githubusercontent.com/66305055/216327229-847c33ea-bc59-4826-a601-14d17ffb547b.png)

**Comment by raoulcollenteur** [comment]
Still want to do this @martinvonk or should we focus on other features and close this issue?

**Comment by martinvonk** [comment]
Yes still would be nice to have I think. @OnnoEbbens made it work for HydroPandas so maybe he can help..
