### ISSUE TITLE
tmin, tmax in ml.plot

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#53]
tmin and tmax can be specified in ml.plot, but tmin is ignored and the plot is drawn including the warmup period. It would be nice to have an easy option to plot the results for the tmin and tmax specified for ml.solve. Now you have to specify them for the solve and then again for the plot. Some kind of option: 'use tmin and tmax from the solution' (which are stored anyway, right?) would be nice.

Same holds for stats.evp. It would be nice to have an option to compute evp for the period used in solving.

**Comment by raoulcollenteur** [comment]
I updated the stats package to calculate all statistics available through ml.stats over the same period as the model is solved. This is done using a decorator, filling in tmin and tmax when they are None. The tmin and tmax from the model settings are used.

I will now look into a solution for the plots, but I think a similar solution or possibly even the same decorator woulds work.

**Comment by raoulcollenteur** [comment]
This should all work now with the latest commits. tmin and tmax are used from the model settings (which are stored from the solve options). This works for both the statistics and the plotting package. 

The warmup period is still included in the simulate method to obtain good results. We can decide to cut off the warmup period after simulating the time series so you don't see it when plotting..
