### ISSUE TITLE
[ENHANCEMENT] ml.solve(info=False)

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#533]
Add `info` as a keyword argument to the solve method to temporarily turn off the `info` statement during solve, similar to `report=False`.

**Comment by raoulcollenteur** [comment]
I like this idea. Here's some pseudocode for future implementation.

```
log_level = #get log level here
ps.set_log_level("ERROR")
#do solve
ps.set_log_level(log_level)
```

**Comment by martinvonk** [comment]
Users can apply this workaround themselves:
```python
ps.set_log_level("ERROR")
ml.solve()
ps.set_log_level("INFO")
```
