### ISSUE TITLE
[ENHANCEMENT] Replace StressModel with same name

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#538]
Right now, when a StressModel is added with the same name as an existing StressModel, it is not added and an INFO statement is given. I think it may be better to replace the existing StressModel (and still throw an INFO statement). This would be in line with what Flopy does.

**Comment by raoulcollenteur** [comment]
This is already possible by using `replace=True` as an additional argument to ml.`add_stressmodel`. 

So I think wha you are proposing is to set the default to True. I can imagine this is desired, but I should perhaps come with a warning level statement.

**Comment by mbakker7** [comment]
My suggestion is indeed to make replace=True the default. I think an INFO statement would be good enough, not a warning. Then again, not sure what the exact diff is between info and warning.

**Comment by raoulcollenteur** [comment]
Done! Closing issue.
