### ISSUE TITLE
[DEVELOPMENT] Add statement about support on paid code development

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#547]
We should document somewhere how to deal with code that is developed as part of a paid assignment (e.g., like the acf function I developed in the past). So company "X" pays person "Y" to develop function "X" for Pastas, and the Pull Request needs to be handled by the developers team. In this case I think it is appropriate that the reviewer(s) of that code (the persons handling the PR), is compensated for the time spend on this PR. I think adding such a statement gives clarity if such a case arrises (which I expect will happen in the future).

Note, I do not suggest to do this for voluntary / academic PRs.

**Comment by mbakker7** [comment]
This is what Pandas has on their webpage: https://pandas.pydata.org/contribute.html

**Comment by martinvonk** [comment]
https://pastas.readthedocs.io/en/latest/developers/contributing.html
