### ISSUE TITLE
[ENHANCEMENT] Improve formatting of "stderr" throughout Pastas

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#549]
**Describe the proposed enhancement**

It commonly occurs that the stderr is shown as a huge number in the fit report and results plot. It would be great if we could format the string differently in these cases. 

**Expected behavior**

Normally formatted strings

**Additional context**

<img width="717" alt="Screenshot 2023-02-13 at 17 08 25" src="https://user-images.githubusercontent.com/12051167/218510327-5bbdcdcb-3fa9-4550-b705-984f28f8c686.png">

**Comment by martinvonk** [comment]
This is already build in in ml.plots.results() according to @dbrakenhoff so we can apply the same str formatting here.
