### ISSUE TITLE
[ENHANCEMENT] allow ffill and bfill as fill_before and fill_after options for time series

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#554]
**Describe the proposed enhancement**

Allow the following settings dictionary:

```python
    settings = {
        "sample_up": "interpolate",
        "sample_down": "mean",
        "fill_before": "bfill",  # <- new option
        "fill_after": "ffill",  # <- new option
        "fill_nan": "interpolate",
    }
```
I know this is the same as getting the first/last value from the timeseries and entering that into the settings dictionary for fill before/after, but I like not having to think about it :).  

When would you ever use this? 

I used it for a pumping test, where I used a reference head time series (with no pumping influence) as input for my time series models, that in some cases needed to be extended slightly into the past/future. In my case, extending the first/last values as fill values worked pretty well.

**Comment by raoulcollenteur** [comment]
Just merged the related PR #558, adding this option. Closing issue :)
