### ISSUE TITLE
Interpolation of oseries

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#56]
Figuring out how we deal with high-frequency oseries, meaning that the oseries have a higher frequency than the simulated series. Do we only compare the oseries on the indices wherethere are also simulations? Or do we interpolate the simulation to the indices of the oseries? I thought the last option..

Then, I think I would like an option where one can only compare to the oseries where there's also a simulation. Or be able to change the frequency of the oseries. Fitting high frequency observations is often difficult and suffers from high auto correlations..

**Comment by rubencalje** [comment]
We first sample the oseries to the simulation-times. In that way, we make sure that one simulation-timestep  is only compared to one observation, and not more. The observations closest to the simulation timesteps are kept. Then we interpolate the simulation to the observation-timesteps, if needed.

Mark added the interpolate_simulation attribute to the model. If you set this to False, interpolation is not used. Now I see that this attribute is overwitten in the initialize-method however... So it will not do anything.
