### ISSUE TITLE
[ENHANCEMENT] improve documentation of settings in StressModels

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#574]
The current description of settings in `ps.StressModel` is a bit vague for new users and refers to `pastas.Timeseries` for more information. I propose moving some of the `pastas.Timeseries.update_series` documentation to the StressModel docstring.

**Comment by raoulcollenteur** [comment]
Or duplicate it, perhaps we can construct the docstrings in a smart way by using a common strings throughout Pastas.

**Comment by dbrakenhoff** [comment]
Closed by #639.

Note: the docstring is copied a few times (that seemed simpler than programming something smart for now), so changes will have to be made in several spots if anything needs to be adjusted.
