### ISSUE TITLE
[ENHANCEMENT] improve validate_series checks and messages

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#577]
**Describe the proposed enhancement**

In a course a lot of users ran into their time series not being ready for pastas, I (and @martinvonk) think adding these checks would further help users along.

- Add an error and message specifically for multi-column DataFrames:
```python
# specific msg for multi-column DataFrame.
msg = "DataFrame with multiple columns. Please select one."
raise ValueError(msg)
```
- Add a check for NaT types in series.index
```python
# check if index contains NaNs
if s.index.hasnans:
    logger.info("The time series index contains NaNs. Try to remove these with `series.loc[series.index.dropna()]`.")
```

**Comment by martinvonk** [comment]
Goes wrong with this kind of csv:
```csv
date,level
2016-01-21 13:00,9.55
2016-01-21 14:00,9.55
2016-01-21 15:00,9.55
,
,
```

`series = pandas.read_csv(csv, index_col=0, parse_dates=True)`
`pastas.validate_stress(series)` raises:
`ValueError: The time-indices of series level are not monotonically increasing. Try to use `series.sort_index()` to fix it.`
