### ISSUE TITLE
[ENHANCEMENT] Mention normalizing surface water levels in example notebook.

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#584]
**Describe the proposed enhancement**
Currently, in the example notebook on surface water levels there is no mention of normalizing surface water levels. This is only done (shortly) in the calibration notebook.

**Comment by raoulcollenteur** [comment]
You still want to do this? Would be a quick PR so we can close this issue..

**Comment by raoulcollenteur** [comment]
Fixed by last PR #668 . Thanks Martin!
