### ISSUE TITLE
[BUG] issue with autocorrelation notebook `Series.append` is deprecated

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#585]
**Describe the bug**
Autocorrelation notebook is causing tests to fail. It uses deprecated `Series.append` methods. Replace with `pd.concat()`.

**Comment by martinvonk** [comment]
fixed with: https://github.com/pastas/pastas/pull/578/commits/d341fb1a5f4c6fe6e79e77c0d3256aef8e71286b
