### ISSUE TITLE
Removed RTD docs build as required status check for PRs 

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#590]
RTD is complaining about setup.py. See message below. This is preventing us from merging PRs, so I (temporarily) removed the RTD status check for PRs.

```
Collecting future (from uncertainties>=3.1.4->lmfit>=1.0.0->pastas==1.0.1)
  Downloading future-0.18.3.tar.gz (840 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 260.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
```

We can log any progress on this issue here.

**Comment by martinvonk** [comment]
https://github.com/dfm/rtds-action

**Comment by dbrakenhoff** [comment]
We tried getting GH actions to run the notebooks and upload the results which theoretically should be picked up by RTD to build the documentation, but no luck getting it work thus far.

See https://github.com/dfm/rtds-action/issues/17 for more info.

**Comment by dbrakenhoff** [comment]
This issue can be closed, it's all working again, and I reinstated the RTD status check. We can reopen this issue if we ever want to explore using GH Actions to generate notebook output for the documentation.
