### ISSUE TITLE
[BUG] Pastas 1.0.1 requires matplotlib >= 3.4

### ISSUE THREAD

**Issue by AnneDeGraaf** [pastas/pastas#598]
**Describe the bug**
When importing pastas 1.0.1 with matplotlib version < 3.4 an ImportError is raised for FigureBase.
`"ImportError: cannot import name 'FigureBase' from 'matplotlib.figure'"`

The `FigureBase` class was added in matplotlib version 3.4 ([release notes](https://matplotlib.org/3.6.3/api/prev_api_changes/api_changes_3.4.0.html#figurebase-class-added-and-figure-class-made-a-child))

**To Reproduce**
install pastas==1.0.1, matplotlib<3.4
`import pastas`

**Expected behavior**
-

**Screenshots**
-

**Python package version**
 - pastas==1.0.1
 - matplotlib==3.2.1

**Additional context**
-

**Comment by raoulcollenteur** [comment]
Hi @AnneDeGraaf , Thanks for reporting! I think we encountered this issue somewhere else as well.

@dbrakenhoff , shall we push the minimum dependency for MPL to 3.4 for Pastas 1.1.0?

**Comment by martinvonk** [comment]
Hi @AnneDeGraaf,

Thanks for the issue. It was also reported here: https://github.com/pastas/pastas/issues/480#issuecomment-1422701493 and fixed by pull request: https://github.com/pastas/pastas/pull/553 so you don't need Matplotlib >= 3.4 anymore.
