### ISSUE TITLE
[ENHANCEMENT] Throw warning if recharge flux looks like m/d

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#609]
**Describe the proposed enhancement**

Throw a Warning when the recharge flux looks like it is in m/d, by resample to annual values and checking against some logical values.

**Expected behavior**

`ps.rch.FlexModel(rain, evaporation)`

>>> WARNING: prec looks like not provided in mm/d

**Comment by martinvonk** [comment]
`if prec.resample("A").sum().max() < 12:`

raises `ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

**Comment by raoulcollenteur** [comment]
This happens if a pandas 1D DataFrame is used as input for prec. Will change that line to use the self.prec.series to solve this.

**Comment by martinvonk** [comment]
Ty!
