### ISSUE TITLE
[BUG] Add link to license in readme

### ISSUE THREAD

**Issue by darigovresearch** [pastas/pastas#611]
**Describe the bug**
No link in readme

**To Reproduce**
Go to readme

**Expected behavior**
Thought it may be helpful/convenient to have a link to the license in the readme

**Screenshots**
na.

**Python package version**
na

**Additional context**
na

**Comment by raoulcollenteur** [comment]
This appears to be a bot as the same post was done in other repositories. Locking and closing conversation.
