### ISSUE TITLE
[ENHANCEMENT] plot WellModel step responses at given distances in `stackplot`

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#617]
**Describe the proposed enhancement**
Instead of plotting the step response at distance=1m, plot all step-responses for distances provided by WellModel in stackplot. 

`#Code to reproduce the behavior`
Something along these lines, i believe Marco has the actual implemented code somewhere.
```
# plot well step response(s)
params = sm.get_parameters(model=ml, istress=istress)
t = sm.rfunc.get_t(params, 1.0, cutoff=0.99)
step_i = sm.rfunc.step(params, cutoff=0.99)
axes[i, 1].plot(t, step_i, c=colordict[c[-1].name])
```

**Comment by raoulcollenteur** [comment]
Fixed as per #656. Closing Issue.
