### ISSUE TITLE
Order of columns of parameters dataframe changes

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#62]
The order of the model parameters  changes after creation, caused by pandas append method that order alphabetically. As a result, pmin is now shown after pmax, which I find confusing.  Should be solved somewhere in the get_init_parameters method.

**Comment by raoulcollenteur** [comment]
`parameters = parameters.append(sm.parameters, sort=False) `would fix it, but let's prevent the extra bit of code.

This issue will probably be fixed in Pandas itself in the next major release, so I'll let it be for now.
https://github.com/pandas-dev/pandas/issues/4588

**Comment by mbakker7** [comment]
Let's leave this open until it is fixed in pandas.

**Comment by raoulcollenteur** [comment]
Fixed the issue now and as Pandas 0.23 is now default this problem no longer exists. Closing the issue.
