### ISSUE TITLE
[BUG] Incorrect link to License in readme

### ISSUE THREAD

**Issue by darigovresearch** [pastas/pastas#622]
**Describe the bug**
Linked to issue https://github.com/pastas/pastas/issues/611, it appears to have been prematurely closed as the issue was not precise enough. The problem is that the badge links to a generic MIT license instead of the repositories license.

**To Reproduce**
Go to the readme and click on the badge

It goes to https://mit-license.org/

**Expected behavior**
Instead it should go to https://github.com/pastas/pastas/blob/master/LICENSE

**Screenshots**

![image](https://github.com/pastas/pastas/assets/30328618/9fa7da19-a3fe-4f02-8c7e-c81b40f91a7d)

**Python package version**
 - na

**Additional context**
Pull request https://github.com/pastas/pastas/pull/621 would resolve this issue

**Comment by raoulcollenteur** [comment]
See comment on #621. Closing.
