### ISSUE TITLE
[ENHANCEMENT] better error when passing rfunc class instead of instance

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#627]
**Describe the proposed enhancement**
Currently, when adding an rfunc class (old behavior) instead of an instance (new behavior), this is the error I get:

```python
TypeError: RfuncBase.update_rfunc_settings() missing 1 required positional argument: 'self'
```
Which I think is a bit confusing. We can probably add something a little more user friendly (for people with old code :))

**Comment by raoulcollenteur** [comment]
Fixed by PR #665 . Closing issue.
