### ISSUE TITLE
[BUG] wrong calculation of the duration_curve_slope

### ISSUE THREAD

**Issue by OnnoEbbens** [pastas/pastas#634]
The function `duration_curve_slope` in `ps.stats.signatures` calculates the duration curve between percentile l and u. There is a bug in the slicing of the series, now only values below the lower percentile are used instead of values between the lower and upper. This is easily fixed by changing:

`s = series[(series.quantile(l) > series) & (series < series.quantile(u))].sort_values()`

to
`
s = series[(series > series.quantile(l)) & (series < series.quantile(u))].sort_values()`

**Comment by raoulcollenteur** [comment]
This will be fixed in the signatures branch.
