### ISSUE TITLE
[DEVELOPMENT]Modify code for stressmodels without an rfunc

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#642]
In preparation of pastas plugins, we need to do some code refactoring so that stressmodels also work well without an rfunc. 
For example, when looking through the code, the rfunc._name is used sometimes, but if the stressmodel doesn't have an rfunc (i.e., `rfunc=None`) this doesn't work. Suggestion is to make sure to check whether an rfunc is not None first, although we don't want to do that all the time.

**Comment by mbakker7** [comment]
Right now, it is checked whether the name of the rfunc is a certain string. It would be better to check whether rfunc `isinstance` of the required rfunc class rather than check the name. In that case rfunc can be `None` and the code still runs. @dbrakenhoff  would that work for you? I think your code is the primary user of this syntax. Any objection to replacing 
```if rfunc._name == 'HantushWellModel'```
to
```if isinstance(rfunc, ps.HantushWellModel)```

**Comment by dbrakenhoff** [comment]
Good idea, I'll submit a PR with this change :+1:

**Comment by dbrakenhoff** [comment]
Fixed in #643
