### ISSUE TITLE
[BUG] Solver instance does not parse kwargs to solve method.

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#645]
**Describe the bug**
kwargs parsed to the solver are not parsed to the solve method.

**To Reproduce**

kwargs not parsed:
```python
solver = ps.LeastSquares(verbose=2)
ml.solve(solver=solver)
```

kwargs parsed:
```python
solver = ps.LeastSquares()
ml.solve(solver=solver, verbose=2)
```

**Comment by raoulcollenteur** [comment]
I am not sure this is a bug but more how it is designed to work. Only arguments that will change some kind of attribute to the Solvers are passed to the solver, the rest is passed through ml.solve. There is no information moving from the solver to ml.solve, only the other way around. Seems more a question on how-to use Pastas to me.

Why would you need the first option?

**Comment by martinvonk** [comment]
> the rest is passed through ml.solve.
This is not the case currently so that's why I made an issue. One would expect that the kwargs of the solver instance are parsed to the solve method.

I am fine with not making it an option to use the kwargs of the solver object, but then we should report that the kwargs of the solver are ignored / or remove it.

**Comment by raoulcollenteur** [comment]
> I am fine with not making it an option to use the kwargs of the solver object, but then we should report that the kwargs of the solver are ignored / or remove it.

I think this would be the best option, otherwise there are two options to pass the kwargs, which might confuse other users. **kwargs should probably not be removed though, as it might affect loading pas-files with old arguments (that are now ignored but do not cause errors). Looking at the Solvers, we might actually want to add doctoring for BaseSolver, LeastSquares , and LmFitSolve to prevent people from doing what you tried to do ;-)

**Comment by mbakker7** [comment]
I got lost in what the appropriate syntax is. 
I think it should be, as in the BaseSolver doc:
```
ml.solve(solver=ps.LeastSquares(solver settings))
```
Is that correct? What other ways are there that don't work?

**Comment by mbakker7** [comment]
Reading back the bug report, it sounds like this is what @martinvonk tried to do and it doesn't work. 
I think this syntax should work and the other syntax shouldn't. Similar to the syntax for `rfunc`-s
So it should be:
```
ml.solve(solver=ps.LeastSquares(solver settings))
```
Any other option should get a deprecation warning.

**Comment by raoulcollenteur** [comment]
I do not think that this is what we want, except for anything that should be an attribute of an instance. With how it is currently implemented all the arguments from least_squares in scipy can be used dynamically. e.g., you can use:

`ml.solve(solver=ps.LeastSquares())`

and then

`ml.solve(jac="3-point")  # which use the same solver now.`

The proposed solutions would require you to make a new solver instance for every argument passed to the underlying solver methods (these are methods not instances..).

`ml.solve(solver=ps.LeastSquares())`

 and then 

`ml.solve(solver=ps.LeastSquares(jac="3-point"))`

The **kwargs in the Solver init methods were never meant to do what Martin tried. This is unlike the kwargs of ml.solve where the documentation clearly states:

```
**kwargs: dict, optional
    All keyword arguments will be passed onto minimization method from the
    solver. It depends on the solver used which arguments can be used.
```

**Comment by mbakker7** [comment]
I am confused, as I think we do pass arguments to an `rfunc` instance this way. 
Let's discuss at our next Pastas meeting and then report back here.

**Comment by mbakker7** [comment]
The suggestion of @martinvonk is indeed more consistent with the way an Refunc is specified. One of the other potential problems that has not been mentioned is that it can make it difficult to store models. So the conclusion is to throw a warning with information how to do it correctly.

**Comment by raoulcollenteur** [comment]
Closing issue after merging #646. An error is now thrown.
