### ISSUE TITLE
[DEVELOPMENT] Add (synthetic) test datasets

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#673]
**Describe the proposed feature**

I would love to have some (synthetic) test dataset available directly in the pastas package. 

**Expected usage**

Unsure how it should look, perhaps: 

```
df = pastas.datasets.vonk_2024   # synthetic data from Martin
df = pastas.datasets.collenteur_2021  # irregular time steps from my 2021 article in groundwater
```

**Additional context**

Other datasets welcome.. but we need to restrict somehow.

**Comment by raoulcollenteur** [comment]
I had a look at seaborn and they have:

1) a function load_dataset in the package
2) a separate GH repo with the data as csv

I think this would also work well for us. 

df = ps.load_dataset("vonk_2024")

Then the question become, what does df look like? Is it just the heads or also the stresses? If the latter, then the DF could be a pandas DataFrame with a multicolumn with the first colomn row ["oseries", "stresses"].

I'll start making some code suggestions in the new 'dataset' branch

**Comment by dbrakenhoff** [comment]
If we go the load dataset route, I'd vote for separating the oseries and stresses into 2 data frames and returning a dictionary with the two. That way it's also easy to add a new dataset to the dictionary and make explicit what it contains.

**Comment by raoulcollenteur** [comment]
Good idea, I'll try and implement it like that over the next couple of weeks.

**Comment by raoulcollenteur** [comment]
I implemented a first version, see the PR and the repository. Still need to update the csv files in vonk_2024 with a changed header.

What do all think? I kinda like it as it is now, simple and effective. In the future we might store all the example data there, but let's see about that.
