### ISSUE TITLE
TimeSeries object with no freq-original

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#68]
When the frequency of a TimeSeries cannot be inferred and is not user-provided, unexpected things can happen when updating the settings / series. This becomes visible when changing the frequency, and resampling automatically switches to the "sample_weighted" method in the "change_frequency" method of the TimeSeries method.

**Bottomline:** it should be possible to change oseries with no freq_original from Hourly values to daily values and use the "drop" option for dropping nan-values.

**Comment by rubencalje** [comment]
I have been looking into this today. I wanted to make a new issue, but then I found this one.

I think we should simplify the resampling methods. Right now we have a sample_up method and a sample_down method, which are chosen based on the frequency and the 'sample_up' setting and 'sample_down' setting. Right now these settings are only used when freq_original could be set. If not, the timestep_weighted_average method is used, which is slow (more on that later).

I think we should replace the 'sample_up' setting and the 'sample_down' setting by a 'resample' setting. The only possible values for the resample method I can think of are:

- 'timestep weighted average'
- 'interpolate'
- 'drop'

I think the default setting should be 'timestep weighted average'. Behind the scenes we can still use the sample_up and sample_down methods for series with a fixed frequency (with a freq_original), to speed things up. For series that we do now know the frequency of, we then use the timestep_weighted_average method. Right now the timestep_weighted_average is quite slow (thanks to a for loop over all timesteps), but I have some code that can do this 50 times faster (not committed yet).

Any thoughts?

**Comment by raoulcollenteur** [comment]
This issue was actually created for the case of the dependent time series the `oseries`. I think what you are describing is how to deal with stresses right? This would be quite a different thing i my opinion.

In the ideal case, the frequency for any user-provided stress used in Pastas should be known, as this is explicitly required for the convolution to work. In this case, timestep_weighted_resample should never be necessary.

I always try not to provide any stresses to Pastas where the freq_original is not automatically detected or provided by me through the freq_original keyword of the TimeSeries object. If I see timestep_weighted_resample is used I go back and fix the problem in my original time series, because apparently that stress is wrong.

The problem I see most with the proposed is that it will be hard for the user to detect the actual problem: incorrect stresses are provided! In fact, I would be in favour of raising an error when Pastas cannot detect the frequency of the stress, and asking the user to resample it somehow. We could provide the timestep_weighted_resample as a method in utils.py for users to pre-process their stresses to make it a constant frequency.

I actually think this would be much easier to understand for new users.

**Comment by rubencalje** [comment]
One of the reasons we have the resample methods is so that the user does not have to supply stresses with a fixed frequency. I can for example think of a stress-series of a well with yearly, monthly and then daily values. It would ask a lot from the user to resample this stress himself. We discussed this, and decided Pastas should be able to handle such input. The method you developed, that stores the series_original, is ideal for this.

The user sees a info-message that freq_original cannot be determined, just like he sees now. He cannot set freq_original, as there is no fixed frequency. If he does, unexpected things can happen, based on the timesteps, the value of freq_orginal and the simulation frequency. The only right way of making an equidistant series would be a timestep weighted algorithm. If freq_original is known, the current sample_up (bfill) and sample_down (mean) methods would be used.

**Comment by raoulcollenteur** [comment]
> One of the reasons we have the resample methods is so that the user does not have to supply stresses with a fixed frequency.

I think the main reason is that users can change the frequency (or time step) of the simulation in the `solve`-method and pastas handles the transformation of the stress series internally when a different frequency is chosen. However, this is always a constant frequency so the transformation should be fast and easy.

I agree that in your example the timestep_weighted_resample method is the way to go. But in essence this only has to be done once right? So it would be an ideal preprocessing method. Then we can require all stresses to have a constant frequency which is much clearer to (future/novice) users I think. The syntax could be like this:
```
# Make series equidistant
well = pd.read_csv(well.csv)
sm = ps.StressModel(well)
>>> Error: stress is not equidistant. Provide a equidistant stress. For example, use 
    ps.util.timestep_weigted_resample to do this

well_new = ps.util.timestep_weigted_resample(well) # Returns an equidistant series
sm = ps.StressModel(well_new .....)
```

I think the above process is much cleaner and a user has full control. It also makes programming on our end a little easier.

**Comment by mbakker7** [comment]
What I think you guys propose is:

Ruben: Try to determine frequency and if that doesn't succeed use 'timestep
weighted' interpolation.
Raoul: Try to determine frequency and if that doesn't work, throw an error
and provide a utility so that the user can interpolate the series with
'timestep weighted' interpolation on their own and then try again.

If I understood that correctly, then I am siding with Ruben. Why not do it
automatically i.o. suggesting they do it on their own? We can make a
keyword input argument that tells Pastas to convert automatically when
needed and still throw an error when users (=Raoul) opt out.

Mark

**Comment by raoulcollenteur** [comment]
> Why not do it automatically i.o. suggesting they do it on their own? 

The main issue for me is that anything we do internally to fix a problem with irregular time series is very intransparent to the user and is hard to take control of. timestep_wieghted resampling only works for wells series in a specific format I think. If we brute-force timestep-weighted resample to other series you get some weird results, for example for:
- when a rainfall/evaporation series has nan-values when it didn't precipitate/evaporate (needs fill_na=0)
- with waterlevel series where values are only recorded when they change (needs bfill)

Providing methods to make a stress regular is much more transparant and easier to control in my opinion.

Providing a keyword-argument would be an option. We would have to add that to each stressmodel for it to be accessible to the user, cause the TimeSeries objects are generally never accessed by the users.

**Comment by rubencalje** [comment]
Ok, I see the point of Raoul. But the waterlevel example (where values are only recorded when they change) is a great example of a irregular series that we should be able to handle. When the user would have to resample this series himself, there will always be loss of information.

What I do not like about the current setup:

- there is a sample_up setting and a sample_down setting. I think they are linked, and are both determined by the type of series. Therefore I would like to replace them by one resample-setting.
- when freq_original cannot be determined, these settings are ignored and timestep_weighted_resampling is always used. It would be better if the user can still choose the resampling method, even if freq_original cannot be determined.

We can better inform the user of what is happening to the series I think. In this info-message (or a warning) we should let the user know that pastas will be faster if he supplies equidistant series.

Maybe I can propose something that we can all agree on. I will think about it, and make a pull request somewhere this summer.

**Comment by raoulcollenteur** [comment]
As resampling non-equidistant/irregular **oseries time series** will now be a pre-processing step for the users I will close this issue.
