### ISSUE TITLE
[BUG] ml._get_output_series() fails when TARSO is used as a stress

### ISSUE THREAD

**Issue by AviadAvr** [pastas/pastas#681]
When calling for .get_output_series() I get the following TypeError:
`TarsoModel.simulate() got an unexpected keyword argument 'istress'`

```
ml = ps.Model(oseries)
rch = ps.RechargeModel(precip, evap, name='recharge', rfunc=ps.Gamma())
ml.add_stressmodel(rch)
tarso = ps.TarsoModel(precip, evap, oseries=oseries, name='tarso')
ml.add_stressmodel(tarso)
ml.solve(solver=ps.LeastSquares(), freq='h', noise=False, report=True)
pastasmodel = ml.get_output_series()
```

.get_output_series() returns a dataframe with the oseries, simulation and recharge series. I'm not sure whether it's possible to estimate a recharge series for TARSO (?), but if not, it should be removed/ignored from this function.

![image](https://github.com/pastas/pastas/assets/124437932/1be9c413-2cea-4d05-8d7c-d8c4d09757b6)

**Python package version**
Python version: 3.11.5
Pastas version: 1.3.0

Cheers!

**Comment by rubencalje** [comment]
This indeed is a bug we need to solve. The influence of TarsoModel on the head cannot (yet?) be split in an influence of precipitation and evaporation. I will add `self.nsplit = 1` in the `__init__` of TarsoModel. Until then you can change the last line to `ml.get_output_series(split=False)`.

However, there are some comments on your question:

- `get_output_series()` never returns the recharge-series, it returns the influence of the stressmodels (for example recharge) on the head (among other things). You can get the recharge flux with the line `ml.get_stress('tarso')`. This is simply the precipitation minus  the evaporation times the evaporation_factor (precip - evap * tarso_f).
- `TarsoModel` cannot be combined with a constant, other stressmodels or a transform (you should have seen some warnings). Therefore your code should look like:
```
ml = ps.Model(oseries, constant=False)
tarso = ps.TarsoModel(precip, evap, oseries=oseries, name="tarso")
ml.add_stressmodel(tarso)
ml.solve(solver=ps.LeastSquares(), freq="h", noise=False, report=True)
pastasmodel = ml.get_output_series(split=False)
```

So with `constant=False`, without the `ps.RechargeModel`, and with `split=False`.

**Comment by AviadAvr** [comment]
@rubencalje thanks for the advice and comments.
I guess I still need to understand a bit more about the differences between adding a threshold transform and using tarso.
