### ISSUE TITLE
Notebook Fixating parameters while fitting does not show how to fix parameters

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#685]
It seems that the wrong notebook is posted under that heading as it contains no example of how to fix a parameter of a model.
(If such a notebook exists, it may be better to call it 'fixing' parameters rather than 'fixating' parameters. "Fixate" -> "cause (someone) to develop an attachment to someone or something".

**Comment by raoulcollenteur** [comment]
Actually the right notebook was there, but there was no header where the parameters were fixed. I updated the name of the notebook and the notebook to better show where the parameters are fixed. Closing issue.
