### ISSUE TITLE
[BUG] Equations not showing correctly in documentation

### ISSUE THREAD

**Issue by HenrikSpa** [pastas/pastas#698]
The equations in the documentation (https://pastas.readthedocs.io/en/master/benchmarks/check_response_functions.html) are shown as:

$ \theta(t) = \frac{4N}{\pi S} \sum_{n=1,3,5…}^\infty \left( \frac{1}{n} \exp{\left( {-n^2\frac{\pi^2T}{SL^2} t} \right)} \sin \left(\frac{n\pi x}{L}\right) \right) $

They do however show using this link instead:
https://github.com/pastas/pastas/blob/master/doc/benchmarks/check_response_functions.ipynb

**Comment by raoulcollenteur** [comment]
Hi @HenrikSpa,

We just fixed this in PR #695. Check out the development version of the docs here:

https://pastas.readthedocs.io/en/dev/benchmarks/check_response_functions.html

Closing issue :)

Cheers,
Raoul

**Comment by HenrikSpa** [comment]
Great!
