### ISSUE TITLE
fix future warning from pandas

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#72]
/Users/mark/git/pastas/pastas/stressmodels.py:298: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  h = h.loc[tindex]

**Comment by raoulcollenteur** [comment]
This was fixed by changing the way we deal with indices now, creating them from tmin, tmax and freq or form the stress index. Also 'h=h.loc[tindex] is no longer used. Should this come up again it must now be a bug in the code, not a compatibility issue
