### ISSUE TITLE
Add cache=True to ps.load_dataset

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#721]
A caching option should be added to the load-dataset method, because GH doesn't like it this way. GH Actions sometime fails now, so the tests should also be removed and only be executes when the master branch is updated.

**Comment by martinvonk** [comment]
Can't we refer to the raw file ? Something like:
```python
import pandas as pd

def pastas.load_datasset(name: Literal["collenteur_2021", "collenteur_2023", "vonk_2024"]) -> DataFrame:
   if name =collenteur_2021:
      urls = https://raw.githubusercontent.com/pastas/pastas-data/main/collenteur_2021/irregular_timesteps.csv
   elif ...
      ...
   return pd.read_csv(url, index_col=0, parse_dates=True)

```

**Comment by raoulcollenteur** [comment]
No the problem is the download from GitHub, you can get the error: Exception: Error: 403. Reason: rate limit exceeded.

Which happened here: https://github.com/pastas/pastas/actions/runs/8541433512/job/23400748923

**Comment by raoulcollenteur** [comment]
Fixed by @martinvonk . Closing issue!
