### ISSUE TITLE
[ENHANCEMENT] Add Ruff as linter and formatter

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#726]
**Describe the proposed enhancement**
Add Ruff as linter

To do:
- [ ] Can `flake8` be removed as linter?
- [ ] Can `black` be removed as formatter?
- [ ] Can `isort` be removed as formatter?
- [ ] Check if we can use github precommit such that each commit is automatically formatted.

**Comment by martinvonk** [comment]
https://github.com/astral-sh/ruff-pre-commit

**Comment by raoulcollenteur** [comment]
Fixed as per #759
