### ISSUE TITLE
Rename NoiseModel to AR1Model?

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#728]
**Describe the proposed enhancement**
I think the name of the `NoiseModel` class is a bit vague and since we are going to explicitly add a noise model to the time series model using the `add_noisemodel()` method #678; maybe we should rename the `NoiseModel` class to `AR1Model`. This way you know what kind of noise model is added to the time series model. This is in line with the `ArmaModel` where the name gives an indication what kind of noise model is used.

This can be quickly done for now by `AR1Model = NoiseModel` in the noisemodel.py script and deprecate NoiseModel in a later version. I think now is the time to make this change if we want it. In later versions, we probably don't want to deprecate the name `NoiseModel` because it is called explicitly many times. 

Thoughts?

**Comment by mbakker7** [comment]
Howbout `AR1NoiseModel`? 
Since AR1 is also a regular (BJ) model and we don't want to confuse the user.

**Comment by martinvonk** [comment]
> Howbout `AR1NoiseModel`? 
> Since AR1 is also a regular (BJ) model and we don't want to confuse the user.

ArmaModel is also a regular (BJ) model so do you suggest to rename that to ArmaNoiseModel as well?

**Comment by mbakker7** [comment]
I think that is a good idea. Not sure what the other developers think.

**Comment by martinvonk** [comment]
I now named:
```
NoiseModel -> ARNoiseModel
ArmaModel -> ARMANoiseModel
```
I did not choose the name AR1NoiseModel because the ARMANoiseModel should then be named ARMA11NoiseModel. 
Everybody okay with with CAPS for `ARMA` and `AR`?

**Comment by martinvonk** [comment]
After discussion in the end chose for 
`NoiseModel` -> `ArNoiseModel`
`ArmaModel` -> `ArmaNoiseModel`


Merged #732 in #678
