### ISSUE TITLE
settings in Stressmodel should be easily accessible

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#73]
Right now it is very difficult to find out what the pre-defined settings are for Stressmodels. They are defined in TimeSeries and can only be seen by looking at the code, as far as I know.

**Comment by raoulcollenteur** [comment]
On the[ documentation website ](http://pastas.readthedocs.io/en/latest/examples/2_TimeSeries_objects.html) I suggested the following routine for now:

`ps.TimeSeries._predefined_settings`

Would it be better to be able to acces them like ps.timeseries_settings? Or is the above enough and should it be documented better?

Adding to this, the ps.TimeSeries._predefined_settings dict does not include all keywords anymore, which is confusing.

**Comment by raoulcollenteur** [comment]
Also, the settings are applied to the TimeSeries, and not to the stressmodels...

**Comment by mbakker7** [comment]
You are right that the `settings` are applied to the `TimeSeries`, but they are specified by the user when creating a `StressModel`. I really think the documentation of `StressModel` should list the different options, even if that means copying the code.

**Comment by mbakker7** [comment]
I think there should be a `ps.settings` of `ps.timeseries_settings` dictionary, similar to the rcParams in matplotlib. That way the user can `print(ps.timeseries_settings)` to see al the settings. We can add that to the documentation of the `StressModel` classes. Thoughts?

**Comment by Hugovdberg** [comment]
I'm not exactly certain how this dictionary is used, but if the settings are only used on creating the `TimeSeries` and not by reference then I think the name of the dictionary should make clear it are the default settings.

**Comment by mbakker7** [comment]
The problem is that they can not be accessed by the user, while the user
does need to specify a setting. So the user should know what values are in
the dictionary.

**Comment by raoulcollenteur** [comment]
Finally got to work on this, I just added a ps.rcParams as suggested by @mbakker7. The default time series settings are now accessed as:

`ps.rcParams["timeseries"]`

the following also still works:

`ps.TimeSeries._predefined_settings`

But is just a copy of the above. 

Another thing, I am wondering if it makes sense to add a `ml.get_stressmodel_settings("rch")` method to obtain the settings that are actually applied, thoughts?

**Comment by mbakker7** [comment]
A ml.get_stressmodel_settings("rch")  would be very helpful, as it is now
rather difficult to get the pre-defined settings for a specific type. Or
even to know what settings there are (suggestion: if
ml.get_stressmodel_settings() is given w/o an argument, it returns a list
of all the different pre-defined settings, like 'rch', 'wel', etc.

**Comment by raoulcollenteur** [comment]
Time series settings of stress models are now accessible as:

`ml.get_stressmodel_settings("rch") `

and the predefined settings as:

`ps.rcParams["timeseries"]`

I think that should close this Issue ?

**Comment by mbakker7** [comment]
Yep. Assuming there is an example Notebook showing this?
