### ISSUE TITLE
[BUG] behavior of `get_equidistant_series_nearest()` changed 

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#738]
From the notebook prepare_timeseries.ipynb, Example 1:

Result with pastas 1.0.1
![image](https://github.com/pastas/pastas/assets/6552225/ed896468-6d11-4cb2-82ac-491a9e72b5c5)

Result with current version of pastas:
![image](https://github.com/pastas/pastas/assets/6552225/02f62b3f-5641-4765-8595-5cf9470d5bab)

This last result is not what I intended, so this needs a look.

**Comment by raoulcollenteur** [comment]
Pandas version? :-p

**Comment by dbrakenhoff** [comment]
:100:%

**Comment by dbrakenhoff** [comment]
![image](https://github.com/pastas/pastas/assets/6552225/92910e1e-adeb-40d7-bb99-daaddc07898b)

**Comment by raoulcollenteur** [comment]
We can close this after #738 was merged right?
