### ISSUE TITLE
[ENHANCEMENT] Function to compute standard error of parameters

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#746]
In Pastas >1.5, the computed standard error of the parameters is not displayed anymore in the fit report. 
I understand that this is better, as the standard error is only a reasonable approximation of the standard deviation of the parameters when the model fulfills certain conditions. And some fitting routines may not even compute the standard error. 

However, when the user wants the standard errors (for example because they did a diagnostic check and the model fulfills all the conditions), it would be nice if there is a `Model.get_stderr` function to get the stderr. Similar to the `Model.get_parameters` function. 

Request: add `Model.get_stderr` function

**Comment by raoulcollenteur** [comment]
I think the stderr should still be available from the ml.parameters attribute, would that work as well?

**Comment by dbrakenhoff** [comment]
Get stderr from parameter dataframe when you need it.
