### ISSUE TITLE
quantile GXG functions do not use tmin and tmax arguments

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#75]
Statistics functions q_ghg, q_glg, q_gvg do not use the optional  arguments tmin and tmax.

Add indexing using .loc?

**Comment by raoulcollenteur** [comment]
Yes, this is something that still needs to be implemented. I added tmin and tmax for all statistics so they could all be called with tmin and tmax but didn't have time to implement it everywhere yet.

I think .loc is the way to go 👍
