### ISSUE TITLE
calculate quantile GXG stats by year

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#77]
The current timeseries statistics functions q_ghg, q_gvg and q_glg take a quantile of the whole series. The classic definition is better approximated by taking the average of quantiles per year. Proposing to implement this using Pandas resample.

**Comment by tomvansteijn** [comment]
Can do a pull request if you agree with this modification. I cannot think of scenario where the quantile of the whole series would be preferred for gxg statistics. Anyhow this is easy to do outside pastas.

**Comment by rubencalje** [comment]
I can think of a lot of scenario's where I would like a quantile of the whole series, but I have not used the q_gxg functions jet. Maybe you can implement it as an option to do it by year, which is on by default?

**Comment by tomvansteijn** [comment]
Good idea. Created see pull request #78

**Comment by rubencalje** [comment]
Great! Pull request is approved.
