### ISSUE TITLE
[BUG] ACF calculation raises 'division by zero'

### ISSUE THREAD

**Issue by AviadAvr** [pastas/pastas#771]
**Describe the bug**
Calculating the autocorrelation function of certain timeseries raises the `division by zero` error.
The error seems to be caused by lines 178-179 in core.py:
```
 if isinstance(lags, int) and bin_method == "regular":
    lags = arange(int(dt_mu), lags + 1, int(dt_mu), dtype=float)
```
 Where if `dt_mu` is a `float`, it is converted to the `int` 0.
 
 Perhaps an easy fix would be:
```
if int(dt_mu) == 0:
    dt_mu = 1 # Prevent division by zero error
```
 
**To Reproduce**
```
import pandas as pd
import pastas as ps

head_path = "" #insert path name to head_test.csv
head = pd.read_csv(head_path)
head.index = pd.to_datetime(head["timestamp"])
head = head.drop(columns="timestamp")

meteo_path = "" #insert path name to meteo_test.csv
meteo = pd.read_csv(meteo_path)
meteo.index = pd.to_datetime(meteo["timestamp"])
meteo = meteo.drop(columns="timestamp")

ml = ps.Model(head.obs)
rch = ps.RechargeModel(meteo.precip, meteo.evap)
ml.add_stressmodel(rch)
ml.solve(freq="h")

residuals = ml.residuals()
acf = ps.stats.acf(residuals)
```

**Python package version**
```
Python version: 3.11.5
NumPy version: 1.26.2
Pandas version: 2.2.2
SciPy version: 1.11.4
Matplotlib version: 3.7.1
Numba version: 0.58.1
LMfit version: Not Installed
Latexify version: Not Installed
Pastas version: 1.5.0
```
**Timeseries**
[head_test.csv](https://github.com/user-attachments/files/15788156/head_test.csv)
[meteo_test.csv](https://github.com/user-attachments/files/15788157/meteo_test.csv)

**Comment by raoulcollenteur** [comment]
Hi @AviadAvr, thanks for reporting. Which version of Pastas are you using? I can't find the code you are referring to in core.py of v1.5.0 (https://github.com/pastas/pastas/blob/v1.5.0/pastas/stats/core.py).

**Comment by AviadAvr** [comment]
> Hi @AviadAvr, thanks for reporting. Which version of Pastas are you using? I can't find the code you are referring to in core.py of v1.5.0 (https://github.com/pastas/pastas/blob/v1.5.0/pastas/stats/core.py).

Hi @raoulcollenteur, sorry for the mix up. I was accidentaly referring to some debugging code i added. The lines causing the issue are 178-179 (editted the post).

**Comment by raoulcollenteur** [comment]
Thanks @AviadAvr ,I see now. I think your solution will work. Do you want to make a PR with the suggested change ? :)

Cheers,
Raoul

**Comment by raoulcollenteur** [comment]
Closing issue after merging #774. Thanks @AviadAvr !
