### ISSUE TITLE
[BUG]Response function notebook doesn't show equations for response functions anymore on readthedoc

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#775]
The notebook https://pastas.readthedocs.io/latest/userguide/response_functions.html doesn't show the mathematical equations for the different response functions anymore. Maybe because latexify is not present?

**Comment by martinvonk** [comment]
Equations look fine now again in #786

**Comment by martinvonk** [comment]
Looks fine on the dev branch: https://pastas.readthedocs.io/dev/benchmarks/check_response_functions.html
