### ISSUE TITLE
[ENHANCEMENT]`ml.plot` does not accept `grid=True`

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#780]
`ml.plot` accepts `figsize=(L, W)`, but not other standard keyword arguments that `pandas` accepts, like `grid=True`.

Desired behavior: pass all keyword arguments to the `pandas` plotting function.

**Comment by raoulcollenteur** [comment]
Not to the matplotlib axes? Also, one may provide a `ax` argument, so one way to do this right now is:

```
fig, ax = plt.subplots(1,1, figsize=(L,W))
ml.plot(ax=ax)
ax.grid()
```

or also:

```
ax = ml.plot()
ax.grid()
```

**Comment by mbakker7** [comment]
Thanks for the workaround. A simple
`ml.plot()`
`plt.grid()` 
works as well. But since `ml.plot` takes a `figsize`, I was wondering why it wouldn't take some other keyword arguments like `grid`, since I presume they are simply passed to `pandas`. For example:
`head = ml.simulate()`
`head.plot(grid=True)`
works, but
`ml.plot(grid=True)`
does not work.

**Comment by dbrakenhoff** [comment]
Kwargs are passed to `plt.subplots()` or `plt.figure()`, not the pandas methods.

**Comment by mbakker7** [comment]
ok. so won't fix.
