### ISSUE TITLE
Sanitize names of models and stress models

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#79]
User provided names could be checked for unwanted characters that cause troubles in other methods.

E.g. name="Test/456" causes troubles when using this name for writing files (pandas read_csv) and could be changed to:

name="Test_456".

**Comment by rubencalje** [comment]
I would prefer a warning then. Changing the name could break any linking between a pastas-model and any other data-source, and therefore can be very annoying to users.

**Comment by raoulcollenteur** [comment]
The model and stressmodel names should also not contain spaces when LmFit is used as it brakes the parameter naming. We could write a general method in utils.py that checks user provided names for characters that can cause troubles.

**Comment by raoulcollenteur** [comment]
Implemented the proposed method giving a warning in commit 91deb73. Closing this issue.
