### ISSUE TITLE
Frequency of dependent variable and the stresses

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#8]
It is now possible to change the frequency of the observed (dependent) and the independent (stress) series. But the implementation is still very experimental. 

**Changing the frequency**
Changing the frequency works fine for both series, but maybe a user option should be provided on how to resample. Now a forward fill method is standardly applied. Alternatively, a method could be written that uses only existing values and does not rely on interpolation.

The stress series now use the pandas .asfreq function, creating nan-values for each unobserved time index. These nan-values are later filled with user defined function.

**Simulating with different frequencies**
The simulation of the model works fine when only the frequency of the observed series is changed. When the frequency of the stress series is changed, the residuals result in occasional nan-values and optimisation fails. 

**TO DO**
- Write a new resample function for the observed series
- Figure out how to the frequency of the stress series can be changed without having nan-values in the residuals

**Comment by rubencalje** [comment]
Is partly solved. Is double with issue #42
