### ISSUE TITLE
warmup passed differently than tmin, tmax in solve

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#81]
when the warmup is specified when doing a solve, the value is passed to the residuals function differently than tmin and tmax. In fact, I don't quite know how it is passed, but a different value of the warmup does give a different solution, so it gets passed in some fashion. but it should probably be passed in a similar fashion to tmin and tmax.

**Comment by rubencalje** [comment]
Do you mean from line 641 in solve:

```
        if not self.settings['fit_constant']:
            # do this before setting oseries_calib to None
            self.normalize_residuals = False
            res = self.residuals(self.fit.optimal_params,
                                 self.settings['tmin'], self.settings['tmax'],
                                 self.settings["freq"])
```

This is only used when the constant is not fitted as a parameter. The warmup is indeed not in the arguments of the residuals method. It then uses the warmup from ml.settings. I will change this, by removing the tmin, tmax and freq arguments, as they are all used from ml.settings, which is the default behaviour of the residuals method anyway. So the code will become:

```
        if not self.settings['fit_constant']:
            # do this before setting oseries_calib to None
            self.normalize_residuals = False
            res = self.residuals(self.fit.optimal_params)
```

**Comment by mbakker7** [comment]
The signature of the `residuals` function is
```
        def residuals(self, parameters=None, tmin=None, tmax=None, freq=None,
                  warmup=None)
```
but when it is called from the `BaseSolve.minimize` function in called as
```
rv = model.residuals(parameters, tmin, tmax, freq)
```
This means that `warmup` is not passed to the `residuals` function through the `minimize` function. Yet the `Model.solve` method allows for the specification of a `warmup`. So that `warmup` is set differently than the `tmin`, `tmax`, and `freq`. Why is `warmup` not passed on? Or why are the others passed on?

**Comment by rubencalje** [comment]
The warmup gets passed to the residuals method through the settings of the model. Like tmin, tmax and freq it is set in the initialize-method, that is called in solve(). I would suggest we also remove the tmin, tmax and freq from the call to model.residuals, like:

`rv = model.residuals(parameters)`

And then also remove any reference to tmin, tmax, freq and warmup in the Solver-classes. They are stored in the model, so they do not have to be passed around.

**Comment by rubencalje** [comment]
I commited the proposed changes, by removing the references to tmin,tmax and freq in the Solver-classes (we should probably do the same for noiseweights, but this is not yet in the settings of the model). Everything still seems to function the same as before. Please revert the commit when this is not the case.

**Comment by mbakker7** [comment]
I really wanted to go the other way around: include warmup in solve like
the others.
I think it is a nice option in `solve` to be able to specify all these
things. How else would you try to fit on different periods? First setting
them in `model` and then solving seems to be strange. Or not?

**Comment by mbakker7** [comment]
Also, having tmin, tmax and all the others as options in `residuals` and
`noise` is really nice. Can you revert the change and include `warmup` like
the others?

**Comment by rubencalje** [comment]
tmin, tmax and all the others are still available in residuals and noise, and also in the solve-method of the model, where you can change the period or the frequncy. We just do not pass them to the solver classes directly anymore. The solver classes has arguments that belong to the solver, and the model class has arguments that belong to the model.

I think it is much clearer now, so I would rather not change it back again...

**Comment by raoulcollenteur** [comment]
Looks like it works right now. However, I thought about this a little more and I think we should add some other changes to this.

Right now we save the settings before doing anything (e.g solving). So it can happen that the user-provided settings doesn't work, and the setting is still being stored. The result is an error, and all the other methods of the Model stop working. We should either:

1: check if the user-provided setting is allowed and then store it
2. solve first (because then it works), and then store it

Thoughts?

Another minor thing is that the signatures of the simulate, residuals, noise and solve method are not consistent, similar arguments have different order in each method which is confusing.

**Comment by raoulcollenteur** [comment]
I think we can close this issue now right?
