### ISSUE TITLE
utils.get_time_offset fails when freq is None

### ISSUE THREAD

**Issue by tomvansteijn** [pastas/pastas#86]
Issue becomes apparent for example when a series contains only NaN. In this case freq cannot be inferred and is set to None.

`freq_is_None_series = pd.Series(index=pd.to_datetime(['2009-01-01', '2010-01-01']))`

**Comment by raoulcollenteur** [comment]
Hi Tom! I can see this going wrong. Before making any changes, why would one add a series containing NaNs? Do you have a specific use case or should we build something that warns the user?

**Comment by tomvansteijn** [comment]
I encountered the issue when reading a KNMI datafile with Pastas, just to process it as a dataframe. I do not need the time_offset for that.

Perhaps a warning is sufficient when get_time_offset fails in this step? Maybe the timeseries models should check whether each timeseries has a valid offset.

**Comment by rubencalje** [comment]
Hi Tom,

If you just want to read a knmi-file without using it in Pastas you can use
the KnmiStation class, using KnmiStation.fromfile classmethod. The
measurement data then is in KnmiStation.data, the variable information (if
present in the file) in KnmiStation.variables and the station information
in KnmiStation.stations. The read_knmi method can be used to use the
knmi-data in a Pastas StressModel.

Op vr 7 sep. 2018 14:32 schreef Tom van Steijn <notifications@github.com>:

**Comment by raoulcollenteur** [comment]
This method is now only used internally (I will change that in the docs) by the TimeSeries object for the fill_before and fill_after methods. These always provide a freq and the above case does not exist anymore.

Closing this issue.
