### ISSUE TITLE
initial value and vary can not be set on constant

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#87]
You can not set the initial value or vary (didn't try pmin and pmax) voor the constant, while this can be done for the noise model (which is also automatically generated). Example code:

```
import pandas as pd
import pastas as ps
dates = pd.date_range('1990', '1991')
ho = pd.Series(data=1, index=dates)
ml = ps.Model(ho)
ml.parameters
ml.set_initial('noise_alpha', 77)
ml.set_initial('constant_d', 33)
ml.set_vary('noise_alpha', False)
ml.set_vary('constant_d', False)
print(ml.parameters)
```

Note that for the parameter of the noise model the values have been changed, but not for the constant.

**Comment by raoulcollenteur** [comment]
Solved per commit cc8c6de81ea2abec564a21e225e95e1cb50aa38a.

Closing this issue
