### ISSUE TITLE
pr.get_distances() ignores kind kwarg when stresses kwarg is passed

### ISSUE THREAD

**Issue by d-brakenhoff** [pastas/pastas#91]
When both the `kind` kwarg and `stresses` kwarg are passed to project.get_distances the kind argument is ignored. My current case is that I have multiple sources of meteorological data. I have a list of stresses from KNMI, and a list of stresses names from another source. I could split up my KNMI stresses into a precipitation list and an evaporation list and just use those, but it would be nice if get_distances allows you to still pass the `kind` kwarg to a subset of stresses.

From project.py get_distances:

```{python}
if stresses is None and kind is None:
    stresses = self.stresses.index
elif stresses is None:
    stresses = self.stresses[self.stresses.kind == kind].index
```

I propose adding the following elif to allow both `kind` and `stresses` to be passed.

```{python}
if stresses is None and kind is None:
    stresses = self.stresses.index
elif stresses is None:
    stresses = self.stresses[self.stresses.kind == kind].index
elif stresses is not None and kind is not None:
    stresses = self.stresses.loc[stresses].loc[self.stresses.kind == kind].index
```

**Comment by raoulcollenteur** [comment]
Yes this makes sense! Can you do this? Maybe check if the other methods depending on get_distances are influenced by this or could be improved too..

**Comment by d-brakenhoff** [comment]
Added logic. 

I checked and only Project.add_recharge() uses this method. We could decide that a subset of stresses can be passed to add_recharge() but I think in that situation it's fine to force the user to explicitly create a StressModel2.
