### ISSUE TITLE
Changes in Pastas related to Pandas 1.0

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#92]
Just read this interesting blog post on Pandas 1.0 which seems to be coming up next year. 
https://www.dataschool.io/future-of-pandas/

Most importantly for us the inplace argument will be removed so we should start removing those from the Pastas code. I think it would be good if we can release a stable Pastas version after the release of Pandas 1.0 as Pastas heavily depends on this package.

Is it an idea to start making a list of what we need to do for such a release?

**Comment by raoulcollenteur** [comment]
Pandas just released 1.0. https://pandas.pydata.org/pandas-docs/version/1.0/whatsnew/v1.0.0.html

**Comment by raoulcollenteur** [comment]
Pandas now starts throwing errors when using strings for selecting date time indices.

Solution:
```
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
```

Maybe we need to do this in importing Pastas

**Comment by rubencalje** [comment]
Can you give an example of the problem?

**Comment by raoulcollenteur** [comment]
Ah yes forgot. 

ml.plot()
plt.xlim("2010", "2018")

will error in the new version.. kind of really annoying.

**Comment by mbakker7** [comment]
Is this known in matplotlib?

**Comment by raoulcollenteur** [comment]
As no other problems came up after bumping to Pandas 1.0 in the last version I think it is save to close this Issue now. I changed the title to reflect that it was in the end only dealing with Pandas 1.0.
